import { DomainParamSetting } from '@/api/main';

export default {
  tableSetting: {
    columnSetting: [
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '单据编号',
        columnKey: null,
        columnName: 'BILL_NO',
        columnType: 'NVARCHAR2',
        columnWidth: 100,
        componentSource: null,
        id: '6626117007636793344',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: true,
        nullable: 'NO',
        seq: 1,
        tableName: 'E_INSPECT_BILL_HEAD',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '单据状态',
        columnKey: null,
        columnName: 'STATUS',
        columnType: 'NVARCHAR2',
        columnWidth: 100,
        componentSource: {
          customDict: {
            dicData: [
              {
                label: '待点检',
                value: 'UNINSPECT',
              },
              {
                label: '点检中',
                value: 'INSPECTING',
              },
              {
                label: '已关闭',
                value: 'CLOSED',
              },
              {
                label: '未完成',
                value: 'UNFINISHED',
              },
            ],
          },
          dataTable: null,
          sourceType: null,
        },
        id: '3915033510965352448',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: true,
        nullable: 'NO',
        seq: 2,
        tableName: 'E_INSPECT_BILL_HEAD',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '点检结果',
        columnKey: null,
        columnName: 'INSPECT_RESULT',
        columnType: 'NVARCHAR2',
        columnWidth: 100,
        // componentSource: {
        //   customDict: {
        //     dicData: [
        //       {
        //         label: '正常',
        //         value: 'OK',
        //       },
        //       {
        //         label: '异常',
        //         value: 'NG',
        //       },
        //     ],
        //   },
        //   dataTable: null,
        //   sourceType: null,
        // },
        id: '4720588182351691776',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: true,
        nullable: 'YES',
        seq: 3,
        tableName: 'E_INSPECT_BILL_HEAD',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '点检执行人',
        columnKey: null,
        columnName: 'userInspectName',
        columnType: 'NVARCHAR2',
        columnWidth: 100,
        componentSource: null,
        id: '5429834828498247680',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: false,
        isHandAdd: true,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: true,
        nullable: null,
        seq: 4,
        tableName: 'S_USER_DEAL',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '模具编码',
        columnKey: null,
        columnName: 'MOULD_CODE',
        columnType: 'NVARCHAR2',
        columnWidth: 100,
        componentSource: null,
        id: '868219092957288448',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: false,
        isHandAdd: true,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: true,
        nullable: null,
        seq: 5,
        tableName: 'M_EQUIPMENT_INFO',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '模具名称',
        columnKey: null,
        columnName: 'MOULD_NAME',
        columnType: 'NVARCHAR2',
        columnWidth: 100,
        componentSource: null,
        id: '4065021259624454144',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: false,
        isHandAdd: true,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: true,
        nullable: null,
        seq: 6,
        tableName: 'M_EQUIPMENT_INFO',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '模具类型',
        columnKey: null,
        columnName: 'mouldType',
        columnType: 'NVARCHAR2',
        columnWidth: 100,
        componentSource: null,
        id: '5757167541422026752',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: false,
        isHandAdd: true,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: true,
        nullable: null,
        seq: 7,
        tableName: 'M_ASSET_TYPE_20240914155506',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '存放位置',
        columnKey: null,
        columnName: 'work_Center_Name',
        columnType: 'NVARCHAR2',
        columnWidth: 100,
        componentSource: null,
        id: '7015548092767854592',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: false,
        isHandAdd: true,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: true,
        nullable: null,
        seq: 8,
        tableName: 'P_WORKCENTER_20240914155723',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '管理部门',
        columnKey: null,
        columnName: 'workshopName',
        columnType: 'NUMBER',
        columnWidth: 100,
        componentSource: null,
        id: '2661645622720200704',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: false,
        isHandAdd: true,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: true,
        nullable: null,
        seq: 9,
        tableName: 'M_EQUIPMENT_INFO',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '完成时间',
        columnKey: null,
        columnName: 'DATETIME_INSPECT_END',
        columnType: 'DATE',
        columnWidth: 100,
        componentSource: null,
        id: '400296099205261312',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: true,
        nullable: 'YES',
        seq: 10,
        tableName: 'E_INSPECT_BILL_HEAD',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '维修单据号',
        columnKey: null,
        columnName: 'REPAIR_BILL_NO',
        columnType: 'NVARCHAR2',
        columnWidth: 100,
        componentSource: null,
        id: '3314265243487387648',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: true,
        nullable: 'YES',
        seq: 11,
        tableName: 'E_INSPECT_BILL_HEAD',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '设备ID',
        columnKey: null,
        columnName: 'M_EQUIPMENT_ID',
        columnType: 'NUMBER(20,0)',
        columnWidth: 100,
        componentSource: null,
        id: '7062689013035089920',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'YES',
        seq: 12,
        tableName: 'E_INSPECT_BILL_HEAD',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '点检人员ID',
        columnKey: null,
        columnName: 'USER_INSPECT_ID',
        columnType: 'NUMBER(20,0)',
        columnWidth: 100,
        componentSource: null,
        id: '7798305596491366400',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'YES',
        seq: 13,
        tableName: 'E_INSPECT_BILL_HEAD',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '点检开始时间',
        columnKey: null,
        columnName: 'DATETIME_INSPECT_START',
        columnType: 'DATE',
        columnWidth: 100,
        componentSource: null,
        id: '9115288559793215488',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'YES',
        seq: 14,
        tableName: 'E_INSPECT_BILL_HEAD',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '模具ID',
        columnKey: null,
        columnName: 'M_MOULD_ID',
        columnType: 'NUMBER',
        columnWidth: 100,
        componentSource: null,
        id: '7624921707487254528',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'YES',
        seq: 15,
        tableName: 'E_INSPECT_BILL_HEAD',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '下次点检时间',
        columnKey: null,
        columnName: 'DATETIME_INSPECT_NEXT',
        columnType: 'DATE',
        columnWidth: 100,
        componentSource: null,
        id: '6310719624705744896',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'YES',
        seq: 16,
        tableName: 'E_INSPECT_BILL_HEAD',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: ' 单据创建来源:JOB;HAND;',
        columnKey: null,
        columnName: 'BILL_SOURCE',
        columnType: 'VARCHAR2',
        columnWidth: 100,
        componentSource: null,
        id: '1721574982443016192',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'YES',
        seq: 17,
        tableName: 'E_INSPECT_BILL_HEAD',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: null,
        columnKey: null,
        columnName: 'ID',
        columnType: 'NUMBER(20,0)',
        columnWidth: 100,
        componentSource: null,
        id: '348973184864354304',
        isAutoWidth: true,
        isDataDefault: true,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'NO',
        seq: 18,
        tableName: 'E_INSPECT_BILL_HEAD',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '创建时间',
        columnKey: null,
        columnName: 'TIME_CREATE',
        columnType: 'DATE',
        columnWidth: 100,
        componentSource: null,
        id: '4562518663897925632',
        isAutoWidth: true,
        isDataDefault: true,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'NO',
        seq: 19,
        tableName: 'E_INSPECT_BILL_HEAD',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '创建人',
        columnKey: null,
        columnName: 'CREATOR',
        columnType: 'NVARCHAR2',
        columnWidth: 100,
        componentSource: null,
        id: '3631389023845883904',
        isAutoWidth: true,
        isDataDefault: true,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'NO',
        seq: 20,
        tableName: 'E_INSPECT_BILL_HEAD',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '修改时间',
        columnKey: null,
        columnName: 'TIME_MODIFIED',
        columnType: 'DATE',
        columnWidth: 100,
        componentSource: null,
        id: '7987769215752443904',
        isAutoWidth: true,
        isDataDefault: true,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'YES',
        seq: 21,
        tableName: 'E_INSPECT_BILL_HEAD',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '修改人',
        columnKey: null,
        columnName: 'MODIFIER',
        columnType: 'NVARCHAR2',
        columnWidth: 100,
        componentSource: null,
        id: '6950071795554177024',
        isAutoWidth: true,
        isDataDefault: true,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'YES',
        seq: 22,
        tableName: 'E_INSPECT_BILL_HEAD',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '1可用；0禁用',
        columnKey: null,
        columnName: 'STATE',
        columnType: 'NUMBER(11,0)',
        columnWidth: 100,
        componentSource: null,
        id: '7348981610891462656',
        isAutoWidth: true,
        isDataDefault: true,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'NO',
        seq: 23,
        tableName: 'E_INSPECT_BILL_HEAD',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '企业ID',
        columnKey: null,
        columnName: 'EID',
        columnType: 'NUMBER(20,0)',
        columnWidth: 100,
        componentSource: null,
        id: '6593579625172670464',
        isAutoWidth: true,
        isDataDefault: true,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'NO',
        seq: 24,
        tableName: 'E_INSPECT_BILL_HEAD',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '组织ID',
        columnKey: null,
        columnName: 'OID',
        columnType: 'NUMBER(20,0)',
        columnWidth: 100,
        componentSource: null,
        id: '2854643569776189440',
        isAutoWidth: true,
        isDataDefault: true,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'NO',
        seq: 25,
        tableName: 'E_INSPECT_BILL_HEAD',
      },
    ],
    isAutoLoad: true,
    pageSize: null,
    sortField: 'time_create',
    sortType: 'desc',
    tableTitle: '模具点检单据列表',
    usePage: true,
  },
} as DomainParamSetting;
