import { DomainParamButtonSetting } from '@/api/main';

export default {
  formColumnSetting: [
    {
      columnType: 'NUMBER(20,0)',
      component: 'bcmp-select-business',
      componentParam: 'repairItem',
      componentSource: null,
      defaultValue: '',
      field: 'E_REPAIR_ITEM_ID',
      fieldType: null,
      id: '7466291270946531328',
      isDisabled: false,
      isKeyField: true,
      isMultiple: false,
      isRequired: true,
      isVisible: true,
      label: '故障项目',
      parentField: null,
      placeholder: null,
      seq: 0,
      verifyExp: '',
    },
    {
      columnType: 'NUMBER(20,0)',
      component: 'bcmp-select-business',
      componentParam: 'assetType',
      componentSource: null,
      defaultValue: '',
      field: 'M_ASSET_TYPE_ID',
      fieldType: null,
      id: '3404344103765139456',
      isDisabled: false,
      isKeyField: true,
      isMultiple: false,
      isRequired: true,
      isVisible: true,
      label: '资产类型',
      parentField: null,
      placeholder: null,
      seq: 1,
      verifyExp: '',
    },
    {
      columnType: 'NUMBER(20,0)',
      component: 'bcmp-select-business',
      componentParam: 'assetBrand',
      componentSource: null,
      defaultValue: '',
      field: 'M_ASSET_BRAND_ID',
      fieldType: null,
      id: '6751981240357718016',
      isDisabled: false,
      isKeyField: true,
      isMultiple: false,
      isRequired: false,
      isVisible: true,
      label: '资产品牌',
      parentField: 'M_ASSET_TYPE_ID',
      placeholder: null,
      seq: 2,
      verifyExp: '',
    },
    {
      columnType: 'NUMBER(20,0)',
      component: 'bcmp-select-business',
      componentParam: 'assetModel',
      componentSource: null,
      defaultValue: '',
      field: 'M_ASSET_MODEL_ID',
      fieldType: null,
      id: '8113433758230585344',
      isDisabled: false,
      isKeyField: true,
      isMultiple: false,
      isRequired: false,
      isVisible: true,
      label: '资产型号',
      parentField: 'M_ASSET_MODEL_ID',
      placeholder: null,
      seq: 3,
      verifyExp: '',
    },
    {
      columnType: 'NVARCHAR2',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      field: 'MOULD_TYPE',
      fieldType: null,
      id: '8527838259359653888',
      isDisabled: false,
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,
      label: '模具类型',
      parentField: null,
      placeholder: null,
      seq: 4,
      verifyExp: '',
    },
    {
      columnType: 'NUMBER(20,0)',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      field: 'M_MOULD_ID',
      fieldType: null,
      id: '3782245668613738496',
      isDisabled: false,
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,
      label: '模具表ID',
      parentField: null,
      placeholder: null,
      seq: 5,
      verifyExp: '',
    },
    {
      columnType: 'NUMBER(20,0)',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      field: 'ID',
      fieldType: null,
      id: '4312510086869680128',
      isDisabled: false,
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,
      label: null,
      parentField: null,
      placeholder: null,
      seq: 6,
      verifyExp: '',
    },
    {
      columnType: 'DATE',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      field: 'TIME_CREATE',
      fieldType: null,
      id: '3529826750495735808',
      isDisabled: false,
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,
      label: '创建时间',
      parentField: null,
      placeholder: null,
      seq: 7,
      verifyExp: '',
    },
    {
      columnType: 'NVARCHAR2',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      field: 'CREATOR',
      fieldType: null,
      id: '1882158446109140992',
      isDisabled: false,
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,
      label: '创建人',
      parentField: null,
      placeholder: null,
      seq: 8,
      verifyExp: '',
    },
    {
      columnType: 'DATE',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      field: 'TIME_MODIFIED',
      fieldType: null,
      id: '7585700625961766912',
      isDisabled: false,
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,
      label: '修改时间',
      parentField: null,
      placeholder: null,
      seq: 9,
      verifyExp: '',
    },
    {
      columnType: 'NVARCHAR2',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      field: 'MODIFIER',
      fieldType: null,
      id: '3676150610216034304',
      isDisabled: false,
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,
      label: '修改人',
      parentField: null,
      placeholder: null,
      seq: 10,
      verifyExp: '',
    },
    {
      columnType: 'NUMBER(11,0)',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      field: 'STATE',
      fieldType: null,
      id: '4029497752553381888',
      isDisabled: false,
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,
      label: '1可用；0禁用',
      parentField: null,
      placeholder: null,
      seq: 11,
      verifyExp: '',
    },
    {
      columnType: 'NUMBER(20,0)',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      field: 'EID',
      fieldType: null,
      id: '8386970110309924864',
      isDisabled: false,
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,
      label: '企业ID',
      parentField: null,
      placeholder: null,
      seq: 12,
      verifyExp: '',
    },
    {
      columnType: 'NUMBER(20,0)',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      field: 'OID',
      fieldType: null,
      id: '4526138493648908288',
      isDisabled: false,
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,
      label: '组织ID',
      parentField: null,
      placeholder: null,
      seq: 13,
      verifyExp: '',
    },
  ],
} as DomainParamButtonSetting;
