import { DomainParamSetting } from '@/api/main';

export default {
  tableSetting: {
    columnSetting: [
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '资产类型编码',
        columnKey: null,
        columnName: 'assetTypeCode',
        columnType: 'NVARCHAR2',
        columnWidth: 100,
        componentSource: null,
        id: '7492371821441792000',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: false,
        isHandAdd: true,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: true,
        nullable: null,
        seq: -4,
        tableName: 'M_ASSET_TYPE_20240904175554',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '资产类型名称',
        columnKey: null,
        columnName: 'assetTypeName',
        columnType: 'NVARCHAR2',
        columnWidth: 100,
        componentSource: null,
        id: '8820288903625957376',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: false,
        isHandAdd: true,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: true,
        nullable: null,
        seq: -3,
        tableName: 'M_ASSET_TYPE_20240904175554',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '资产品牌名称',
        columnKey: null,
        columnName: 'assetBrandName',
        columnType: 'NVARCHAR2',
        columnWidth: 100,
        componentSource: null,
        id: '2398884145742858240',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: false,
        isHandAdd: true,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: true,
        nullable: null,
        seq: -2,
        tableName: 'M_ASSET_BRAND_20240904175614',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '资产型号名称',
        columnKey: null,
        columnName: 'assetModelName',
        columnType: 'NVARCHAR2',
        columnWidth: 100,
        componentSource: null,
        id: '6376883820368072704',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: false,
        isHandAdd: true,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: true,
        nullable: null,
        seq: -1,
        tableName: 'M_ASSET_MODEL_20240904175636',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '故障项目表ID',
        columnKey: null,
        columnName: 'E_REPAIR_ITEM_ID',
        columnType: 'NUMBER(20,0)',
        columnWidth: 100,
        componentSource: null,
        id: '7466291270946531328',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'YES',
        seq: 0,
        tableName: 'E_REPAIR_ITEM_IN_EQUIPMENT',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '资产类型表ID',
        columnKey: null,
        columnName: 'M_ASSET_TYPE_ID',
        columnType: 'NUMBER(20,0)',
        columnWidth: 100,
        componentSource: null,
        id: '3404344103765139456',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'YES',
        seq: 1,
        tableName: 'E_REPAIR_ITEM_IN_EQUIPMENT',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '资产品牌表ID',
        columnKey: null,
        columnName: 'M_ASSET_BRAND_ID',
        columnType: 'NUMBER(20,0)',
        columnWidth: 100,
        componentSource: null,
        id: '6751981240357718016',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'YES',
        seq: 2,
        tableName: 'E_REPAIR_ITEM_IN_EQUIPMENT',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '资产型号表ID',
        columnKey: null,
        columnName: 'M_ASSET_MODEL_ID',
        columnType: 'NUMBER(20,0)',
        columnWidth: 100,
        componentSource: null,
        id: '8113433758230585344',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'YES',
        seq: 3,
        tableName: 'E_REPAIR_ITEM_IN_EQUIPMENT',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '模具类型',
        columnKey: null,
        columnName: 'MOULD_TYPE',
        columnType: 'NVARCHAR2',
        columnWidth: 100,
        componentSource: null,
        id: '8527838259359653888',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'YES',
        seq: 4,
        tableName: 'E_REPAIR_ITEM_IN_EQUIPMENT',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '模具表ID',
        columnKey: null,
        columnName: 'M_MOULD_ID',
        columnType: 'NUMBER(20,0)',
        columnWidth: 100,
        componentSource: null,
        id: '3782245668613738496',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'YES',
        seq: 5,
        tableName: 'E_REPAIR_ITEM_IN_EQUIPMENT',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: null,
        columnKey: null,
        columnName: 'ID',
        columnType: 'NUMBER(20,0)',
        columnWidth: 100,
        componentSource: null,
        id: '4312510086869680128',
        isAutoWidth: true,
        isDataDefault: true,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'NO',
        seq: 6,
        tableName: 'E_REPAIR_ITEM_IN_EQUIPMENT',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '创建时间',
        columnKey: null,
        columnName: 'TIME_CREATE',
        columnType: 'DATE',
        columnWidth: 100,
        componentSource: null,
        id: '3529826750495735808',
        isAutoWidth: true,
        isDataDefault: true,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'NO',
        seq: 7,
        tableName: 'E_REPAIR_ITEM_IN_EQUIPMENT',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '创建人',
        columnKey: null,
        columnName: 'CREATOR',
        columnType: 'NVARCHAR2',
        columnWidth: 100,
        componentSource: null,
        id: '1882158446109140992',
        isAutoWidth: true,
        isDataDefault: true,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'NO',
        seq: 8,
        tableName: 'E_REPAIR_ITEM_IN_EQUIPMENT',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '修改时间',
        columnKey: null,
        columnName: 'TIME_MODIFIED',
        columnType: 'DATE',
        columnWidth: 100,
        componentSource: null,
        id: '7585700625961766912',
        isAutoWidth: true,
        isDataDefault: true,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'YES',
        seq: 9,
        tableName: 'E_REPAIR_ITEM_IN_EQUIPMENT',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '修改人',
        columnKey: null,
        columnName: 'MODIFIER',
        columnType: 'NVARCHAR2',
        columnWidth: 100,
        componentSource: null,
        id: '3676150610216034304',
        isAutoWidth: true,
        isDataDefault: true,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'YES',
        seq: 10,
        tableName: 'E_REPAIR_ITEM_IN_EQUIPMENT',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '1可用；0禁用',
        columnKey: null,
        columnName: 'STATE',
        columnType: 'NUMBER(11,0)',
        columnWidth: 100,
        componentSource: null,
        id: '4029497752553381888',
        isAutoWidth: true,
        isDataDefault: true,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'NO',
        seq: 11,
        tableName: 'E_REPAIR_ITEM_IN_EQUIPMENT',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '企业ID',
        columnKey: null,
        columnName: 'EID',
        columnType: 'NUMBER(20,0)',
        columnWidth: 100,
        componentSource: null,
        id: '8386970110309924864',
        isAutoWidth: true,
        isDataDefault: true,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'NO',
        seq: 12,
        tableName: 'E_REPAIR_ITEM_IN_EQUIPMENT',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '组织ID',
        columnKey: null,
        columnName: 'OID',
        columnType: 'NUMBER(20,0)',
        columnWidth: 100,
        componentSource: null,
        id: '4526138493648908288',
        isAutoWidth: true,
        isDataDefault: true,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'NO',
        seq: 13,
        tableName: 'E_REPAIR_ITEM_IN_EQUIPMENT',
      },
    ],
    isAutoLoad: true,
    pageSize: null,
    sortField: 'time_create',
    sortType: 'desc',
    tableTitle: '设备与维修项目关系',
    usePage: true,
  },
} as DomainParamSetting;
