import { DomainParamButtonSetting } from '@/api/main';

export default {
  formColumnSetting: [
    {
      columnType: 'varchar(80)',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      field: 'maintenance_plan_code',
      fieldType: null,
      id: '1979249244809189376',
      isDisabled: false,
      isKeyField: true,
      isMultiple: false,
      isRequired: true,
      isVisible: true,
      label: '保养计划代码',
      parentField: null,
      placeholder: null,
      seq: 1,
      verifyExp: '',
    },
    {
      columnType: 'varchar(240)',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      field: 'maintenance_plan_name',
      fieldType: null,
      id: '6430913614447872000',
      isDisabled: false,
      isKeyField: false,
      isMultiple: false,
      isRequired: true,
      isVisible: true,
      label: '保养计划名称',
      parentField: null,
      placeholder: null,
      seq: 2,
      verifyExp: '',
    },
    {
      columnType: 'varchar(80)',
      component: 't-radio-group',
      componentParam: '',
      componentSource: {
        customDict: {
          dicData: [
            {
              label: '周期保养',
              value: 'PERIOD',
            },
            {
              label: '使用次数',
              value: 'USETIME',
            },
          ],
        },
        dataTable: {
          conditionData: [],
          mapBusinessDomain: '',
          mapTable: '',
          showField: '',
          valueField: '',
        },
        sourceType: 'customDict',
      },
      defaultValue: 'PERIOD',
      isDisabled: false,
      field: 'maintenance_plan_type',
      fieldType: null,
      id: '5781640216176422912',

      isKeyField: false,
      isMultiple: false,
      isRequired: true,
      isVisible: true,

      label: '保养计划方式',

      placeholder: null,

      seq: 3,
      verifyExp: '',
    },
    {
      columnType: 'datetime(4)',
      component: 't-date-picker',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      field: 'datetime_effect',
      fieldType: null,
      id: '7582449786451361792',
      isDisabled: false,
      isKeyField: false,
      isMultiple: false,
      isRequired: true,
      isVisible: true,
      label: '生效时间',
      parentField: null,
      placeholder: null,
      seq: 4,
      verifyExp: '',
    },
    {
      columnType: 'int',
      component: 't-input-number',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      field: 'day_maintenance_period',
      fieldType: null,
      id: '8079611604183496704',
      isDisabled: false,
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: true,
      label: '保计划养周期（天）',
      parentField: null,
      placeholder: null,
      seq: 5,
      verifyExp: '',
    },
    {
      columnType: 'int',
      component: 't-input-number',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      field: 'day_early_warn',
      fieldType: null,
      id: '1957731539453566976',
      isDisabled: false,
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: true,
      label: '预警提前期（天）',
      parentField: null,
      placeholder: null,
      seq: 6,
      verifyExp: '',
    },
    {
      columnType: 'int',
      component: 't-input-number',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      field: 'hour_run',
      fieldType: null,
      id: '4228583883284498432',
      isDisabled: false,
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,
      label: '运行时长（小时）',
      parentField: null,
      placeholder: null,
      seq: 7,
      verifyExp: '',
    },
    {
      columnType: 'int',
      component: 't-input-number',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      field: 'hour_run_early',
      fieldType: null,
      id: '2861171201225009152',
      isDisabled: false,
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,
      label: '提前运行时间（小时）',
      parentField: null,
      placeholder: null,
      seq: 8,
      verifyExp: '',
    },
    {
      columnType: 'varchar(80)',
      component: 'bcmp-select-param',
      componentParam: 'E_MOULD_TYPE',
      componentSource: null,
      defaultValue: '',
      field: 'mould_type',
      fieldType: null,
      id: '1191873293498304512',
      isDisabled: false,
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,
      label: '模具类型',
      parentField: null,
      placeholder: null,
      seq: 9,
      verifyExp: '',
    },
    {
      columnType: 'bigint',
      component: 'bcmp-select-business',
      componentParam: 'mould',
      componentSource: null,
      defaultValue: '',
      field: 'm_mould_id',
      fieldType: null,
      id: '6372160288314134528',
      isDisabled: false,
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,
      label: '模具',
      parentField: null,
      placeholder: null,
      seq: 10,
      verifyExp: '',
    },
    {
      columnType: 'int',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      field: 'state',
      fieldType: null,
      id: '6848017972128808960',
      isDisabled: false,
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,
      label: '状态',
      parentField: null,
      placeholder: null,
      seq: 11,
      verifyExp: '',
    },
    {
      columnType: 'datetime(4)',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      field: 'time_create',
      fieldType: null,
      id: '4750236166081570816',
      isDisabled: false,
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,
      label: '创建时间',
      parentField: null,
      placeholder: null,
      seq: 12,
      verifyExp: '',
    },
    {
      columnType: 'bigint',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      field: 'id',
      fieldType: null,
      id: '6294374149532706816',
      isDisabled: false,
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,
      label: '',
      parentField: null,
      placeholder: null,
      seq: 13,
      verifyExp: '',
    },
    {
      columnType: 'bigint',
      component: 'bcmp-select-business',
      componentParam: 'assetType',
      componentSource: null,
      defaultValue: '',
      field: 'm_asset_type_id',
      fieldType: null,
      id: '196172220756541440',
      isDisabled: false,
      isKeyField: false,
      isMultiple: false,
      isRequired: true,
      isVisible: true,
      label: '资产类型',
      parentField: null,
      placeholder: null,
      seq: 14,
      verifyExp: '',
    },
    {
      columnType: 'bigint',
      component: 'bcmp-select-business',
      componentParam: 'assetBrand',
      componentSource: null,
      defaultValue: '',
      field: 'm_asset_brand_id',
      fieldType: null,
      id: '7194000198495977472',
      isDisabled: false,
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: true,
      label: '资产品牌',
      parentField: 'm_asset_type_id',
      placeholder: null,
      seq: 15,
      verifyExp: '',
    },
    {
      columnType: 'bigint',
      component: 'bcmp-select-business',
      componentParam: 'assetModel',
      componentSource: null,
      defaultValue: '',
      field: 'm_asset_model_id',
      fieldType: null,
      id: '5356558238514077696',
      isDisabled: false,
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: true,
      label: '资产型号',
      parentField: 'm_asset_brand_id',
      placeholder: null,
      seq: 16,
      verifyExp: '',
    },
    {
      columnType: 'varchar(80)',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      field: 'creator',
      fieldType: null,
      id: '658595641727797248',
      isDisabled: false,
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,
      label: '创建人',
      parentField: null,
      placeholder: null,
      seq: 17,
      verifyExp: '',
    },
    {
      columnType: 'datetime(4)',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      field: 'time_modified',
      fieldType: null,
      id: '9147958099678668800',
      isDisabled: false,
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,
      label: '修改时间',
      parentField: null,
      placeholder: null,
      seq: 18,
      verifyExp: '',
    },
    {
      columnType: 'varchar(80)',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      field: 'modifier',
      fieldType: null,
      id: '3019427964243161088',
      isDisabled: false,
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,
      label: '修改人',
      parentField: null,
      placeholder: null,
      seq: 19,
      verifyExp: '',
    },
    {
      columnType: 'bigint',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      field: 'eid',
      fieldType: null,
      id: '7989769675184011264',
      isDisabled: false,
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,
      label: '企业ID',
      parentField: null,
      placeholder: null,
      seq: 20,
      verifyExp: '',
    },
    {
      columnType: 'bigint',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      field: 'oid',
      fieldType: null,
      id: '3195778080208447488',
      isDisabled: false,
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,
      label: '组织ID',
      parentField: null,
      placeholder: null,
      seq: 21,
      verifyExp: '',
    },
  ],
} as DomainParamButtonSetting;
