import { DomainParamButtonSetting } from '@/api/main';

export default {
  formColumnSetting: [
    {
      seq: 1,
      id: '2285418535176525824',
      field: 'mould_code',
      label: '模具代码',
      component: 't-input',
      componentParam: '',
      placeholder: null,
      defaultValue: '',
      fieldType: null,
      columnType: 'varchar(80)',
      verifyExp: '',
      componentSource: null,
      isVisible: true,
      isDisabled: true,
      isMultiple: false,
      isRequired: true,
      isKeyField: true,
    },
    {
      seq: 2,
      id: '4646315149008599040',
      field: 'mould_name',
      label: '模具名称',
      component: 't-input',
      componentParam: '',
      placeholder: null,
      defaultValue: '',
      fieldType: null,
      columnType: 'varchar(240)',
      verifyExp: '',
      componentSource: null,
      isVisible: true,
      isDisabled: false,
      isMultiple: false,
      isRequired: true,
      isKeyField: false,
    },
    {
      seq: 3,
      id: '5145692567556231168',
      field: 'mould_type',
      label: '模具类型',
      component: 'bcmp-select-param',
      componentParam: 'E_MOULD_TYPE',
      placeholder: null,
      defaultValue: '',
      fieldType: null,
      columnType: 'varchar(80)',
      verifyExp: '',
      componentSource: null,
      isVisible: true,
      isDisabled: false,
      isMultiple: false,
      isRequired: true,
      isKeyField: false,
    },
    {
      seq: 4,
      id: '6822321945146140672',
      field: 'mould_desc',
      label: '模具描述',
      component: 't-input',
      componentParam: '',
      placeholder: null,
      defaultValue: '',
      fieldType: null,
      columnType: 'varchar(2000)',
      verifyExp: '',
      componentSource: null,
      isVisible: true,
      isDisabled: false,
      isMultiple: false,
      isRequired: false,
      isKeyField: false,
    },
    {
      seq: 5,
      id: '6100287561399015424',
      field: 'is_mul_mode',
      label: '一模多穴',
      component: 't-radio-group',
      componentParam: '',
      placeholder: null,
      defaultValue: '1',
      fieldType: null,
      columnType: 'int',
      verifyExp: '',
      componentSource: {
        sourceType: 'customDict',
        customDict: {
          dicData: [
            {
              label: '是',
              value: '1',
            },
            {
              label: '否',
              value: '0',
            },
          ],
        },
        dataTable: {
          mapBusinessDomain: '',
          mapTable: '',
          conditionData: [],
          valueField: '',
          showField: '',
        },
      },
      isVisible: true,
      isDisabled: false,
      isMultiple: false,
      isRequired: true,
      isKeyField: false,
    },
    {
      seq: 6,
      id: '3530687092750663680',
      field: 'cavity_number',
      label: '型腔数',
      component: 't-input-number',
      componentParam: '',
      placeholder: null,
      defaultValue: '',
      fieldType: null,
      columnType: 'int',
      verifyExp: '',
      componentSource: null,
      isVisible: true,
      isDisabled: false,
      isMultiple: false,
      isRequired: true,
      isKeyField: false,
    },
    {
      seq: 7,
      id: '5363064168543293440',
      field: 'status',
      label: '管理状态',
      component: 'bcmp-select-param',
      componentParam: 'E_MOULD_STATUS',
      placeholder: null,
      defaultValue: '',
      fieldType: null,
      columnType: 'varchar(80)',
      verifyExp: '',
      componentSource: null,
      isVisible: true,
      isDisabled: false,
      isMultiple: false,
      isRequired: true,
      isKeyField: false,
    },
    {
      seq: 8,
      id: '6276986324658425856',
      field: 'life_time',
      label: '使用寿命',
      component: 't-input-number',
      componentParam: '',
      placeholder: null,
      defaultValue: '',
      fieldType: null,
      columnType: 'int',
      verifyExp: '',
      componentSource: null,
      isVisible: true,
      isDisabled: false,
      isMultiple: false,
      isRequired: false,
      isKeyField: false,
    },
    {
      seq: 9,
      id: '8281116790299037696',
      field: 'mould_size',
      label: '模具尺寸',
      component: 't-input',
      componentParam: '',
      placeholder: null,
      defaultValue: '',
      fieldType: null,
      columnType: 'varchar(240)',
      verifyExp: '',
      componentSource: null,
      isVisible: true,
      isDisabled: false,
      isMultiple: false,
      isRequired: false,
      isKeyField: false,
    },
    {
      seq: 10,
      id: '4594231664977162240',
      field: 'drawing_no',
      label: '图纸编号',
      component: 't-input',
      componentParam: '',
      placeholder: null,
      defaultValue: '',
      fieldType: null,
      columnType: 'varchar(80)',
      verifyExp: '',
      componentSource: null,
      isVisible: true,
      isDisabled: false,
      isMultiple: false,
      isRequired: true,
      isKeyField: false,
    },
    {
      seq: 11,
      id: '2398335752604854272',
      field: 'datetime_effect',
      label: '生效时间',
      component: 't-date-picker',
      componentParam: '',
      placeholder: null,
      defaultValue: '',
      fieldType: null,
      columnType: 'datetime(4)',
      verifyExp: '',
      componentSource: null,
      isVisible: true,
      isDisabled: false,
      isMultiple: false,
      isRequired: true,
      isKeyField: false,
    },
    {
      seq: 12,
      id: '3700276295988484096',
      field: 'datetime_invalid',
      label: '失效时间',
      component: 't-date-picker',
      componentParam: '',
      placeholder: null,
      defaultValue: '',
      fieldType: null,
      columnType: 'datetime(4)',
      verifyExp: '',
      componentSource: null,
      isVisible: true,
      isDisabled: false,
      isMultiple: false,
      isRequired: false,
      isKeyField: false,
    },
    {
      seq: 13,
      id: '2721070477307887616',
      field: 'mould_supplier_id',
      label: '模具供应商',
      component: 'bcmp-select-business',
      componentParam: 'supplier',
      placeholder: null,
      defaultValue: '',
      fieldType: null,
      columnType: 'bigint',
      verifyExp: '',
      componentSource: null,
      isVisible: true,
      isDisabled: false,
      isMultiple: false,
      isRequired: false,
      isKeyField: false,
    },
    {
      seq: 14,
      id: '1996315299009398784',
      field: 'm_warehouse_id',
      label: '存放仓库',
      component: 'bcmp-select-business',
      componentParam: 'warehouse',
      placeholder: null,
      defaultValue: '',
      fieldType: null,
      columnType: 'bigint',
      verifyExp: '',
      componentSource: null,
      isVisible: true,
      isDisabled: false,
      isMultiple: false,
      isRequired: false,
      isKeyField: false,
    },
    {
      seq: 15,
      id: '5628098309117079552',
      field: 'w_district_id',
      label: '存放模架',
      component: 'bcmp-select-business',
      componentParam: 'district',
      parentField: 'm_warehouse_id',
      placeholder: null,
      defaultValue: '',
      fieldType: null,
      columnType: 'bigint',
      verifyExp: '',
      componentSource: null,
      isVisible: true,
      isDisabled: false,
      isMultiple: false,
      isRequired: false,
      isKeyField: false,
    },
    {
      seq: 16,
      id: '3695271518609461248',
      field: 'w_loc_id',
      label: '存放位置',
      parentField: 'w_district_id',
      component: 'bcmp-select-business',
      componentParam: 'location',
      placeholder: null,
      defaultValue: '',
      fieldType: null,
      columnType: 'bigint',
      verifyExp: '',
      componentSource: null,
      isVisible: true,
      isDisabled: false,
      isMultiple: false,
      isRequired: false,
      isKeyField: false,
    },
    {
      seq: 17,
      id: '4493168118760359936',
      field: 'molding_cycle',
      label: '成型周期',
      component: 't-input-number',
      componentParam: '',
      placeholder: null,
      defaultValue: '',
      fieldType: null,
      columnType: 'decimal(10,2)',
      verifyExp: '',
      componentSource: null,
      isVisible: true,
      isDisabled: false,
      isMultiple: false,
      isRequired: false,
      isKeyField: false,
    },
    {
      seq: 18,
      id: '881590170010204160',
      field: 'molding_cycle_max',
      label: '成型上偏差',
      component: 't-input-number',
      componentParam: '',
      placeholder: null,
      defaultValue: '',
      fieldType: null,
      columnType: 'decimal(10,2)',
      verifyExp: '',
      componentSource: null,
      isVisible: true,
      isDisabled: false,
      isMultiple: false,
      isRequired: false,
      isKeyField: false,
    },
    {
      seq: 19,
      id: '1568185396752343040',
      field: 'molding_cycle_min',
      label: '成型下偏差',
      component: 't-input-number',
      componentParam: '',
      placeholder: null,
      defaultValue: '',
      fieldType: null,
      columnType: 'decimal(10,2)',
      verifyExp: '',
      componentSource: null,
      isVisible: true,
      isDisabled: false,
      isMultiple: false,
      isRequired: false,
      isKeyField: false,
    },
    {
      seq: 20,
      id: '7133268008107317248',
      field: 'repair_deal_id',
      label: '维修处理组ID',
      component: 'bcmp-select-business',
      componentParam: 'supportGroup',
      placeholder: null,
      defaultValue: '',
      fieldType: null,
      columnType: 'bigint',
      verifyExp: '',
      componentSource: null,
      isVisible: true,
      isDisabled: false,
      isMultiple: false,
      isRequired: false,
      isKeyField: false,
    },
    {
      seq: 21,
      id: '5825001759040468992',
      field: 'repair_accept_id',
      label: '维修验收组ID',
      component: 'bcmp-select-business',
      componentParam: 'supportGroup',
      placeholder: null,
      defaultValue: '',
      fieldType: null,
      columnType: 'bigint',
      verifyExp: '',
      componentSource: null,
      isVisible: true,
      isDisabled: false,
      isMultiple: false,
      isRequired: false,
      isKeyField: false,
    },
    {
      seq: 22,
      id: '860484300907347968',
      field: 'maintenance_deal_id',
      label: '保养处理组ID',
      component: 'bcmp-select-business',
      componentParam: 'supportGroup',
      placeholder: null,
      defaultValue: '',
      fieldType: null,
      columnType: 'bigint',
      verifyExp: '',
      componentSource: null,
      isVisible: true,
      isDisabled: false,
      isMultiple: false,
      isRequired: false,
      isKeyField: false,
    },
    {
      seq: 23,
      id: '7247511504459790336',
      field: 'maintenance_accept_id',
      label: '保养验收组ID',
      component: 'bcmp-select-business',
      componentParam: 'supportGroup',
      placeholder: null,
      defaultValue: '',
      fieldType: null,
      columnType: 'bigint',
      verifyExp: '',
      componentSource: null,
      isVisible: true,
      isDisabled: false,
      isMultiple: false,
      isRequired: false,
      isKeyField: false,
    },
    {
      seq: 24,
      id: '5307248031152431104',
      field: 'source_mould_code',
      label: '源模具编码',
      component: 't-input',
      componentParam: '',
      placeholder: null,
      defaultValue: '',
      fieldType: null,
      columnType: 'varchar(80)',
      verifyExp: '',
      componentSource: null,
      isVisible: true,
      isDisabled: false,
      isMultiple: false,
      isRequired: false,
      isKeyField: false,
    },
    {
      seq: 25,
      id: '5062851217394386944',
      field: 'owner_oid',
      label: '所属部门ID',
      component: 'bcmp-select-business',
      componentParam: 'adminOrg',
      placeholder: null,
      defaultValue: '',
      fieldType: null,
      columnType: 'bigint',
      verifyExp: '',
      componentSource: null,
      isVisible: true,
      isDisabled: false,
      isMultiple: false,
      isRequired: false,
      isKeyField: false,
    },
    {
      seq: 26,
      id: '648443324106840064',
      field: 'position',
      label: '存放地点',
      component: 't-input',
      componentParam: '',
      placeholder: null,
      defaultValue: '',
      fieldType: null,
      columnType: 'varchar(2000)',
      verifyExp: '',
      componentSource: null,
      isVisible: false,
      isDisabled: false,
      isMultiple: false,
      isRequired: false,
      isKeyField: false,
    },
    {
      seq: 27,
      id: '5028892141798502400',
      field: 'creator',
      label: '创建人',
      component: 't-input',
      componentParam: '',
      placeholder: null,
      defaultValue: '',
      fieldType: null,
      columnType: 'varchar(80)',
      verifyExp: '',
      componentSource: null,
      isVisible: false,
      isDisabled: false,
      isMultiple: false,
      isRequired: false,
      isKeyField: false,
    },
    {
      seq: 28,
      id: '3150474983722315776',
      field: 'eid',
      label: '企业ID',
      component: 't-input',
      componentParam: '',
      placeholder: null,
      defaultValue: '',
      fieldType: null,
      columnType: 'bigint',
      verifyExp: '',
      componentSource: null,
      isVisible: false,
      isDisabled: false,
      isMultiple: false,
      isRequired: false,
      isKeyField: false,
    },
    {
      seq: 29,
      id: '7251497857913159680',
      field: 'id',
      label: '',
      component: 't-input',
      componentParam: '',
      placeholder: null,
      defaultValue: '',
      fieldType: null,
      columnType: 'bigint',
      verifyExp: '',
      componentSource: null,
      isVisible: false,
      isDisabled: false,
      isMultiple: false,
      isRequired: false,
      isKeyField: false,
    },
    {
      seq: 30,
      id: '8735484834941782016',
      field: 'modifier',
      label: '修改人',
      component: 't-input',
      componentParam: '',
      placeholder: null,
      defaultValue: '',
      fieldType: null,
      columnType: 'varchar(80)',
      verifyExp: '',
      componentSource: null,
      isVisible: false,
      isDisabled: false,
      isMultiple: false,
      isRequired: false,
      isKeyField: false,
    },
    {
      seq: 31,
      id: '3242165794038982656',
      field: 'oid',
      label: '组织ID',
      component: 't-input',
      componentParam: '',
      placeholder: null,
      defaultValue: '',
      fieldType: null,
      columnType: 'bigint',
      verifyExp: '',
      componentSource: null,
      isVisible: false,
      isDisabled: false,
      isMultiple: false,
      isRequired: false,
      isKeyField: false,
    },
    {
      seq: 32,
      id: '4243135370688477184',
      field: 'state',
      label: '1可用；0禁用',
      component: 't-input',
      componentParam: '',
      placeholder: null,
      defaultValue: '',
      fieldType: null,
      columnType: 'int',
      verifyExp: '',
      componentSource: null,
      isVisible: false,
      isDisabled: false,
      isMultiple: false,
      isRequired: false,
      isKeyField: false,
    },
    {
      seq: 33,
      id: '1708633160171360256',
      field: 'time_create',
      label: '创建时间',
      component: 't-input',
      componentParam: '',
      placeholder: null,
      defaultValue: '',
      fieldType: null,
      columnType: 'datetime(4)',
      verifyExp: '',
      componentSource: null,
      isVisible: false,
      isDisabled: false,
      isMultiple: false,
      isRequired: false,
      isKeyField: false,
    },
    {
      seq: 34,
      id: '1315258483207671808',
      field: 'time_modified',
      label: '修改时间',
      component: 't-input',
      componentParam: '',
      placeholder: null,
      defaultValue: '',
      fieldType: null,
      columnType: 'datetime(4)',
      verifyExp: '',
      componentSource: null,
      isVisible: false,
      isDisabled: false,
      isMultiple: false,
      isRequired: false,
      isKeyField: false,
    },
  ],
} as DomainParamButtonSetting;
