import { DomainParamSetting } from '@/api/main';

export default {
  tableSetting: {
    tableTitle: '模具档案',
    usePage: true,
    pageSize: null,
    sortField: 'time_create',
    sortType: 'desc',
    columnSetting: [
      {
        seq: 1,
        id: '2285418535176525824',
        columnDefault: null,
        columnDesc: '模具编码',
        columnKey: '',
        columnName: 'mould_code',
        columnType: 'varchar(80)',
        nullable: 'NO',
        tableName: 'm_mould',
        columnWidth: 100,
        align: 'center',
        canDelete: false,
        isDatabaseField: true,
        isAutoWidth: false,
        isVisible: true,
        isLeftFixed: false,
        isRightFixed: false,
        isDataDefault: false,
        isHandAdd: false,
      },
      {
        seq: 2,
        id: '4646315149008599040',
        columnDefault: null,
        columnDesc: '模具名称',
        columnKey: '',
        columnName: 'mould_name',
        columnType: 'varchar(240)',
        nullable: 'NO',
        tableName: 'm_mould',
        columnWidth: 100,
        align: 'center',
        canDelete: false,
        isDatabaseField: true,
        isAutoWidth: false,
        isVisible: true,
        isLeftFixed: false,
        isRightFixed: false,
        isDataDefault: false,
        isHandAdd: false,
      },
      {
        seq: 3,
        id: '6822321945146140672',
        columnDefault: null,
        columnDesc: '模具描述',
        columnKey: '',
        columnName: 'mould_desc',
        columnType: 'varchar(2000)',
        nullable: 'YES',
        tableName: 'm_mould',
        columnWidth: 100,
        align: 'center',
        canDelete: false,
        isDatabaseField: true,
        isAutoWidth: false,
        isVisible: true,
        isLeftFixed: false,
        isRightFixed: false,
        isDataDefault: false,
        isHandAdd: false,
      },
      {
        seq: 4,
        id: '5145692567556231168',
        columnDefault: null,
        columnDesc: '模具类型',
        columnKey: '',
        columnName: 'mould_type',
        columnType: 'varchar(80)',
        nullable: 'NO',
        tableName: 'm_mould',
        columnWidth: 100,
        align: 'center',
        canDelete: false,
        isDatabaseField: true,
        isAutoWidth: false,
        isVisible: true,
        isLeftFixed: false,
        isRightFixed: false,
        isDataDefault: false,
        isHandAdd: false,
      },
      {
        seq: 5,
        id: '5363064168543293440',
        columnDefault: null,
        columnDesc: '管理状态',
        columnKey: '',
        columnName: 'status',
        columnType: 'varchar(80)',
        nullable: 'NO',
        tableName: 'm_mould',
        columnWidth: 100,
        align: 'center',
        canDelete: false,
        isDatabaseField: true,
        isAutoWidth: false,
        isVisible: true,
        isLeftFixed: false,
        isRightFixed: false,
        isDataDefault: false,
        isHandAdd: false,
      },
      {
        seq: 6,
        id: '5062851217394386944',
        columnDefault: null,
        columnDesc: '所属部门',
        columnKey: '',
        columnName: 'owner_oid',
        columnType: 'bigint',
        nullable: 'YES',
        tableName: 'm_mould',
        columnWidth: 100,
        align: 'center',
        canDelete: false,
        isDatabaseField: true,
        isAutoWidth: false,
        isVisible: false,
        isLeftFixed: false,
        isRightFixed: false,
        isDataDefault: false,
        isHandAdd: false,
      },
      {
        seq: 7,
        id: '5398202737161988096',
        columnDefault: null,
        columnDesc: '所属部门',
        columnKey: null,
        columnName: 'org_name',
        columnType: 'varchar(80)',
        nullable: null,
        tableName: 'm_admin_org_20240729170442',
        columnWidth: 100,
        align: 'center',
        canDelete: false,
        isDatabaseField: false,
        isAutoWidth: false,
        isVisible: true,
        isLeftFixed: false,
        isRightFixed: false,
        isDataDefault: false,
        isHandAdd: true,
      },
      {
        seq: 8,
        id: '6100287561399015424',
        columnDefault: null,
        columnDesc: '一模多穴',
        columnKey: '',
        columnName: 'is_mul_mode',
        columnType: 'int',
        nullable: 'NO',
        tableName: 'm_mould',
        columnWidth: 100,
        align: 'center',
        canDelete: false,
        isDatabaseField: true,
        isAutoWidth: false,
        isVisible: true,
        isLeftFixed: false,
        isRightFixed: false,
        isDataDefault: false,
        isHandAdd: false,
      },
      {
        seq: 9,
        id: '8281116790299037696',
        columnDefault: null,
        columnDesc: '模具尺寸',
        columnKey: '',
        columnName: 'mould_size',
        columnType: 'varchar(240)',
        nullable: 'YES',
        tableName: 'm_mould',
        columnWidth: 100,
        align: 'center',
        canDelete: false,
        isDatabaseField: true,
        isAutoWidth: false,
        isVisible: true,
        isLeftFixed: false,
        isRightFixed: false,
        isDataDefault: false,
        isHandAdd: false,
      },
      {
        seq: 10,
        id: '6276986324658425856',
        columnDefault: null,
        columnDesc: '使用寿命',
        columnKey: '',
        columnName: 'life_time',
        columnType: 'int',
        nullable: 'NO',
        tableName: 'm_mould',
        columnWidth: 100,
        align: 'center',
        canDelete: false,
        isDatabaseField: true,
        isAutoWidth: false,
        isVisible: true,
        isLeftFixed: false,
        isRightFixed: false,
        isDataDefault: false,
        isHandAdd: false,
      },
      {
        seq: 11,
        id: '3530687092750663680',
        columnDefault: null,
        columnDesc: '型腔数',
        columnKey: '',
        columnName: 'cavity_number',
        columnType: 'int',
        nullable: 'NO',
        tableName: 'm_mould',
        columnWidth: 100,
        align: 'center',
        canDelete: false,
        isDatabaseField: true,
        isAutoWidth: false,
        isVisible: true,
        isLeftFixed: false,
        isRightFixed: false,
        isDataDefault: false,
        isHandAdd: false,
      },
      {
        seq: 12,
        id: '4594231664977162240',
        columnDefault: null,
        columnDesc: '图纸编号',
        columnKey: '',
        columnName: 'drawing_no',
        columnType: 'varchar(80)',
        nullable: 'YES',
        tableName: 'm_mould',
        columnWidth: 100,
        align: 'center',
        canDelete: false,
        isDatabaseField: true,
        isAutoWidth: false,
        isVisible: true,
        isLeftFixed: false,
        isRightFixed: false,
        isDataDefault: false,
        isHandAdd: false,
      },
      {
        seq: 13,
        id: '5439936873503248384',
        columnDefault: null,
        columnDesc: '存放仓库',
        columnKey: null,
        columnName: 'warehouse_name',
        columnType: 'varchar(240)',
        nullable: null,
        tableName: 'm_warehouse_20240729170617',
        columnWidth: 100,
        align: 'center',
        canDelete: false,
        isDatabaseField: false,
        isAutoWidth: false,
        isVisible: true,
        isLeftFixed: false,
        isRightFixed: false,
        isDataDefault: false,
        isHandAdd: true,
      },
      {
        seq: 14,
        id: '6924980156443009024',
        columnDefault: null,
        columnDesc: '模架',
        columnKey: null,
        columnName: 'district_name',
        columnType: 'varchar(240)',
        nullable: null,
        tableName: 'w_district_20240729170650',
        columnWidth: 100,
        align: 'center',
        canDelete: false,
        isDatabaseField: false,
        isAutoWidth: false,
        isVisible: true,
        isLeftFixed: false,
        isRightFixed: false,
        isDataDefault: false,
        isHandAdd: true,
      },
      {
        seq: 15,
        id: '1996315299009398784',
        columnDefault: null,
        columnDesc: '存放仓库',
        columnKey: '',
        columnName: 'm_warehouse_id',
        columnType: 'bigint',
        nullable: 'YES',
        tableName: 'm_mould',
        columnWidth: 100,
        align: 'center',
        canDelete: false,
        isDatabaseField: true,
        isAutoWidth: false,
        isVisible: false,
        isLeftFixed: false,
        isRightFixed: false,
        isDataDefault: false,
        isHandAdd: false,
      },
      {
        seq: 16,
        id: '5628098309117079552',
        columnDefault: null,
        columnDesc: '模架',
        columnKey: '',
        columnName: 'w_district_id',
        columnType: 'bigint',
        nullable: 'YES',
        tableName: 'm_mould',
        columnWidth: 100,
        align: 'center',
        canDelete: false,
        isDatabaseField: true,
        isAutoWidth: false,
        isVisible: false,
        isLeftFixed: false,
        isRightFixed: false,
        isDataDefault: false,
        isHandAdd: false,
      },
      {
        seq: 17,
        id: '3695271518609461248',
        columnDefault: null,
        columnDesc: '位置',
        columnKey: '',
        columnName: 'w_loc_id',
        columnType: 'bigint',
        nullable: 'YES',
        tableName: 'm_mould',
        columnWidth: 100,
        align: 'center',
        canDelete: false,
        isDatabaseField: true,
        isAutoWidth: false,
        isVisible: true,
        isLeftFixed: false,
        isRightFixed: false,
        isDataDefault: false,
        isHandAdd: false,
      },
      {
        seq: 18,
        id: '2721070477307887616',
        columnDefault: null,
        columnDesc: '供应商',
        columnKey: '',
        columnName: 'mould_supplier_id',
        columnType: 'bigint',
        nullable: 'YES',
        tableName: 'm_mould',
        columnWidth: 100,
        align: 'center',
        canDelete: false,
        isDatabaseField: true,
        isAutoWidth: false,
        isVisible: false,
        isLeftFixed: false,
        isRightFixed: false,
        isDataDefault: false,
        isHandAdd: false,
      },
      {
        seq: 19,
        id: '6120338013606422528',
        columnDefault: null,
        columnDesc: '供应商名称',
        columnKey: null,
        columnName: 'supplier_name',
        columnType: 'varchar(240)',
        nullable: null,
        tableName: 'm_supplier_20240729171214',
        columnWidth: 100,
        align: 'center',
        canDelete: false,
        isDatabaseField: false,
        isAutoWidth: false,
        isVisible: true,
        isLeftFixed: false,
        isRightFixed: false,
        isDataDefault: false,
        isHandAdd: true,
      },
      {
        seq: 20,
        id: '4493168118760359936',
        columnDefault: null,
        columnDesc: '成型周期',
        columnKey: '',
        columnName: 'molding_cycle',
        columnType: 'decimal(10,2)',
        nullable: 'YES',
        tableName: 'm_mould',
        columnWidth: 100,
        align: 'center',
        canDelete: false,
        isDatabaseField: true,
        isAutoWidth: false,
        isVisible: true,
        isLeftFixed: false,
        isRightFixed: false,
        isDataDefault: false,
        isHandAdd: false,
      },
      {
        seq: 21,
        id: '881590170010204160',
        columnDefault: null,
        columnDesc: '成型上偏差',
        columnKey: '',
        columnName: 'molding_cycle_max',
        columnType: 'decimal(10,2)',
        nullable: 'YES',
        tableName: 'm_mould',
        columnWidth: 100,
        align: 'center',
        canDelete: false,
        isDatabaseField: true,
        isAutoWidth: false,
        isVisible: true,
        isLeftFixed: false,
        isRightFixed: false,
        isDataDefault: false,
        isHandAdd: false,
      },
      {
        seq: 22,
        id: '1568185396752343040',
        columnDefault: null,
        columnDesc: '成型下偏差',
        columnKey: '',
        columnName: 'molding_cycle_min',
        columnType: 'decimal(10,2)',
        nullable: 'YES',
        tableName: 'm_mould',
        columnWidth: 100,
        align: 'center',
        canDelete: false,
        isDatabaseField: true,
        isAutoWidth: false,
        isVisible: true,
        isLeftFixed: false,
        isRightFixed: false,
        isDataDefault: false,
        isHandAdd: false,
      },
      {
        seq: 23,
        id: '2398335752604854272',
        columnDefault: null,
        columnDesc: '生效时间',
        columnKey: '',
        columnName: 'datetime_effect',
        columnType: 'datetime(4)',
        nullable: 'NO',
        tableName: 'm_mould',
        columnWidth: 130,
        align: 'center',
        canDelete: false,
        isDatabaseField: true,
        isAutoWidth: false,
        isVisible: true,
        isLeftFixed: false,
        isRightFixed: false,
        isDataDefault: false,
        isHandAdd: false,
      },
      {
        seq: 24,
        id: '3700276295988484096',
        columnDefault: null,
        columnDesc: '失效时间',
        columnKey: '',
        columnName: 'datetime_invalid',
        columnType: 'datetime(4)',
        nullable: 'YES',
        tableName: 'm_mould',
        columnWidth: 130,
        align: 'center',
        canDelete: false,
        isDatabaseField: true,
        isAutoWidth: false,
        isVisible: true,
        isLeftFixed: false,
        isRightFixed: false,
        isDataDefault: false,
        isHandAdd: false,
      },
      {
        seq: 25,
        id: '7247511504459790336',
        columnDefault: null,
        columnDesc: '保养验收组ID',
        columnKey: '',
        columnName: 'maintenance_accept_id',
        columnType: 'bigint',
        nullable: 'YES',
        tableName: 'm_mould',
        columnWidth: 100,
        align: 'center',
        canDelete: false,
        isDatabaseField: true,
        isAutoWidth: true,
        isVisible: false,
        isLeftFixed: false,
        isRightFixed: false,
        isDataDefault: false,
        isHandAdd: false,
      },
      {
        seq: 26,
        id: '860484300907347968',
        columnDefault: null,
        columnDesc: '保养处理组ID',
        columnKey: '',
        columnName: 'maintenance_deal_id',
        columnType: 'bigint',
        nullable: 'YES',
        tableName: 'm_mould',
        columnWidth: 100,
        align: 'center',
        canDelete: false,
        isDatabaseField: true,
        isAutoWidth: true,
        isVisible: false,
        isLeftFixed: false,
        isRightFixed: false,
        isDataDefault: false,
        isHandAdd: false,
      },
      {
        seq: 27,
        id: '648443324106840064',
        columnDefault: null,
        columnDesc: '存放地点',
        columnKey: '',
        columnName: 'position',
        columnType: 'varchar(2000)',
        nullable: 'YES',
        tableName: 'm_mould',
        columnWidth: 100,
        align: 'center',
        canDelete: false,
        isDatabaseField: true,
        isAutoWidth: true,
        isVisible: false,
        isLeftFixed: false,
        isRightFixed: false,
        isDataDefault: false,
        isHandAdd: false,
      },
      {
        seq: 28,
        id: '5825001759040468992',
        columnDefault: null,
        columnDesc: '维修验收组ID',
        columnKey: '',
        columnName: 'repair_accept_id',
        columnType: 'bigint',
        nullable: 'YES',
        tableName: 'm_mould',
        columnWidth: 100,
        align: 'center',
        canDelete: false,
        isDatabaseField: true,
        isAutoWidth: true,
        isVisible: false,
        isLeftFixed: false,
        isRightFixed: false,
        isDataDefault: false,
        isHandAdd: false,
      },
      {
        seq: 29,
        id: '7133268008107317248',
        columnDefault: null,
        columnDesc: '维修处理组ID',
        columnKey: '',
        columnName: 'repair_deal_id',
        columnType: 'bigint',
        nullable: 'YES',
        tableName: 'm_mould',
        columnWidth: 100,
        align: 'center',
        canDelete: false,
        isDatabaseField: true,
        isAutoWidth: true,
        isVisible: false,
        isLeftFixed: false,
        isRightFixed: false,
        isDataDefault: false,
        isHandAdd: false,
      },
      {
        seq: 30,
        id: '5307248031152431104',
        columnDefault: null,
        columnDesc: '源模具编码',
        columnKey: '',
        columnName: 'source_mould_code',
        columnType: 'varchar(80)',
        nullable: 'YES',
        tableName: 'm_mould',
        columnWidth: 100,
        align: 'center',
        canDelete: false,
        isDatabaseField: true,
        isAutoWidth: true,
        isVisible: false,
        isLeftFixed: false,
        isRightFixed: false,
        isDataDefault: false,
        isHandAdd: false,
      },
      {
        seq: 31,
        id: '5028892141798502400',
        columnDefault: null,
        columnDesc: '创建人',
        columnKey: '',
        columnName: 'creator',
        columnType: 'varchar(80)',
        nullable: 'NO',
        tableName: 'm_mould',
        columnWidth: 100,
        align: 'center',
        canDelete: false,
        isDatabaseField: true,
        isAutoWidth: true,
        isVisible: false,
        isLeftFixed: false,
        isRightFixed: false,
        isDataDefault: true,
        isHandAdd: false,
      },
      {
        seq: 32,
        id: '3150474983722315776',
        columnDefault: null,
        columnDesc: '企业ID',
        columnKey: 'MUL',
        columnName: 'eid',
        columnType: 'bigint',
        nullable: 'NO',
        tableName: 'm_mould',
        columnWidth: 100,
        align: 'center',
        canDelete: false,
        isDatabaseField: true,
        isAutoWidth: true,
        isVisible: false,
        isLeftFixed: false,
        isRightFixed: false,
        isDataDefault: true,
        isHandAdd: false,
      },
      {
        seq: 33,
        id: '7251497857913159680',
        columnDefault: null,
        columnDesc: '',
        columnKey: 'PRI',
        columnName: 'id',
        columnType: 'bigint',
        nullable: 'NO',
        tableName: 'm_mould',
        columnWidth: 100,
        align: 'center',
        canDelete: false,
        isDatabaseField: true,
        isAutoWidth: true,
        isVisible: false,
        isLeftFixed: false,
        isRightFixed: false,
        isDataDefault: true,
        isHandAdd: false,
      },
      {
        seq: 34,
        id: '8735484834941782016',
        columnDefault: null,
        columnDesc: '修改人',
        columnKey: '',
        columnName: 'modifier',
        columnType: 'varchar(80)',
        nullable: 'YES',
        tableName: 'm_mould',
        columnWidth: 100,
        align: 'center',
        canDelete: false,
        isDatabaseField: true,
        isAutoWidth: true,
        isVisible: false,
        isLeftFixed: false,
        isRightFixed: false,
        isDataDefault: true,
        isHandAdd: false,
      },
      {
        seq: 35,
        id: '3242165794038982656',
        columnDefault: null,
        columnDesc: '组织ID',
        columnKey: '',
        columnName: 'oid',
        columnType: 'bigint',
        nullable: 'NO',
        tableName: 'm_mould',
        columnWidth: 100,
        align: 'center',
        canDelete: false,
        isDatabaseField: true,
        isAutoWidth: true,
        isVisible: false,
        isLeftFixed: false,
        isRightFixed: false,
        isDataDefault: true,
        isHandAdd: false,
      },
      {
        seq: 36,
        id: '4243135370688477184',
        columnDefault: null,
        columnDesc: '1可用；0禁用',
        columnKey: '',
        columnName: 'state',
        columnType: 'int',
        nullable: 'NO',
        tableName: 'm_mould',
        columnWidth: 100,
        align: 'center',
        canDelete: false,
        isDatabaseField: true,
        isAutoWidth: true,
        isVisible: false,
        isLeftFixed: false,
        isRightFixed: false,
        isDataDefault: true,
        isHandAdd: false,
      },
      {
        seq: 37,
        id: '1708633160171360256',
        columnDefault: null,
        columnDesc: '创建时间',
        columnKey: '',
        columnName: 'time_create',
        columnType: 'datetime(4)',
        nullable: 'NO',
        tableName: 'm_mould',
        columnWidth: 100,
        align: 'center',
        canDelete: false,
        isDatabaseField: true,
        isAutoWidth: true,
        isVisible: false,
        isLeftFixed: false,
        isRightFixed: false,
        isDataDefault: true,
        isHandAdd: false,
      },
      {
        seq: 38,
        id: '1315258483207671808',
        columnDefault: null,
        columnDesc: '修改时间',
        columnKey: '',
        columnName: 'time_modified',
        columnType: 'datetime(4)',
        nullable: 'YES',
        tableName: 'm_mould',
        columnWidth: 100,
        align: 'center',
        canDelete: false,
        isDatabaseField: true,
        isAutoWidth: true,
        isVisible: false,
        isLeftFixed: false,
        isRightFixed: false,
        isDataDefault: true,
        isHandAdd: false,
      },
    ],
  },
} as DomainParamSetting;
