import { DomainParamSetting } from '@/api/main';

export default {
  creator: 'administrator',
  datasourceCategory: 'TABLE',
  datasourceName: 'm_mould_in_mitem',
  defaultPageCount: null,
  domainCategory: 'MAIN',
  domainParamCode: 'm_mould_in_mitem',
  domainParamDesc: null,
  domainParamGroupId: '1813403715610427394',
  domainParamName: '模具与物料关系表',
  domainParamTemplateId: '2',
  domainParmSetting: {
    buttonSetting: [
      {
        actionType: 'form-add',
        buttonCode: 'add',
        buttonName: '新增',
        buttonPosition: 'tableHeader',
        buttonTheme: 'primary',
        customButton: false,
        deleteType: 'logical',
        enabled: true,
        formColumnSetting: [
          {
            columnType: 'bigint',
            component: 'bcmp-select-business',
            componentParam: 'mould',
            componentSource: null,
            defaultValue: '',
            isDisabled: false,
            field: 'm_mould_id',
            fieldType: null,
            id: '8880003601681600512',

            isKeyField: true,
            isMultiple: false,
            isRequired: true,
            isVisible: true,

            label: '模具',

            placeholder: null,

            seq: 1,
            verifyExp: '',
          },
          {
            columnType: 'bigint',
            component: 'bcmp-select-business',
            componentParam: 'mitem',
            componentSource: null,
            defaultValue: '',
            isDisabled: false,
            field: 'm_mitem_id',
            fieldType: null,
            id: '5810841323136913408',

            isKeyField: true,
            isMultiple: false,
            isRequired: true,
            isVisible: true,

            label: '物料',

            placeholder: null,

            seq: 0,
            verifyExp: '',
          },
          {
            columnType: 'int',
            component: 't-input-number',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            isDisabled: false,
            field: 'use_cavity_number',
            fieldType: null,
            id: '4663789766149406720',

            isKeyField: false,
            isMultiple: false,
            isRequired: true,
            isVisible: true,

            label: '使用型腔数',

            placeholder: null,

            seq: 2,
            verifyExp: '',
          },
          {
            columnType: 'varchar(80)',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            isDisabled: false,
            field: 'creator',
            fieldType: null,
            id: '4284065120981458944',

            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: false,

            label: '创建人',

            placeholder: null,

            seq: 3,
            verifyExp: '',
          },
          {
            columnType: 'bigint',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            isDisabled: false,
            field: 'eid',
            fieldType: null,
            id: '6095329185865361408',

            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: false,

            label: '企业ID',

            placeholder: null,

            seq: 4,
            verifyExp: '',
          },
          {
            columnType: 'bigint',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            isDisabled: false,
            field: 'id',
            fieldType: null,
            id: '3928647073488867328',

            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: false,

            label: '',

            placeholder: null,

            seq: 5,
            verifyExp: '',
          },
          {
            columnType: 'varchar(80)',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            isDisabled: false,
            field: 'modifier',
            fieldType: null,
            id: '5229387004119519232',

            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: false,

            label: '修改人',

            placeholder: null,

            seq: 6,
            verifyExp: '',
          },
          {
            columnType: 'bigint',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            isDisabled: false,
            field: 'oid',
            fieldType: null,
            id: '7720795600085651456',

            isKeyField: true,
            isMultiple: false,
            isRequired: false,
            isVisible: false,

            label: '组织ID',

            placeholder: null,

            seq: 7,
            verifyExp: '',
          },
          {
            columnType: 'int',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            isDisabled: false,
            field: 'state',
            fieldType: null,
            id: '4497805457590392832',

            isKeyField: true,
            isMultiple: false,
            isRequired: false,
            isVisible: false,

            label: '1可用；0禁用',

            placeholder: null,

            seq: 8,
            verifyExp: '',
          },
          {
            columnType: 'datetime(4)',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            isDisabled: false,
            field: 'time_create',
            fieldType: null,
            id: '3164691321260062720',

            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: false,

            label: '创建时间',

            placeholder: null,

            seq: 9,
            verifyExp: '',
          },
          {
            columnType: 'datetime(4)',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            isDisabled: false,
            field: 'time_modified',
            fieldType: null,
            id: '7051859561795536896',

            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: false,

            label: '修改时间',

            placeholder: null,

            seq: 10,
            verifyExp: '',
          },
        ],
        id: null,
        isCustomButton: false,
        isEnabled: true,
        needCheckSelectRow: false,
        seq: 1,
      },
      {
        actionType: 'form-edit',
        buttonCode: 'edit',
        buttonName: '编辑',
        buttonPosition: 'row',
        buttonTheme: 'primary',
        customButton: false,
        deleteType: '',
        enabled: true,
        formColumnSetting: [
          {
            columnType: 'bigint',
            component: 'bcmp-select-business',
            componentParam: 'mould',
            componentSource: null,
            defaultValue: '',
            isDisabled: true,
            field: 'm_mould_id',
            fieldType: null,
            id: '8880003601681600512',

            isKeyField: true,
            isMultiple: false,
            isRequired: false,
            isVisible: true,

            label: '模具',

            placeholder: null,

            seq: 1,
            verifyExp: '',
          },
          {
            columnType: 'bigint',
            component: 'bcmp-select-business',
            componentParam: 'mitem',
            componentSource: null,
            defaultValue: '',
            isDisabled: true,
            field: 'm_mitem_id',
            fieldType: null,
            id: '5810841323136913408',

            isKeyField: true,
            isMultiple: false,
            isRequired: false,
            isVisible: true,

            label: '物料',

            placeholder: null,

            seq: 0,
            verifyExp: '',
          },
          {
            columnType: 'int',
            component: 't-input-number',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            isDisabled: false,
            field: 'use_cavity_number',
            fieldType: null,
            id: '4663789766149406720',
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: true,
            label: '使用型腔数',
            placeholder: null,
            seq: 2,
            verifyExp: '',
          },
          {
            columnType: 'varchar(80)',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            isDisabled: false,
            field: 'creator',
            fieldType: null,
            id: '4284065120981458944',
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: false,
            label: '创建人',
            placeholder: null,
            seq: 3,
            verifyExp: '',
          },
          {
            columnType: 'bigint',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            isDisabled: false,
            field: 'eid',
            fieldType: null,
            id: '6095329185865361408',
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: false,
            label: '企业ID',
            placeholder: null,
            seq: 4,
            verifyExp: '',
          },
          {
            columnType: 'bigint',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            isDisabled: false,
            field: 'id',
            fieldType: null,
            id: '3928647073488867328',
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: false,
            label: '',
            placeholder: null,
            seq: 5,
            verifyExp: '',
          },
          {
            columnType: 'varchar(80)',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            isDisabled: false,
            field: 'modifier',
            fieldType: null,
            id: '5229387004119519232',
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: false,
            label: '修改人',
            placeholder: null,
            seq: 6,
            verifyExp: '',
          },
          {
            columnType: 'bigint',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            isDisabled: false,
            field: 'oid',
            fieldType: null,
            id: '7720795600085651456',
            isKeyField: true,
            isMultiple: false,
            isRequired: false,
            isVisible: false,
            label: '组织ID',
            placeholder: null,
            seq: 7,
            verifyExp: '',
          },
          {
            columnType: 'int',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            isDisabled: false,
            field: 'state',
            fieldType: null,
            id: '4497805457590392832',

            isKeyField: true,
            isMultiple: false,
            isRequired: false,
            isVisible: false,

            label: '1可用；0禁用',

            placeholder: null,

            seq: 8,
            verifyExp: '',
          },
          {
            columnType: 'datetime(4)',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            isDisabled: false,
            field: 'time_create',
            fieldType: null,
            id: '3164691321260062720',
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: false,
            label: '创建时间',
            placeholder: null,
            seq: 9,
            verifyExp: '',
          },
          {
            columnType: 'datetime(4)',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            isDisabled: false,
            field: 'time_modified',
            fieldType: null,
            id: '7051859561795536896',
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: false,
            label: '修改时间',
            placeholder: null,
            seq: 10,
            verifyExp: '',
          },
        ],
        id: null,
        isCustomButton: false,
        isEnabled: true,
        needCheckSelectRow: false,
        seq: 2,
      },
      {
        actionType: 'delete',
        buttonCode: 'delete',
        buttonName: '删除',
        buttonPosition: 'row',
        buttonTheme: 'danger',
        customButton: false,
        deleteType: 'logical',
        enabled: true,
        formColumnSetting: [],
        id: null,
        isCustomButton: false,
        isEnabled: true,
        needCheckSelectRow: true,
        seq: 3,
      },
    ],
    datasourceSetting: [
      {
        aliasName: 'm_mitem_20240718211633',
        conditionData: [
          {
            aliasName: 'm_mould_in_mitem',
            fieldName: 'id',
            operator: 'EQ',
            relateFieldName: 'm_mitem_id',
            relateType: 'field',
            relateValue: '',
            seq: 0,
          },
        ],
        datasourceName: 'm_mitem',
        datasourceType: 'dataTable',
        relatedType: 'LEFT',
        seq: 1,
      },
      {
        aliasName: 'm_mould_20240718211651',
        conditionData: [
          {
            aliasName: 'm_mould_in_mitem',
            fieldName: 'id',
            operator: 'EQ',
            relateFieldName: 'm_mould_id',
            relateType: 'field',
            relateValue: '',
            seq: 0,
          },
        ],
        datasourceName: 'm_mould',
        datasourceType: 'dataTable',
        relatedType: 'LEFT',
        seq: 2,
      },
    ],
    searchSetting: [
      {
        component: 'bcmp-select-business',
        componentParam: 'mitem',
        componentSource: null,
        defaultValue: '',
        field: 'm_mitem_id',
        fieldType: null,
        id: null,
        isMultiple: false,
        isVisible: true,
        label: '物料代码',
        operator: 'EQ',
        seq: 1,
      },
    ],
    tableSetting: {
      columnSetting: [
        {
          align: 'center',

          canDelete: false,
          columnDefault: null,
          columnDesc: '图纸编号',
          columnKey: null,
          columnName: 'drawing_no',
          columnType: 'varchar(80)',
          columnWidth: 100,

          id: '4652981094784356352',
          isAutoWidth: true,
          isDataDefault: false,
          isDatabaseField: false,
          isHandAdd: true,
          isLeftFixed: false,
          isRightFixed: false,
          isVisible: true,

          nullable: null,

          seq: 1,
          tableName: 'm_mould_20240718211651',
        },
        {
          align: 'center',

          canDelete: false,
          columnDefault: null,
          columnDesc: '物料代码',
          columnKey: null,
          columnName: 'mitem_code',
          columnType: 'varchar(80)',
          columnWidth: 100,

          id: '7363133749208338432',
          isAutoWidth: true,
          isDataDefault: false,
          isDatabaseField: false,
          isHandAdd: true,
          isLeftFixed: false,
          isRightFixed: false,
          isVisible: true,

          nullable: null,

          seq: 2,
          tableName: 'm_mitem_20240718211633',
        },
        {
          align: 'center',

          canDelete: false,
          columnDefault: null,
          columnDesc: '物料名称',
          columnKey: null,
          columnName: 'mitem_name',
          columnType: 'varchar(240)',
          columnWidth: 100,

          id: '4374212621220308992',
          isAutoWidth: true,
          isDataDefault: false,
          isDatabaseField: false,
          isHandAdd: true,
          isLeftFixed: false,
          isRightFixed: false,
          isVisible: true,

          nullable: null,

          seq: 3,
          tableName: 'm_mitem_20240718211633',
        },
        {
          align: 'center',

          canDelete: false,
          columnDefault: null,
          columnDesc: '物料描述',
          columnKey: null,
          columnName: 'mitem_desc',
          columnType: 'varchar(2000)',
          columnWidth: 100,

          id: '1809449273702719488',
          isAutoWidth: true,
          isDataDefault: false,
          isDatabaseField: false,
          isHandAdd: true,
          isLeftFixed: false,
          isRightFixed: false,
          isVisible: true,

          nullable: null,

          seq: 4,
          tableName: 'm_mitem_20240718211633',
        },
        {
          align: 'center',

          canDelete: false,
          columnDefault: null,
          columnDesc: '使用型腔数',
          columnKey: '',
          columnName: 'use_cavity_number',
          columnType: 'int',
          columnWidth: 100,

          id: '4663789766149406720',
          isAutoWidth: true,
          isDataDefault: false,
          isDatabaseField: true,
          isHandAdd: false,
          isLeftFixed: false,
          isRightFixed: false,
          isVisible: true,

          nullable: 'NO',

          seq: 5,
          tableName: 'm_mould_in_mitem',
        },
        {
          align: 'center',

          canDelete: false,
          columnDefault: null,
          columnDesc: '模具代码',
          columnKey: null,
          columnName: 'mould_code',
          columnType: 'varchar(80)',
          columnWidth: 100,

          id: '4011640066667585536',
          isAutoWidth: true,
          isDataDefault: false,
          isDatabaseField: false,
          isHandAdd: true,
          isLeftFixed: false,
          isRightFixed: false,
          isVisible: false,

          nullable: null,

          seq: 6,
          tableName: 'm_mould_20240718211651',
        },
        {
          align: 'center',

          canDelete: false,
          columnDefault: null,
          columnDesc: '物料ID',
          columnKey: '',
          columnName: 'm_mitem_id',
          columnType: 'bigint',
          columnWidth: 100,

          id: '5810841323136913408',
          isAutoWidth: true,
          isDataDefault: false,
          isDatabaseField: true,
          isHandAdd: false,
          isLeftFixed: false,
          isRightFixed: false,
          isVisible: false,

          nullable: 'NO',

          seq: 7,
          tableName: 'm_mould_in_mitem',
        },
        {
          align: 'center',

          canDelete: false,
          columnDefault: null,
          columnDesc: '模具ID',
          columnKey: '',
          columnName: 'm_mould_id',
          columnType: 'bigint',
          columnWidth: 100,

          id: '8880003601681600512',
          isAutoWidth: true,
          isDataDefault: false,
          isDatabaseField: true,
          isHandAdd: false,
          isLeftFixed: false,
          isRightFixed: false,
          isVisible: false,

          nullable: 'NO',

          seq: 8,
          tableName: 'm_mould_in_mitem',
        },
        {
          align: 'center',

          canDelete: false,
          columnDefault: null,
          columnDesc: '创建人',
          columnKey: '',
          columnName: 'creator',
          columnType: 'varchar(80)',
          columnWidth: 100,

          id: '4284065120981458944',
          isAutoWidth: true,
          isDataDefault: true,
          isDatabaseField: true,
          isHandAdd: false,
          isLeftFixed: false,
          isRightFixed: false,
          isVisible: false,

          nullable: 'NO',

          seq: 9,
          tableName: 'm_mould_in_mitem',
        },
        {
          align: 'center',

          canDelete: false,
          columnDefault: null,
          columnDesc: '企业ID',
          columnKey: 'MUL',
          columnName: 'eid',
          columnType: 'bigint',
          columnWidth: 100,

          id: '6095329185865361408',
          isAutoWidth: true,
          isDataDefault: true,
          isDatabaseField: true,
          isHandAdd: false,
          isLeftFixed: false,
          isRightFixed: false,
          isVisible: false,

          nullable: 'NO',

          seq: 10,
          tableName: 'm_mould_in_mitem',
        },
        {
          align: 'center',

          canDelete: false,
          columnDefault: null,
          columnDesc: '',
          columnKey: 'PRI',
          columnName: 'id',
          columnType: 'bigint',
          columnWidth: 100,

          id: '3928647073488867328',
          isAutoWidth: true,
          isDataDefault: true,
          isDatabaseField: true,
          isHandAdd: false,
          isLeftFixed: false,
          isRightFixed: false,
          isVisible: false,

          nullable: 'NO',

          seq: 11,
          tableName: 'm_mould_in_mitem',
        },
        {
          align: 'center',

          canDelete: false,
          columnDefault: null,
          columnDesc: '修改人',
          columnKey: '',
          columnName: 'modifier',
          columnType: 'varchar(80)',
          columnWidth: 100,

          id: '5229387004119519232',
          isAutoWidth: true,
          isDataDefault: true,
          isDatabaseField: true,
          isHandAdd: false,
          isLeftFixed: false,
          isRightFixed: false,
          isVisible: false,

          nullable: 'YES',

          seq: 12,
          tableName: 'm_mould_in_mitem',
        },
        {
          align: 'center',

          canDelete: false,
          columnDefault: null,
          columnDesc: '组织ID',
          columnKey: '',
          columnName: 'oid',
          columnType: 'bigint',
          columnWidth: 100,

          id: '7720795600085651456',
          isAutoWidth: true,
          isDataDefault: true,
          isDatabaseField: true,
          isHandAdd: false,
          isLeftFixed: false,
          isRightFixed: false,
          isVisible: false,

          nullable: 'NO',

          seq: 13,
          tableName: 'm_mould_in_mitem',
        },
        {
          align: 'center',

          canDelete: false,
          columnDefault: null,
          columnDesc: '1可用；0禁用',
          columnKey: '',
          columnName: 'state',
          columnType: 'int',
          columnWidth: 100,

          id: '4497805457590392832',
          isAutoWidth: true,
          isDataDefault: true,
          isDatabaseField: true,
          isHandAdd: false,
          isLeftFixed: false,
          isRightFixed: false,
          isVisible: false,

          nullable: 'NO',

          seq: 14,
          tableName: 'm_mould_in_mitem',
        },
        {
          align: 'center',

          canDelete: false,
          columnDefault: null,
          columnDesc: '创建时间',
          columnKey: '',
          columnName: 'time_create',
          columnType: 'datetime(4)',
          columnWidth: 100,

          id: '3164691321260062720',
          isAutoWidth: true,
          isDataDefault: true,
          isDatabaseField: true,
          isHandAdd: false,
          isLeftFixed: false,
          isRightFixed: false,
          isVisible: false,

          nullable: 'NO',

          seq: 15,
          tableName: 'm_mould_in_mitem',
        },
        {
          align: 'center',

          canDelete: false,
          columnDefault: null,
          columnDesc: '修改时间',
          columnKey: '',
          columnName: 'time_modified',
          columnType: 'datetime(4)',
          columnWidth: 100,

          id: '7051859561795536896',
          isAutoWidth: true,
          isDataDefault: true,
          isDatabaseField: true,
          isHandAdd: false,
          isLeftFixed: false,
          isRightFixed: false,
          isVisible: false,

          nullable: 'YES',

          seq: 16,
          tableName: 'm_mould_in_mitem',
        },
      ],
      pageSize: null,
      sortField: 'time_create',
      sortType: 'desc',
      tableTitle: '模具与物料关系表',
      usePage: true,
    },
  },
  eid: '1',
  exportFileName: null,
  exportLimitCount: null,
  groupCode: 'MOULD',
  groupName: '模具',
  id: '1813926287884165121',
  importFileName: null,
  isCustomerSql: null,
  isDebug: null,
  jsonContent:
    '{"datasourceSetting":[{"seq":1,"datasourceType":"dataTable","datasourceName":"m_mitem","aliasName":"m_mitem_20240718211633","relatedType":"LEFT","conditionData":[{"seq":0,"fieldName":"id","operator":"EQ","relateType":"field","aliasName":"m_mould_in_mitem","relateFieldName":"m_mitem_id","relateValue":""}]},{"seq":2,"datasourceType":"dataTable","datasourceName":"m_mould","aliasName":"m_mould_20240718211651","relatedType":"LEFT","conditionData":[{"seq":0,"fieldName":"id","operator":"EQ","relateType":"field","aliasName":"m_mould_in_mitem","relateFieldName":"m_mould_id","relateValue":""}]}],"tableSetting":{"tableTitle":"模具与物料关系表","usePage":true,"pageSize":null,"sortField":"time_create","sortType":"desc","columnSetting":[{"seq":1,"id":"4652981094784356352","columnDefault":null,"columnDesc":"图纸编号","columnKey":null,"columnName":"drawing_no","columnType":"varchar(80)","nullable":null,"tableName":"m_mould_20240718211651","columnWidth":100,"align":"center","canDelete":false,"isDatabaseField":false,"isAutoWidth":true,"isVisible":true,"isLeftFixed":false,"isRightFixed":false,"isDataDefault":false,"isHandAdd":true},{"seq":2,"id":"7363133749208338432","columnDefault":null,"columnDesc":"物料代码","columnKey":null,"columnName":"mitem_code","columnType":"varchar(80)","nullable":null,"tableName":"m_mitem_20240718211633","columnWidth":100,"align":"center","canDelete":false,"isDatabaseField":false,"isAutoWidth":true,"isVisible":true,"isLeftFixed":false,"isRightFixed":false,"isDataDefault":false,"isHandAdd":true},{"seq":3,"id":"4374212621220308992","columnDefault":null,"columnDesc":"物料名称","columnKey":null,"columnName":"mitem_name","columnType":"varchar(240)","nullable":null,"tableName":"m_mitem_20240718211633","columnWidth":100,"align":"center","canDelete":false,"isDatabaseField":false,"isAutoWidth":true,"isVisible":true,"isLeftFixed":false,"isRightFixed":false,"isDataDefault":false,"isHandAdd":true},{"seq":4,"id":"1809449273702719488","columnDefault":null,"columnDesc":"物料描述","columnKey":null,"columnName":"mitem_desc","columnType":"varchar(2000)","nullable":null,"tableName":"m_mitem_20240718211633","columnWidth":100,"align":"center","canDelete":false,"isDatabaseField":false,"isAutoWidth":true,"isVisible":true,"isLeftFixed":false,"isRightFixed":false,"isDataDefault":false,"isHandAdd":true},{"seq":5,"id":"4663789766149406720","columnDefault":null,"columnDesc":"使用型腔数","columnKey":"","columnName":"use_cavity_number","columnType":"int","nullable":"NO","tableName":"m_mould_in_mitem","columnWidth":100,"align":"center","canDelete":false,"isDatabaseField":true,"isAutoWidth":true,"isVisible":true,"isLeftFixed":false,"isRightFixed":false,"isDataDefault":false,"isHandAdd":false},{"seq":6,"id":"4011640066667585536","columnDefault":null,"columnDesc":"模具代码","columnKey":null,"columnName":"mould_code","columnType":"varchar(80)","nullable":null,"tableName":"m_mould_20240718211651","columnWidth":100,"align":"center","canDelete":false,"isDatabaseField":false,"isAutoWidth":true,"isVisible":false,"isLeftFixed":false,"isRightFixed":false,"isDataDefault":false,"isHandAdd":true},{"seq":7,"id":"5810841323136913408","columnDefault":null,"columnDesc":"物料ID","columnKey":"","columnName":"m_mitem_id","columnType":"bigint","nullable":"NO","tableName":"m_mould_in_mitem","columnWidth":100,"align":"center","canDelete":false,"isDatabaseField":true,"isAutoWidth":true,"isVisible":false,"isLeftFixed":false,"isRightFixed":false,"isDataDefault":false,"isHandAdd":false},{"seq":8,"id":"8880003601681600512","columnDefault":null,"columnDesc":"模具ID","columnKey":"","columnName":"m_mould_id","columnType":"bigint","nullable":"NO","tableName":"m_mould_in_mitem","columnWidth":100,"align":"center","canDelete":false,"isDatabaseField":true,"isAutoWidth":true,"isVisible":false,"isLeftFixed":false,"isRightFixed":false,"isDataDefault":false,"isHandAdd":false},{"seq":9,"id":"4284065120981458944","columnDefault":null,"columnDesc":"创建人","columnKey":"","columnName":"creator","columnType":"varchar(80)","nullable":"NO","tableName":"m_mould_in_mitem","columnWidth":100,"align":"center","canDelete":false,"isDatabaseField":true,"isAutoWidth":true,"isVisible":false,"isLeftFixed":false,"isRightFixed":false,"isDataDefault":true,"isHandAdd":false},{"seq":10,"id":"6095329185865361408","columnDefault":null,"columnDesc":"企业ID","columnKey":"MUL","columnName":"eid","columnType":"bigint","nullable":"NO","tableName":"m_mould_in_mitem","columnWidth":100,"align":"center","canDelete":false,"isDatabaseField":true,"isAutoWidth":true,"isVisible":false,"isLeftFixed":false,"isRightFixed":false,"isDataDefault":true,"isHandAdd":false},{"seq":11,"id":"3928647073488867328","columnDefault":null,"columnDesc":"","columnKey":"PRI","columnName":"id","columnType":"bigint","nullable":"NO","tableName":"m_mould_in_mitem","columnWidth":100,"align":"center","canDelete":false,"isDatabaseField":true,"isAutoWidth":true,"isVisible":false,"isLeftFixed":false,"isRightFixed":false,"isDataDefault":true,"isHandAdd":false},{"seq":12,"id":"5229387004119519232","columnDefault":null,"columnDesc":"修改人","columnKey":"","columnName":"modifier","columnType":"varchar(80)","nullable":"YES","tableName":"m_mould_in_mitem","columnWidth":100,"align":"center","canDelete":false,"isDatabaseField":true,"isAutoWidth":true,"isVisible":false,"isLeftFixed":false,"isRightFixed":false,"isDataDefault":true,"isHandAdd":false},{"seq":13,"id":"7720795600085651456","columnDefault":null,"columnDesc":"组织ID","columnKey":"","columnName":"oid","columnType":"bigint","nullable":"NO","tableName":"m_mould_in_mitem","columnWidth":100,"align":"center","canDelete":false,"isDatabaseField":true,"isAutoWidth":true,"isVisible":false,"isLeftFixed":false,"isRightFixed":false,"isDataDefault":true,"isHandAdd":false},{"seq":14,"id":"4497805457590392832","columnDefault":null,"columnDesc":"1可用；0禁用","columnKey":"","columnName":"state","columnType":"int","nullable":"NO","tableName":"m_mould_in_mitem","columnWidth":100,"align":"center","canDelete":false,"isDatabaseField":true,"isAutoWidth":true,"isVisible":false,"isLeftFixed":false,"isRightFixed":false,"isDataDefault":true,"isHandAdd":false},{"seq":15,"id":"3164691321260062720","columnDefault":null,"columnDesc":"创建时间","columnKey":"","columnName":"time_create","columnType":"datetime(4)","nullable":"NO","tableName":"m_mould_in_mitem","columnWidth":100,"align":"center","canDelete":false,"isDatabaseField":true,"isAutoWidth":true,"isVisible":false,"isLeftFixed":false,"isRightFixed":false,"isDataDefault":true,"isHandAdd":false},{"seq":16,"id":"7051859561795536896","columnDefault":null,"columnDesc":"修改时间","columnKey":"","columnName":"time_modified","columnType":"datetime(4)","nullable":"YES","tableName":"m_mould_in_mitem","columnWidth":100,"align":"center","canDelete":false,"isDatabaseField":true,"isAutoWidth":true,"isVisible":false,"isLeftFixed":false,"isRightFixed":false,"isDataDefault":true,"isHandAdd":false}]},"searchSetting":[{"seq":1,"id":null,"field":"m_mitem_id","label":"物料代码","component":"bcmp-select-business","componentParam":"mitem","operator":"EQ","defaultValue":"","fieldType":null,"componentSource":null,"isVisible":true,"isMultiple":false}],"buttonSetting":[{"seq":1,"id":null,"buttonCode":"add","buttonName":"新增","buttonPosition":"tableHeader","buttonTheme":"primary","needCheckSelectRow":false,"actionType":"form-add","formColumnSetting":[{"seq":0,"id":"5810841323136913408","field":"m_mitem_id","label":"物料","component":"bcmp-select-business","componentParam":"mitem","placeholder":null,"defaultValue":"","fieldType":null,"columnType":"bigint","verifyExp":"","componentSource":null,"isVisible":true,"isDisabled":false,"isMultiple":false,"isRequired":false,"isKeyField":true},{"seq":1,"id":"8880003601681600512","field":"m_mould_id","label":"模具","component":"bcmp-select-business","componentParam":"mould","placeholder":null,"defaultValue":"","fieldType":null,"columnType":"bigint","verifyExp":"","componentSource":null,"isVisible":true,"isDisabled":false,"isMultiple":false,"isRequired":false,"isKeyField":true},{"seq":2,"id":"4663789766149406720","field":"use_cavity_number","label":"使用型腔数","component":"t-input-number","componentParam":"","placeholder":null,"defaultValue":"","fieldType":null,"columnType":"int","verifyExp":"","componentSource":null,"isVisible":true,"isDisabled":false,"isMultiple":false,"isRequired":false,"isKeyField":false},{"seq":3,"id":"4284065120981458944","field":"creator","label":"创建人","component":"t-input","componentParam":"","placeholder":null,"defaultValue":"","fieldType":null,"columnType":"varchar(80)","verifyExp":"","componentSource":null,"isVisible":false,"isDisabled":false,"isMultiple":false,"isRequired":false,"isKeyField":false},{"seq":4,"id":"6095329185865361408","field":"eid","label":"企业ID","component":"t-input","componentParam":"","placeholder":null,"defaultValue":"","fieldType":null,"columnType":"bigint","verifyExp":"","componentSource":null,"isVisible":false,"isDisabled":false,"isMultiple":false,"isRequired":false,"isKeyField":false},{"seq":5,"id":"3928647073488867328","field":"id","label":"","component":"t-input","componentParam":"","placeholder":null,"defaultValue":"","fieldType":null,"columnType":"bigint","verifyExp":"","componentSource":null,"isVisible":false,"isDisabled":false,"isMultiple":false,"isRequired":false,"isKeyField":false},{"seq":6,"id":"5229387004119519232","field":"modifier","label":"修改人","component":"t-input","componentParam":"","placeholder":null,"defaultValue":"","fieldType":null,"columnType":"varchar(80)","verifyExp":"","componentSource":null,"isVisible":false,"isDisabled":false,"isMultiple":false,"isRequired":false,"isKeyField":false},{"seq":7,"id":"7720795600085651456","field":"oid","label":"组织ID","component":"t-input","componentParam":"","placeholder":null,"defaultValue":"","fieldType":null,"columnType":"bigint","verifyExp":"","componentSource":null,"isVisible":false,"isDisabled":false,"isMultiple":false,"isRequired":false,"isKeyField":true},{"seq":8,"id":"4497805457590392832","field":"state","label":"1可用；0禁用","component":"t-input","componentParam":"","placeholder":null,"defaultValue":"","fieldType":null,"columnType":"int","verifyExp":"","componentSource":null,"isVisible":false,"isDisabled":false,"isMultiple":false,"isRequired":false,"isKeyField":true},{"seq":9,"id":"3164691321260062720","field":"time_create","label":"创建时间","component":"t-input","componentParam":"","placeholder":null,"defaultValue":"","fieldType":null,"columnType":"datetime(4)","verifyExp":"","componentSource":null,"isVisible":false,"isDisabled":false,"isMultiple":false,"isRequired":false,"isKeyField":false},{"seq":10,"id":"7051859561795536896","field":"time_modified","label":"修改时间","component":"t-input","componentParam":"","placeholder":null,"defaultValue":"","fieldType":null,"columnType":"datetime(4)","verifyExp":"","componentSource":null,"isVisible":false,"isDisabled":false,"isMultiple":false,"isRequired":false,"isKeyField":false}],"deleteType":"logical","isEnabled":true,"isCustomButton":false},{"seq":2,"id":null,"buttonCode":"edit","buttonName":"编辑","buttonPosition":"row","buttonTheme":"primary","needCheckSelectRow":false,"actionType":"form-edit","formColumnSetting":[{"seq":0,"id":"5810841323136913408","field":"m_mitem_id","label":"物料","component":"bcmp-select-business","componentParam":"mitem","placeholder":null,"defaultValue":"","fieldType":null,"columnType":"bigint","verifyExp":"","componentSource":null,"isVisible":true,"isDisabled":false,"isMultiple":false,"isRequired":false,"isKeyField":true},{"seq":1,"id":"8880003601681600512","field":"m_mould_id","label":"模具","component":"bcmp-select-business","componentParam":"mould","placeholder":null,"defaultValue":"","fieldType":null,"columnType":"bigint","verifyExp":"","componentSource":null,"isVisible":true,"isDisabled":false,"isMultiple":false,"isRequired":false,"isKeyField":true},{"seq":2,"id":"4663789766149406720","field":"use_cavity_number","label":"使用型腔数","component":"t-input-number","componentParam":"","placeholder":null,"defaultValue":"","fieldType":null,"columnType":"int","verifyExp":"","componentSource":null,"isVisible":true,"isDisabled":false,"isMultiple":false,"isRequired":false,"isKeyField":false},{"seq":3,"id":"4284065120981458944","field":"creator","label":"创建人","component":"t-input","componentParam":"","placeholder":null,"defaultValue":"","fieldType":null,"columnType":"varchar(80)","verifyExp":"","componentSource":null,"isVisible":false,"isDisabled":false,"isMultiple":false,"isRequired":false,"isKeyField":false},{"seq":4,"id":"6095329185865361408","field":"eid","label":"企业ID","component":"t-input","componentParam":"","placeholder":null,"defaultValue":"","fieldType":null,"columnType":"bigint","verifyExp":"","componentSource":null,"isVisible":false,"isDisabled":false,"isMultiple":false,"isRequired":false,"isKeyField":false},{"seq":5,"id":"3928647073488867328","field":"id","label":"","component":"t-input","componentParam":"","placeholder":null,"defaultValue":"","fieldType":null,"columnType":"bigint","verifyExp":"","componentSource":null,"isVisible":false,"isDisabled":false,"isMultiple":false,"isRequired":false,"isKeyField":false},{"seq":6,"id":"5229387004119519232","field":"modifier","label":"修改人","component":"t-input","componentParam":"","placeholder":null,"defaultValue":"","fieldType":null,"columnType":"varchar(80)","verifyExp":"","componentSource":null,"isVisible":false,"isDisabled":false,"isMultiple":false,"isRequired":false,"isKeyField":false},{"seq":7,"id":"7720795600085651456","field":"oid","label":"组织ID","component":"t-input","componentParam":"","placeholder":null,"defaultValue":"","fieldType":null,"columnType":"bigint","verifyExp":"","componentSource":null,"isVisible":false,"isDisabled":false,"isMultiple":false,"isRequired":false,"isKeyField":true},{"seq":8,"id":"4497805457590392832","field":"state","label":"1可用；0禁用","component":"t-input","componentParam":"","placeholder":null,"defaultValue":"","fieldType":null,"columnType":"int","verifyExp":"","componentSource":null,"isVisible":false,"isDisabled":false,"isMultiple":false,"isRequired":false,"isKeyField":true},{"seq":9,"id":"3164691321260062720","field":"time_create","label":"创建时间","component":"t-input","componentParam":"","placeholder":null,"defaultValue":"","fieldType":null,"columnType":"datetime(4)","verifyExp":"","componentSource":null,"isVisible":false,"isDisabled":false,"isMultiple":false,"isRequired":false,"isKeyField":false},{"seq":10,"id":"7051859561795536896","field":"time_modified","label":"修改时间","component":"t-input","componentParam":"","placeholder":null,"defaultValue":"","fieldType":null,"columnType":"datetime(4)","verifyExp":"","componentSource":null,"isVisible":false,"isDisabled":false,"isMultiple":false,"isRequired":false,"isKeyField":false}],"deleteType":"","isEnabled":true,"isCustomButton":false},{"seq":3,"id":null,"buttonCode":"delete","buttonName":"删除","buttonPosition":"row","buttonTheme":"danger","needCheckSelectRow":true,"actionType":"delete","formColumnSetting":[],"deleteType":"logical","isEnabled":true,"isCustomButton":false}]}',
  modifier: 'administrator',
  operateColumnWidth: null,
  queryApi: null,
  seqColumnWidth: null,
  sqlContent: '',
  state: 1,
  templateCode: 'singleTableManage',
  templateName: '数据维护模板',
  templateUrl: '/main#/singleTableManage',
  timeCreate: '2024-07-18 21:18:22',
  timeModified: '2024-07-30 16:31:39',
  validateApi: null,
} as DomainParamSetting;
