import { DomainParamVO } from '@/api/main';

export default {
  creator: 'administrator',
  datasourceCategory: 'TABLE',
  datasourceName: 'e_maintenance_bill_dtl',
  defaultPageCount: null,
  domainCategory: 'EQUIPMENT',
  domainParamCode: 'e_maintenance_bill_item_mould',
  domainParamDesc: null,
  domainParamGroupId: '1813403715610427394',
  domainParamName: '模具保养单据项目',
  domainParamTemplateId: '2',
  domainParmSetting: {
    buttonSetting: [
      {
        actionType: 'form-add',
        apiAction: null,
        buttonCode: 'add',
        buttonName: '新增',
        buttonPosition: 'tableHeader',
        buttonTheme: 'primary',
        customApi: null,
        deleteType: 'logical',
        formColumnSetting: [
          {
            columnType: 'varchar(80)',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            field: 'bill_no',
            fieldType: null,
            id: '1358777087314993152',
            isDisabled: false,
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: true,
            label: '单据号',
            parentField: null,
            placeholder: null,
            seq: 0,
            verifyExp: '',
          },
          {
            columnType: 'bigint',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            field: 'e_maintenance_bill_head_id',
            fieldType: null,
            id: '583542975499554816',
            isDisabled: false,
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: true,
            label: '设备保养单据头ID',
            parentField: null,
            placeholder: null,
            seq: 1,
            verifyExp: '',
          },
          {
            columnType: 'varchar(80)',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            field: 'maintenance_item_code',
            fieldType: null,
            id: '1384302817068023808',
            isDisabled: false,
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: true,
            label: '保养项目编码',
            parentField: null,
            placeholder: null,
            seq: 2,
            verifyExp: '',
          },
          {
            columnType: 'int',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            field: 'is_photo',
            fieldType: null,
            id: '7775309910290667520',
            isDisabled: false,
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: true,
            label: '是否拍照',
            parentField: null,
            placeholder: null,
            seq: 5,
            verifyExp: '',
          },
          {
            columnType: 'varchar(2000)',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            field: 'memo',
            fieldType: null,
            id: '2009369001741768704',
            isDisabled: false,
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: true,
            label: '备注',
            parentField: null,
            placeholder: null,
            seq: 6,
            verifyExp: '',
          },
          {
            columnType: 'varchar(80)',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            field: 'status',
            fieldType: null,
            id: '3100688443270617088',
            isDisabled: false,
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: true,
            label: '状态',
            parentField: null,
            placeholder: null,
            seq: 7,
            verifyExp: '',
          },
          {
            columnType: 'bigint',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            field: 'id',
            fieldType: null,
            id: '857360722877861888',
            isDisabled: false,
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: false,
            label: '',
            parentField: null,
            placeholder: null,
            seq: 8,
            verifyExp: '',
          },
          {
            columnType: 'datetime(4)',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            field: 'time_create',
            fieldType: null,
            id: '204050571474679808',
            isDisabled: false,
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: false,
            label: '创建时间',
            parentField: null,
            placeholder: null,
            seq: 9,
            verifyExp: '',
          },
          {
            columnType: 'varchar(80)',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            field: 'creator',
            fieldType: null,
            id: '2689044083408650240',
            isDisabled: false,
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: false,
            label: '创建人',
            parentField: null,
            placeholder: null,
            seq: 10,
            verifyExp: '',
          },
          {
            columnType: 'datetime(4)',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            field: 'time_modified',
            fieldType: null,
            id: '452483409669943296',
            isDisabled: false,
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: false,
            label: '修改时间',
            parentField: null,
            placeholder: null,
            seq: 11,
            verifyExp: '',
          },
          {
            columnType: 'varchar(80)',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            field: 'modifier',
            fieldType: null,
            id: '7416972890001125376',
            isDisabled: false,
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: false,
            label: '修改人',
            parentField: null,
            placeholder: null,
            seq: 12,
            verifyExp: '',
          },
          {
            columnType: 'int',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            field: 'state',
            fieldType: null,
            id: '1103094797897347072',
            isDisabled: false,
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: false,
            label: '1可用；0禁用',
            parentField: null,
            placeholder: null,
            seq: 13,
            verifyExp: '',
          },
          {
            columnType: 'bigint',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            field: 'eid',
            fieldType: null,
            id: '5817187759097767936',
            isDisabled: false,
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: false,
            label: '企业ID',
            parentField: null,
            placeholder: null,
            seq: 14,
            verifyExp: '',
          },
          {
            columnType: 'bigint',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            field: 'oid',
            fieldType: null,
            id: '398730972504778752',
            isDisabled: false,
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: false,
            label: '组织ID',
            parentField: null,
            placeholder: null,
            seq: 15,
            verifyExp: '',
          },
          {
            columnType: 'varchar(80)',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            field: 'maintenance_item_name',
            fieldType: null,
            id: null,
            isDisabled: false,
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: true,
            label: '保养项目名称',
            parentField: null,
            placeholder: null,
            seq: 11,
            verifyExp: '',
          },
          {
            columnType: 'varchar(2000)',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            field: 'maintenance_item_require',
            fieldType: null,
            id: null,
            isDisabled: false,
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: true,
            label: '保养项目要求',
            parentField: null,
            placeholder: null,
            seq: 12,
            verifyExp: '',
          },
        ],
        id: null,
        importCode: null,
        isCustomButton: false,
        isEnabled: false,
        jumpLink: null,
        needCheckSelectRow: false,
        seq: 1,
      },
      {
        actionType: 'form-edit',
        apiAction: null,
        buttonCode: 'edit',
        buttonName: '编辑',
        buttonPosition: 'row',
        buttonTheme: 'primary',
        customApi: null,
        deleteType: '',
        formColumnSetting: [
          {
            columnType: 'varchar(80)',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            field: 'bill_no',
            fieldType: null,
            id: '1358777087314993152',
            isDisabled: false,
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: true,
            label: '单据号',
            parentField: null,
            placeholder: null,
            seq: 0,
            verifyExp: '',
          },
          {
            columnType: 'bigint',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            field: 'e_maintenance_bill_head_id',
            fieldType: null,
            id: '583542975499554816',
            isDisabled: false,
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: true,
            label: '设备保养单据头ID',
            parentField: null,
            placeholder: null,
            seq: 1,
            verifyExp: '',
          },
          {
            columnType: 'varchar(80)',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            field: 'maintenance_item_code',
            fieldType: null,
            id: '1384302817068023808',
            isDisabled: false,
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: true,
            label: '保养项目编码',
            parentField: null,
            placeholder: null,
            seq: 2,
            verifyExp: '',
          },
          {
            columnType: 'int',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            field: 'is_photo',
            fieldType: null,
            id: '7775309910290667520',
            isDisabled: false,
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: true,
            label: '是否拍照',
            parentField: null,
            placeholder: null,
            seq: 5,
            verifyExp: '',
          },
          {
            columnType: 'varchar(2000)',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            field: 'memo',
            fieldType: null,
            id: '2009369001741768704',
            isDisabled: false,
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: true,
            label: '备注',
            parentField: null,
            placeholder: null,
            seq: 6,
            verifyExp: '',
          },
          {
            columnType: 'varchar(80)',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            field: 'status',
            fieldType: null,
            id: '3100688443270617088',
            isDisabled: false,
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: true,
            label: '状态',
            parentField: null,
            placeholder: null,
            seq: 7,
            verifyExp: '',
          },
          {
            columnType: 'bigint',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            field: 'id',
            fieldType: null,
            id: '857360722877861888',
            isDisabled: false,
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: false,
            label: '',
            parentField: null,
            placeholder: null,
            seq: 8,
            verifyExp: '',
          },
          {
            columnType: 'datetime(4)',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            field: 'time_create',
            fieldType: null,
            id: '204050571474679808',
            isDisabled: false,
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: false,
            label: '创建时间',
            parentField: null,
            placeholder: null,
            seq: 9,
            verifyExp: '',
          },
          {
            columnType: 'varchar(80)',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            field: 'creator',
            fieldType: null,
            id: '2689044083408650240',
            isDisabled: false,
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: false,
            label: '创建人',
            parentField: null,
            placeholder: null,
            seq: 10,
            verifyExp: '',
          },
          {
            columnType: 'datetime(4)',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            field: 'time_modified',
            fieldType: null,
            id: '452483409669943296',
            isDisabled: false,
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: false,
            label: '修改时间',
            parentField: null,
            placeholder: null,
            seq: 11,
            verifyExp: '',
          },
          {
            columnType: 'varchar(80)',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            field: 'modifier',
            fieldType: null,
            id: '7416972890001125376',
            isDisabled: false,
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: false,
            label: '修改人',
            parentField: null,
            placeholder: null,
            seq: 12,
            verifyExp: '',
          },
          {
            columnType: 'int',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            field: 'state',
            fieldType: null,
            id: '1103094797897347072',
            isDisabled: false,
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: false,
            label: '1可用；0禁用',
            parentField: null,
            placeholder: null,
            seq: 13,
            verifyExp: '',
          },
          {
            columnType: 'bigint',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            field: 'eid',
            fieldType: null,
            id: '5817187759097767936',
            isDisabled: false,
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: false,
            label: '企业ID',
            parentField: null,
            placeholder: null,
            seq: 14,
            verifyExp: '',
          },
          {
            columnType: 'bigint',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            field: 'oid',
            fieldType: null,
            id: '398730972504778752',
            isDisabled: false,
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: false,
            label: '组织ID',
            parentField: null,
            placeholder: null,
            seq: 15,
            verifyExp: '',
          },
          {
            columnType: 'varchar(80)',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            field: 'maintenance_item_name',
            fieldType: null,
            id: null,
            isDisabled: false,
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: true,
            label: '保养项目名称',
            parentField: null,
            placeholder: null,
            seq: 11,
            verifyExp: '',
          },
          {
            columnType: 'varchar(2000)',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            field: 'maintenance_item_require',
            fieldType: null,
            id: null,
            isDisabled: false,
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: true,
            label: '保养项目要求',
            parentField: null,
            placeholder: null,
            seq: 12,
            verifyExp: '',
          },
        ],
        id: null,
        importCode: null,
        isCustomButton: false,
        isEnabled: false,
        jumpLink: null,
        needCheckSelectRow: false,
        seq: 2,
      },
      {
        actionType: 'delete',
        apiAction: null,
        buttonCode: 'delete',
        buttonName: '删除',
        buttonPosition: 'row',
        buttonTheme: 'danger',
        customApi: null,
        deleteType: 'logical',
        formColumnSetting: [],
        id: null,
        importCode: null,
        isCustomButton: false,
        isEnabled: false,
        jumpLink: null,
        needCheckSelectRow: true,
        seq: 3,
      },
    ],
    datasourceSetting: [],
    searchSetting: [],
    tableSetting: {
      columnSetting: [
        {
          align: 'center',
          canDelete: false,
          columnDefault: null,
          columnDesc: '保养项目编码',
          columnKey: '',
          columnName: 'maintenance_item_code',
          columnType: 'varchar(80)',
          columnWidth: 100,
          componentSource: null,
          id: '1384302817068023808',
          isAutoWidth: true,
          isDataDefault: false,
          isDatabaseField: true,
          isHandAdd: false,
          isLeftFixed: false,
          isRightFixed: false,
          isVisible: true,
          nullable: 'NO',
          seq: 1,
          tableName: 'e_maintenance_bill_dtl',
        },
        {
          align: 'center',
          canDelete: false,
          columnDefault: null,
          columnDesc: '保养项目名称',
          columnKey: '',
          columnName: 'maintenance_item_name',
          columnType: 'varchar(80)',
          columnWidth: 100,
          componentSource: null,
          id: null,
          isAutoWidth: true,
          isDataDefault: false,
          isDatabaseField: true,
          isHandAdd: false,
          isLeftFixed: false,
          isRightFixed: false,
          isVisible: true,
          nullable: 'NO',
          seq: 2,
          tableName: 'e_maintenance_bill_dtl',
        },
        {
          align: 'center',
          canDelete: false,
          columnDefault: null,
          columnDesc: '保养项目要求',
          columnKey: '',
          columnName: 'maintenance_item_require',
          columnType: 'varchar(2000)',
          columnWidth: 100,
          componentSource: null,
          id: null,
          isAutoWidth: true,
          isDataDefault: false,
          isDatabaseField: true,
          isHandAdd: false,
          isLeftFixed: false,
          isRightFixed: false,
          isVisible: true,
          nullable: 'YES',
          seq: 3,
          tableName: 'e_maintenance_bill_dtl',
        },
        {
          align: 'center',
          canDelete: false,
          columnDefault: null,
          columnDesc: '是否拍照',
          columnKey: '',
          columnName: 'is_photo',
          columnType: 'int',
          columnWidth: 100,
          componentSource: {
            customDict: {
              dicData: [
                {
                  label: '是',
                  value: '1',
                },
                {
                  label: '否',
                  value: '0',
                },
              ],
            },
            dataTable: null,
            sourceType: null,
          },
          id: '7775309910290667520',
          isAutoWidth: true,
          isDataDefault: false,
          isDatabaseField: true,
          isHandAdd: false,
          isLeftFixed: false,
          isRightFixed: false,
          isVisible: true,
          nullable: 'NO',
          seq: 4,
          tableName: 'e_maintenance_bill_dtl',
        },
        {
          align: 'center',
          canDelete: false,
          columnDefault: null,
          columnDesc: '状态',
          columnKey: '',
          columnName: 'status',
          columnType: 'varchar(80)',
          columnWidth: 100,
          componentSource: {
            customDict: {
              dicData: [
                {
                  label: '待保养',
                  value: 'UNMAINTAIN',
                },
                {
                  label: '保养中',
                  value: 'MAINTAINING',
                },
                {
                  label: '待验收',
                  value: 'UNACCEPT',
                },
                {
                  label: '已关闭',
                  value: 'CLOSED',
                },
              ],
            },
            dataTable: null,
            sourceType: null,
          },
          id: '3100688443270617088',
          isAutoWidth: true,
          isDataDefault: false,
          isDatabaseField: true,
          isHandAdd: false,
          isLeftFixed: false,
          isRightFixed: false,
          isVisible: true,
          nullable: 'NO',
          seq: 5,
          tableName: 'e_maintenance_bill_dtl',
        },
        {
          align: 'center',
          canDelete: false,
          columnDefault: null,
          columnDesc: '单据号',
          columnKey: '',
          columnName: 'bill_no',
          columnType: 'varchar(80)',
          columnWidth: 100,
          componentSource: null,
          id: '1358777087314993152',
          isAutoWidth: true,
          isDataDefault: false,
          isDatabaseField: true,
          isHandAdd: false,
          isLeftFixed: false,
          isRightFixed: false,
          isVisible: false,
          nullable: 'NO',
          seq: 6,
          tableName: 'e_maintenance_bill_dtl',
        },
        {
          align: 'center',
          canDelete: false,
          columnDefault: null,
          columnDesc: '设备保养单据头ID',
          columnKey: '',
          columnName: 'e_maintenance_bill_head_id',
          columnType: 'bigint',
          columnWidth: 100,
          componentSource: null,
          id: '583542975499554816',
          isAutoWidth: true,
          isDataDefault: false,
          isDatabaseField: true,
          isHandAdd: false,
          isLeftFixed: false,
          isRightFixed: false,
          isVisible: false,
          nullable: 'NO',
          seq: 7,
          tableName: 'e_maintenance_bill_dtl',
        },
        {
          align: 'center',
          canDelete: false,
          columnDefault: null,
          columnDesc: '备注',
          columnKey: '',
          columnName: 'memo',
          columnType: 'varchar(2000)',
          columnWidth: 100,
          componentSource: null,
          id: '2009369001741768704',
          isAutoWidth: true,
          isDataDefault: false,
          isDatabaseField: true,
          isHandAdd: false,
          isLeftFixed: false,
          isRightFixed: false,
          isVisible: false,
          nullable: 'YES',
          seq: 8,
          tableName: 'e_maintenance_bill_dtl',
        },
        {
          align: 'center',
          canDelete: false,
          columnDefault: null,
          columnDesc: '',
          columnKey: 'PRI',
          columnName: 'id',
          columnType: 'bigint',
          columnWidth: 100,
          componentSource: null,
          id: '857360722877861888',
          isAutoWidth: true,
          isDataDefault: true,
          isDatabaseField: true,
          isHandAdd: false,
          isLeftFixed: false,
          isRightFixed: false,
          isVisible: false,
          nullable: 'NO',
          seq: 9,
          tableName: 'e_maintenance_bill_dtl',
        },
        {
          align: 'center',
          canDelete: false,
          columnDefault: null,
          columnDesc: '创建时间',
          columnKey: '',
          columnName: 'time_create',
          columnType: 'datetime(4)',
          columnWidth: 100,
          componentSource: null,
          id: '204050571474679808',
          isAutoWidth: true,
          isDataDefault: true,
          isDatabaseField: true,
          isHandAdd: false,
          isLeftFixed: false,
          isRightFixed: false,
          isVisible: false,
          nullable: 'NO',
          seq: 10,
          tableName: 'e_maintenance_bill_dtl',
        },
        {
          align: 'center',
          canDelete: false,
          columnDefault: null,
          columnDesc: '创建人',
          columnKey: '',
          columnName: 'creator',
          columnType: 'varchar(80)',
          columnWidth: 100,
          componentSource: null,
          id: '2689044083408650240',
          isAutoWidth: true,
          isDataDefault: true,
          isDatabaseField: true,
          isHandAdd: false,
          isLeftFixed: false,
          isRightFixed: false,
          isVisible: false,
          nullable: 'NO',
          seq: 11,
          tableName: 'e_maintenance_bill_dtl',
        },
        {
          align: 'center',
          canDelete: false,
          columnDefault: null,
          columnDesc: '修改时间',
          columnKey: '',
          columnName: 'time_modified',
          columnType: 'datetime(4)',
          columnWidth: 100,
          componentSource: null,
          id: '452483409669943296',
          isAutoWidth: true,
          isDataDefault: true,
          isDatabaseField: true,
          isHandAdd: false,
          isLeftFixed: false,
          isRightFixed: false,
          isVisible: false,
          nullable: 'YES',
          seq: 12,
          tableName: 'e_maintenance_bill_dtl',
        },
        {
          align: 'center',
          canDelete: false,
          columnDefault: null,
          columnDesc: '修改人',
          columnKey: '',
          columnName: 'modifier',
          columnType: 'varchar(80)',
          columnWidth: 100,
          componentSource: null,
          id: '7416972890001125376',
          isAutoWidth: true,
          isDataDefault: true,
          isDatabaseField: true,
          isHandAdd: false,
          isLeftFixed: false,
          isRightFixed: false,
          isVisible: false,
          nullable: 'YES',
          seq: 13,
          tableName: 'e_maintenance_bill_dtl',
        },
        {
          align: 'center',
          canDelete: false,
          columnDefault: null,
          columnDesc: '1可用；0禁用',
          columnKey: '',
          columnName: 'state',
          columnType: 'int',
          columnWidth: 100,
          componentSource: null,
          id: '1103094797897347072',
          isAutoWidth: true,
          isDataDefault: true,
          isDatabaseField: true,
          isHandAdd: false,
          isLeftFixed: false,
          isRightFixed: false,
          isVisible: false,
          nullable: 'NO',
          seq: 14,
          tableName: 'e_maintenance_bill_dtl',
        },
        {
          align: 'center',
          canDelete: false,
          columnDefault: null,
          columnDesc: '企业ID',
          columnKey: 'MUL',
          columnName: 'eid',
          columnType: 'bigint',
          columnWidth: 100,
          componentSource: null,
          id: '5817187759097767936',
          isAutoWidth: true,
          isDataDefault: true,
          isDatabaseField: true,
          isHandAdd: false,
          isLeftFixed: false,
          isRightFixed: false,
          isVisible: false,
          nullable: 'NO',
          seq: 15,
          tableName: 'e_maintenance_bill_dtl',
        },
        {
          align: 'center',
          canDelete: false,
          columnDefault: null,
          columnDesc: '组织ID',
          columnKey: '',
          columnName: 'oid',
          columnType: 'bigint',
          columnWidth: 100,
          componentSource: null,
          id: '398730972504778752',
          isAutoWidth: true,
          isDataDefault: true,
          isDatabaseField: true,
          isHandAdd: false,
          isLeftFixed: false,
          isRightFixed: false,
          isVisible: false,
          nullable: 'NO',
          seq: 16,
          tableName: 'e_maintenance_bill_dtl',
        },
      ],
      pageSize: null,
      sortField: 'time_create',
      sortType: 'desc',
      tableTitle: '模具保养单据项目',
      usePage: false,
    },
  },
  eid: '1',
  exportFileName: null,
  exportLimitCount: null,
  groupCode: 'MOULD',
  groupName: '模具',
  id: '1825506456137457666',
  importFileName: null,
  isCustomerSql: null,
  isDebug: null,
  jsonContent:
    '{"datasourceSetting":[],"tableSetting":{"tableTitle":"模具保养单据项目","usePage":false,"pageSize":null,"sortField":"time_create","sortType":"desc","columnSetting":[{"seq":1,"id":"1384302817068023808","columnDefault":null,"columnDesc":"保养项目编码","columnKey":"","columnName":"maintenance_item_code","columnType":"varchar(80)","nullable":"NO","tableName":"e_maintenance_bill_dtl","columnWidth":100,"align":"center","canDelete":false,"componentSource":null,"isDatabaseField":true,"isAutoWidth":true,"isVisible":true,"isLeftFixed":false,"isRightFixed":false,"isDataDefault":false,"isHandAdd":false},{"seq":2,"id":null,"columnDefault":null,"columnDesc":"保养项目名称","columnKey":"","columnName":"maintenance_item_name","columnType":"varchar(80)","nullable":"NO","tableName":"e_maintenance_bill_dtl","columnWidth":100,"align":"center","canDelete":false,"componentSource":null,"isDatabaseField":true,"isAutoWidth":true,"isVisible":true,"isLeftFixed":false,"isRightFixed":false,"isDataDefault":false,"isHandAdd":false},{"seq":3,"id":null,"columnDefault":null,"columnDesc":"保养项目要求","columnKey":"","columnName":"maintenance_item_require","columnType":"varchar(2000)","nullable":"YES","tableName":"e_maintenance_bill_dtl","columnWidth":100,"align":"center","canDelete":false,"componentSource":null,"isDatabaseField":true,"isAutoWidth":true,"isVisible":true,"isLeftFixed":false,"isRightFixed":false,"isDataDefault":false,"isHandAdd":false},{"seq":4,"id":"7775309910290667520","columnDefault":null,"columnDesc":"是否拍照","columnKey":"","columnName":"is_photo","columnType":"int","nullable":"NO","tableName":"e_maintenance_bill_dtl","columnWidth":100,"align":"center","canDelete":false,"componentSource":{"sourceType":null,"customDict":{"dicData":[{"label":"是","value":"1"},{"label":"否","value":"0"}]},"dataTable":null},"isDatabaseField":true,"isAutoWidth":true,"isVisible":true,"isLeftFixed":false,"isRightFixed":false,"isDataDefault":false,"isHandAdd":false},{"seq":5,"id":"3100688443270617088","columnDefault":null,"columnDesc":"状态","columnKey":"","columnName":"status","columnType":"varchar(80)","nullable":"NO","tableName":"e_maintenance_bill_dtl","columnWidth":100,"align":"center","canDelete":false,"componentSource":{"sourceType":null,"customDict":{"dicData":[{"label":"待保养","value":"UNMAINTAIN"},{"label":"保养中","value":"MAINTAINING"},{"label":"待验收","value":"UNACCEPT"},{"label":"已关闭","value":"CLOSED"}]},"dataTable":null},"isDatabaseField":true,"isAutoWidth":true,"isVisible":true,"isLeftFixed":false,"isRightFixed":false,"isDataDefault":false,"isHandAdd":false},{"seq":6,"id":"1358777087314993152","columnDefault":null,"columnDesc":"单据号","columnKey":"","columnName":"bill_no","columnType":"varchar(80)","nullable":"NO","tableName":"e_maintenance_bill_dtl","columnWidth":100,"align":"center","canDelete":false,"componentSource":null,"isDatabaseField":true,"isAutoWidth":true,"isVisible":false,"isLeftFixed":false,"isRightFixed":false,"isDataDefault":false,"isHandAdd":false},{"seq":7,"id":"583542975499554816","columnDefault":null,"columnDesc":"设备保养单据头ID","columnKey":"","columnName":"e_maintenance_bill_head_id","columnType":"bigint","nullable":"NO","tableName":"e_maintenance_bill_dtl","columnWidth":100,"align":"center","canDelete":false,"componentSource":null,"isDatabaseField":true,"isAutoWidth":true,"isVisible":false,"isLeftFixed":false,"isRightFixed":false,"isDataDefault":false,"isHandAdd":false},{"seq":8,"id":"2009369001741768704","columnDefault":null,"columnDesc":"备注","columnKey":"","columnName":"memo","columnType":"varchar(2000)","nullable":"YES","tableName":"e_maintenance_bill_dtl","columnWidth":100,"align":"center","canDelete":false,"componentSource":null,"isDatabaseField":true,"isAutoWidth":true,"isVisible":false,"isLeftFixed":false,"isRightFixed":false,"isDataDefault":false,"isHandAdd":false},{"seq":9,"id":"857360722877861888","columnDefault":null,"columnDesc":"","columnKey":"PRI","columnName":"id","columnType":"bigint","nullable":"NO","tableName":"e_maintenance_bill_dtl","columnWidth":100,"align":"center","canDelete":false,"componentSource":null,"isDatabaseField":true,"isAutoWidth":true,"isVisible":false,"isLeftFixed":false,"isRightFixed":false,"isDataDefault":true,"isHandAdd":false},{"seq":10,"id":"204050571474679808","columnDefault":null,"columnDesc":"创建时间","columnKey":"","columnName":"time_create","columnType":"datetime(4)","nullable":"NO","tableName":"e_maintenance_bill_dtl","columnWidth":100,"align":"center","canDelete":false,"componentSource":null,"isDatabaseField":true,"isAutoWidth":true,"isVisible":false,"isLeftFixed":false,"isRightFixed":false,"isDataDefault":true,"isHandAdd":false},{"seq":11,"id":"2689044083408650240","columnDefault":null,"columnDesc":"创建人","columnKey":"","columnName":"creator","columnType":"varchar(80)","nullable":"NO","tableName":"e_maintenance_bill_dtl","columnWidth":100,"align":"center","canDelete":false,"componentSource":null,"isDatabaseField":true,"isAutoWidth":true,"isVisible":false,"isLeftFixed":false,"isRightFixed":false,"isDataDefault":true,"isHandAdd":false},{"seq":12,"id":"452483409669943296","columnDefault":null,"columnDesc":"修改时间","columnKey":"","columnName":"time_modified","columnType":"datetime(4)","nullable":"YES","tableName":"e_maintenance_bill_dtl","columnWidth":100,"align":"center","canDelete":false,"componentSource":null,"isDatabaseField":true,"isAutoWidth":true,"isVisible":false,"isLeftFixed":false,"isRightFixed":false,"isDataDefault":true,"isHandAdd":false},{"seq":13,"id":"7416972890001125376","columnDefault":null,"columnDesc":"修改人","columnKey":"","columnName":"modifier","columnType":"varchar(80)","nullable":"YES","tableName":"e_maintenance_bill_dtl","columnWidth":100,"align":"center","canDelete":false,"componentSource":null,"isDatabaseField":true,"isAutoWidth":true,"isVisible":false,"isLeftFixed":false,"isRightFixed":false,"isDataDefault":true,"isHandAdd":false},{"seq":14,"id":"1103094797897347072","columnDefault":null,"columnDesc":"1可用；0禁用","columnKey":"","columnName":"state","columnType":"int","nullable":"NO","tableName":"e_maintenance_bill_dtl","columnWidth":100,"align":"center","canDelete":false,"componentSource":null,"isDatabaseField":true,"isAutoWidth":true,"isVisible":false,"isLeftFixed":false,"isRightFixed":false,"isDataDefault":true,"isHandAdd":false},{"seq":15,"id":"5817187759097767936","columnDefault":null,"columnDesc":"企业ID","columnKey":"MUL","columnName":"eid","columnType":"bigint","nullable":"NO","tableName":"e_maintenance_bill_dtl","columnWidth":100,"align":"center","canDelete":false,"componentSource":null,"isDatabaseField":true,"isAutoWidth":true,"isVisible":false,"isLeftFixed":false,"isRightFixed":false,"isDataDefault":true,"isHandAdd":false},{"seq":16,"id":"398730972504778752","columnDefault":null,"columnDesc":"组织ID","columnKey":"","columnName":"oid","columnType":"bigint","nullable":"NO","tableName":"e_maintenance_bill_dtl","columnWidth":100,"align":"center","canDelete":false,"componentSource":null,"isDatabaseField":true,"isAutoWidth":true,"isVisible":false,"isLeftFixed":false,"isRightFixed":false,"isDataDefault":true,"isHandAdd":false}]},"searchSetting":[],"buttonSetting":[{"seq":1,"id":null,"buttonCode":"add","buttonName":"新增","buttonPosition":"tableHeader","buttonTheme":"primary","needCheckSelectRow":false,"actionType":"form-add","formColumnSetting":[{"seq":0,"id":"1358777087314993152","field":"bill_no","label":"单据号","component":"t-input","componentParam":"","placeholder":null,"defaultValue":"","fieldType":null,"columnType":"varchar(80)","parentField":null,"verifyExp":"","componentSource":null,"isVisible":true,"isDisabled":false,"isMultiple":false,"isRequired":false,"isKeyField":false},{"seq":1,"id":"583542975499554816","field":"e_maintenance_bill_head_id","label":"设备保养单据头ID","component":"t-input","componentParam":"","placeholder":null,"defaultValue":"","fieldType":null,"columnType":"bigint","parentField":null,"verifyExp":"","componentSource":null,"isVisible":true,"isDisabled":false,"isMultiple":false,"isRequired":false,"isKeyField":false},{"seq":2,"id":"1384302817068023808","field":"maintenance_item_code","label":"保养项目编码","component":"t-input","componentParam":"","placeholder":null,"defaultValue":"","fieldType":null,"columnType":"varchar(80)","parentField":null,"verifyExp":"","componentSource":null,"isVisible":true,"isDisabled":false,"isMultiple":false,"isRequired":false,"isKeyField":false},{"seq":5,"id":"7775309910290667520","field":"is_photo","label":"是否拍照","component":"t-input","componentParam":"","placeholder":null,"defaultValue":"","fieldType":null,"columnType":"int","parentField":null,"verifyExp":"","componentSource":null,"isVisible":true,"isDisabled":false,"isMultiple":false,"isRequired":false,"isKeyField":false},{"seq":6,"id":"2009369001741768704","field":"memo","label":"备注","component":"t-input","componentParam":"","placeholder":null,"defaultValue":"","fieldType":null,"columnType":"varchar(2000)","parentField":null,"verifyExp":"","componentSource":null,"isVisible":true,"isDisabled":false,"isMultiple":false,"isRequired":false,"isKeyField":false},{"seq":7,"id":"3100688443270617088","field":"status","label":"状态","component":"t-input","componentParam":"","placeholder":null,"defaultValue":"","fieldType":null,"columnType":"varchar(80)","parentField":null,"verifyExp":"","componentSource":null,"isVisible":true,"isDisabled":false,"isMultiple":false,"isRequired":false,"isKeyField":false},{"seq":8,"id":"857360722877861888","field":"id","label":"","component":"t-input","componentParam":"","placeholder":null,"defaultValue":"","fieldType":null,"columnType":"bigint","parentField":null,"verifyExp":"","componentSource":null,"isVisible":false,"isDisabled":false,"isMultiple":false,"isRequired":false,"isKeyField":false},{"seq":9,"id":"204050571474679808","field":"time_create","label":"创建时间","component":"t-input","componentParam":"","placeholder":null,"defaultValue":"","fieldType":null,"columnType":"datetime(4)","parentField":null,"verifyExp":"","componentSource":null,"isVisible":false,"isDisabled":false,"isMultiple":false,"isRequired":false,"isKeyField":false},{"seq":10,"id":"2689044083408650240","field":"creator","label":"创建人","component":"t-input","componentParam":"","placeholder":null,"defaultValue":"","fieldType":null,"columnType":"varchar(80)","parentField":null,"verifyExp":"","componentSource":null,"isVisible":false,"isDisabled":false,"isMultiple":false,"isRequired":false,"isKeyField":false},{"seq":11,"id":"452483409669943296","field":"time_modified","label":"修改时间","component":"t-input","componentParam":"","placeholder":null,"defaultValue":"","fieldType":null,"columnType":"datetime(4)","parentField":null,"verifyExp":"","componentSource":null,"isVisible":false,"isDisabled":false,"isMultiple":false,"isRequired":false,"isKeyField":false},{"seq":12,"id":"7416972890001125376","field":"modifier","label":"修改人","component":"t-input","componentParam":"","placeholder":null,"defaultValue":"","fieldType":null,"columnType":"varchar(80)","parentField":null,"verifyExp":"","componentSource":null,"isVisible":false,"isDisabled":false,"isMultiple":false,"isRequired":false,"isKeyField":false},{"seq":13,"id":"1103094797897347072","field":"state","label":"1可用；0禁用","component":"t-input","componentParam":"","placeholder":null,"defaultValue":"","fieldType":null,"columnType":"int","parentField":null,"verifyExp":"","componentSource":null,"isVisible":false,"isDisabled":false,"isMultiple":false,"isRequired":false,"isKeyField":false},{"seq":14,"id":"5817187759097767936","field":"eid","label":"企业ID","component":"t-input","componentParam":"","placeholder":null,"defaultValue":"","fieldType":null,"columnType":"bigint","parentField":null,"verifyExp":"","componentSource":null,"isVisible":false,"isDisabled":false,"isMultiple":false,"isRequired":false,"isKeyField":false},{"seq":15,"id":"398730972504778752","field":"oid","label":"组织ID","component":"t-input","componentParam":"","placeholder":null,"defaultValue":"","fieldType":null,"columnType":"bigint","parentField":null,"verifyExp":"","componentSource":null,"isVisible":false,"isDisabled":false,"isMultiple":false,"isRequired":false,"isKeyField":false},{"seq":11,"id":null,"field":"maintenance_item_name","label":"保养项目名称","component":"t-input","componentParam":"","placeholder":null,"defaultValue":"","fieldType":null,"columnType":"varchar(80)","parentField":null,"verifyExp":"","componentSource":null,"isVisible":true,"isDisabled":false,"isMultiple":false,"isRequired":false,"isKeyField":false},{"seq":12,"id":null,"field":"maintenance_item_require","label":"保养项目要求","component":"t-input","componentParam":"","placeholder":null,"defaultValue":"","fieldType":null,"columnType":"varchar(2000)","parentField":null,"verifyExp":"","componentSource":null,"isVisible":true,"isDisabled":false,"isMultiple":false,"isRequired":false,"isKeyField":false}],"deleteType":"logical","jumpLink":null,"customApi":null,"apiAction":null,"importCode":null,"isEnabled":false,"isCustomButton":false},{"seq":2,"id":null,"buttonCode":"edit","buttonName":"编辑","buttonPosition":"row","buttonTheme":"primary","needCheckSelectRow":false,"actionType":"form-edit","formColumnSetting":[{"seq":0,"id":"1358777087314993152","field":"bill_no","label":"单据号","component":"t-input","componentParam":"","placeholder":null,"defaultValue":"","fieldType":null,"columnType":"varchar(80)","parentField":null,"verifyExp":"","componentSource":null,"isVisible":true,"isDisabled":false,"isMultiple":false,"isRequired":false,"isKeyField":false},{"seq":1,"id":"583542975499554816","field":"e_maintenance_bill_head_id","label":"设备保养单据头ID","component":"t-input","componentParam":"","placeholder":null,"defaultValue":"","fieldType":null,"columnType":"bigint","parentField":null,"verifyExp":"","componentSource":null,"isVisible":true,"isDisabled":false,"isMultiple":false,"isRequired":false,"isKeyField":false},{"seq":2,"id":"1384302817068023808","field":"maintenance_item_code","label":"保养项目编码","component":"t-input","componentParam":"","placeholder":null,"defaultValue":"","fieldType":null,"columnType":"varchar(80)","parentField":null,"verifyExp":"","componentSource":null,"isVisible":true,"isDisabled":false,"isMultiple":false,"isRequired":false,"isKeyField":false},{"seq":5,"id":"7775309910290667520","field":"is_photo","label":"是否拍照","component":"t-input","componentParam":"","placeholder":null,"defaultValue":"","fieldType":null,"columnType":"int","parentField":null,"verifyExp":"","componentSource":null,"isVisible":true,"isDisabled":false,"isMultiple":false,"isRequired":false,"isKeyField":false},{"seq":6,"id":"2009369001741768704","field":"memo","label":"备注","component":"t-input","componentParam":"","placeholder":null,"defaultValue":"","fieldType":null,"columnType":"varchar(2000)","parentField":null,"verifyExp":"","componentSource":null,"isVisible":true,"isDisabled":false,"isMultiple":false,"isRequired":false,"isKeyField":false},{"seq":7,"id":"3100688443270617088","field":"status","label":"状态","component":"t-input","componentParam":"","placeholder":null,"defaultValue":"","fieldType":null,"columnType":"varchar(80)","parentField":null,"verifyExp":"","componentSource":null,"isVisible":true,"isDisabled":false,"isMultiple":false,"isRequired":false,"isKeyField":false},{"seq":8,"id":"857360722877861888","field":"id","label":"","component":"t-input","componentParam":"","placeholder":null,"defaultValue":"","fieldType":null,"columnType":"bigint","parentField":null,"verifyExp":"","componentSource":null,"isVisible":false,"isDisabled":false,"isMultiple":false,"isRequired":false,"isKeyField":false},{"seq":9,"id":"204050571474679808","field":"time_create","label":"创建时间","component":"t-input","componentParam":"","placeholder":null,"defaultValue":"","fieldType":null,"columnType":"datetime(4)","parentField":null,"verifyExp":"","componentSource":null,"isVisible":false,"isDisabled":false,"isMultiple":false,"isRequired":false,"isKeyField":false},{"seq":10,"id":"2689044083408650240","field":"creator","label":"创建人","component":"t-input","componentParam":"","placeholder":null,"defaultValue":"","fieldType":null,"columnType":"varchar(80)","parentField":null,"verifyExp":"","componentSource":null,"isVisible":false,"isDisabled":false,"isMultiple":false,"isRequired":false,"isKeyField":false},{"seq":11,"id":"452483409669943296","field":"time_modified","label":"修改时间","component":"t-input","componentParam":"","placeholder":null,"defaultValue":"","fieldType":null,"columnType":"datetime(4)","parentField":null,"verifyExp":"","componentSource":null,"isVisible":false,"isDisabled":false,"isMultiple":false,"isRequired":false,"isKeyField":false},{"seq":12,"id":"7416972890001125376","field":"modifier","label":"修改人","component":"t-input","componentParam":"","placeholder":null,"defaultValue":"","fieldType":null,"columnType":"varchar(80)","parentField":null,"verifyExp":"","componentSource":null,"isVisible":false,"isDisabled":false,"isMultiple":false,"isRequired":false,"isKeyField":false},{"seq":13,"id":"1103094797897347072","field":"state","label":"1可用；0禁用","component":"t-input","componentParam":"","placeholder":null,"defaultValue":"","fieldType":null,"columnType":"int","parentField":null,"verifyExp":"","componentSource":null,"isVisible":false,"isDisabled":false,"isMultiple":false,"isRequired":false,"isKeyField":false},{"seq":14,"id":"5817187759097767936","field":"eid","label":"企业ID","component":"t-input","componentParam":"","placeholder":null,"defaultValue":"","fieldType":null,"columnType":"bigint","parentField":null,"verifyExp":"","componentSource":null,"isVisible":false,"isDisabled":false,"isMultiple":false,"isRequired":false,"isKeyField":false},{"seq":15,"id":"398730972504778752","field":"oid","label":"组织ID","component":"t-input","componentParam":"","placeholder":null,"defaultValue":"","fieldType":null,"columnType":"bigint","parentField":null,"verifyExp":"","componentSource":null,"isVisible":false,"isDisabled":false,"isMultiple":false,"isRequired":false,"isKeyField":false},{"seq":11,"id":null,"field":"maintenance_item_name","label":"保养项目名称","component":"t-input","componentParam":"","placeholder":null,"defaultValue":"","fieldType":null,"columnType":"varchar(80)","parentField":null,"verifyExp":"","componentSource":null,"isVisible":true,"isDisabled":false,"isMultiple":false,"isRequired":false,"isKeyField":false},{"seq":12,"id":null,"field":"maintenance_item_require","label":"保养项目要求","component":"t-input","componentParam":"","placeholder":null,"defaultValue":"","fieldType":null,"columnType":"varchar(2000)","parentField":null,"verifyExp":"","componentSource":null,"isVisible":true,"isDisabled":false,"isMultiple":false,"isRequired":false,"isKeyField":false}],"deleteType":"","jumpLink":null,"customApi":null,"apiAction":null,"importCode":null,"isEnabled":false,"isCustomButton":false},{"seq":3,"id":null,"buttonCode":"delete","buttonName":"删除","buttonPosition":"row","buttonTheme":"danger","needCheckSelectRow":true,"actionType":"delete","formColumnSetting":[],"deleteType":"logical","jumpLink":null,"customApi":null,"apiAction":null,"importCode":null,"isEnabled":false,"isCustomButton":false}]}',
  modifier: 'administrator',
  operateColumnWidth: null,
  queryApi: null,
  seqColumnWidth: null,
  sqlContent: null,
  state: 1,
  templateCode: 'singleTableManage',
  templateName: '数据维护模板',
  templateUrl: '/main#/singleTableManage',
  timeCreate: '2024-08-19 20:13:50',
  timeModified: '2024-08-20 15:52:54',
  validateApi: null,
} as DomainParamVO;
