import { DomainParamButtonSetting } from '@/api/main';

export default {
  formColumnSetting: [
    {
      columnType: 'varchar(80)',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      isDisabled: false,
      field: 'maintenance_plan_code',
      fieldType: null,
      id: '1979249244809189376',
      isKeyField: true,
      isMultiple: false,
      isRequired: true,
      isVisible: true,
      label: '保养计划代码',
      placeholder: null,
      seq: 1,
      verifyExp: '',
    },
    {
      columnType: 'varchar(240)',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      isDisabled: false,
      field: 'maintenance_plan_name',
      fieldType: null,
      id: '6430913614447872000',
      isKeyField: false,
      isMultiple: false,
      isRequired: true,
      isVisible: true,
      label: '保养计划名称',
      placeholder: null,
      seq: 2,
      verifyExp: '',
    },
    {
      columnType: 'varchar(80)',
      component: 't-radio-group',
      componentParam: '',
      componentSource: {
        customDict: {
          dicData: [
            {
              label: '周期保养',
              value: 'PERIOD',
            },
            {
              label: '使用次数',
              value: 'USETIME',
            },
          ],
        },
        dataTable: {
          conditionData: [],
          mapBusinessDomain: '',
          mapTable: '',
          showField: '',
          valueField: '',
        },
        sourceType: 'customDict',
      },
      defaultValue: 'PERIOD',
      isDisabled: false,
      field: 'maintenance_plan_type',
      fieldType: null,
      id: '5781640216176422912',

      isKeyField: false,
      isMultiple: false,
      isRequired: true,
      isVisible: true,

      label: '保养计划方式',

      placeholder: null,

      seq: 3,
      verifyExp: '',
    },
    {
      columnType: 'datetime(4)',
      component: 't-date-picker',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      isDisabled: false,
      field: 'datetime_effect',
      fieldType: null,
      id: '7582449786451361792',

      isKeyField: false,
      isMultiple: false,
      isRequired: true,
      isVisible: true,

      label: '生效时间',

      placeholder: null,
      seq: 4,
      verifyExp: '',
    },
    {
      columnType: 'int',
      component: 't-input-number',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      isDisabled: false,
      field: 'day_maintenance_period',
      fieldType: null,
      id: '8079611604183496704',

      isKeyField: false,
      isMultiple: false,
      isRequired: true,
      isVisible: true,

      label: '保养周期（天）',

      placeholder: null,
      seq: 5,
      verifyExp: '',
    },
    {
      columnType: 'int',
      component: 't-input-number',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      isDisabled: false,
      field: 'day_early_warn',
      fieldType: null,
      id: '1957731539453566976',

      isKeyField: false,
      isMultiple: false,
      isRequired: true,
      isVisible: true,

      label: '预警提前期（天）',

      placeholder: null,
      seq: 6,
      verifyExp: '',
    },
    {
      columnType: 'int',
      component: 't-input-number',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      isDisabled: false,
      field: 'hour_run',
      fieldType: null,
      id: '4228583883284498432',

      isKeyField: false,
      isMultiple: false,
      isRequired: true,
      isVisible: false,

      label: '使用次数',

      placeholder: null,
      seq: 7,
      verifyExp: '',
    },
    {
      columnType: 'int',
      component: 't-input-number',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      isDisabled: false,
      field: 'hour_run_early',
      fieldType: null,
      id: '2861171201225009152',

      isKeyField: false,
      isMultiple: false,
      isRequired: true,
      isVisible: false,

      label: '提前次数',

      placeholder: null,
      seq: 8,
      verifyExp: '',
    },
    {
      columnType: 'String',
      component: 't-radio-group',
      componentSource: {
        sourceType: 'customDict',
        customDict: {
          dicData: [
            {
              label: '关联模具类型',
              value: 'mouldType',
            },
            // {
            //   label: '关联模具',
            //   value: 'mould',
            // },
          ],
        },
        dataTable: {
          mapBusinessDomain: '',
          mapTable: '',
          conditionData: [],
          valueField: '',
          showField: '',
        },
      },
      defaultValue: 'mouldType',
      isDisabled: false,
      field: 'relateType',
      fieldType: null,
      id: 'relateType',

      isKeyField: false,
      isMultiple: false,
      isRequired: true,
      isVisible: true,

      label: '关联类型',

      placeholder: null,
      seq: 2,
      verifyExp: '',
    },
    {
      columnType: 'varchar(80)',
      component: 'bcmp-select-param',
      componentParam: 'E_MOULD_TYPE',
      componentSource: null,
      defaultValue: '',
      isDisabled: false,
      field: 'mould_type',
      fieldType: null,
      id: '1191873293498304512',

      isKeyField: false,
      isMultiple: false,
      isRequired: true,
      isVisible: true,

      label: '模具类型',

      placeholder: null,
      seq: 9,
      verifyExp: '',
    },
    {
      columnType: 'bigint',
      component: 'bcmp-select-business',
      componentParam: 'mould',
      componentSource: null,
      defaultValue: '',
      isDisabled: false,
      field: 'm_mould_id',
      fieldType: null,
      id: '6372160288314134528',

      isKeyField: false,
      isMultiple: false,
      isRequired: true,
      isVisible: false,

      label: '模具',

      placeholder: null,
      seq: 10,
      verifyExp: '',
    },
    {
      columnType: 'int',
      component: 't-switch',
      componentParam: '',
      componentSource: null,
      defaultValue: '1',
      isDisabled: false,
      field: 'state',
      fieldType: null,
      id: '6848017972128808960',

      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: true,

      label: '启用状态',

      placeholder: null,
      seq: 11,
      verifyExp: '',
    },
    {
      columnType: 'datetime(4)',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      isDisabled: false,
      field: 'time_create',
      fieldType: null,
      id: '4750236166081570816',

      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,

      label: '创建时间',

      placeholder: null,
      seq: 12,
      verifyExp: '',
    },
    {
      columnType: 'bigint',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      isDisabled: false,
      field: 'id',
      fieldType: null,
      id: '6294374149532706816',

      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,

      label: '',

      placeholder: null,
      seq: 13,
      verifyExp: '',
    },
    {
      columnType: 'bigint',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      isDisabled: false,
      field: 'm_asset_type_id',
      fieldType: null,
      id: '196172220756541440',

      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,

      label: '资产类型表ID',

      placeholder: null,
      seq: 14,
      verifyExp: '',
    },
    {
      columnType: 'bigint',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      isDisabled: false,
      field: 'm_asset_brand_id',
      fieldType: null,
      id: '7194000198495977472',

      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,

      label: '资产品牌表ID',

      placeholder: null,
      seq: 15,
      verifyExp: '',
    },
    {
      columnType: 'bigint',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      isDisabled: false,
      field: 'm_asset_model_id',
      fieldType: null,
      id: '5356558238514077696',

      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,

      label: '资产型号表ID',

      placeholder: null,
      seq: 16,
      verifyExp: '',
    },
    {
      columnType: 'varchar(80)',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      isDisabled: false,
      field: 'creator',
      fieldType: null,
      id: '658595641727797248',

      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,

      label: '创建人',

      placeholder: null,
      seq: 17,
      verifyExp: '',
    },
    {
      columnType: 'datetime(4)',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      isDisabled: false,
      field: 'time_modified',
      fieldType: null,
      id: '9147958099678668800',

      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,

      label: '修改时间',

      placeholder: null,
      seq: 18,
      verifyExp: '',
    },
    {
      columnType: 'varchar(80)',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      isDisabled: false,
      field: 'modifier',
      fieldType: null,
      id: '3019427964243161088',

      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,

      label: '修改人',

      placeholder: null,
      seq: 19,
      verifyExp: '',
    },
    {
      columnType: 'bigint',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      isDisabled: false,
      field: 'eid',
      fieldType: null,
      id: '7989769675184011264',

      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,

      label: '企业ID',

      placeholder: null,
      seq: 20,
      verifyExp: '',
    },
    {
      columnType: 'bigint',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      isDisabled: false,
      field: 'oid',
      fieldType: null,
      id: '3195778080208447488',

      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,

      label: '组织ID',

      placeholder: null,
      seq: 21,
      verifyExp: '',
    },
  ],
} as DomainParamButtonSetting;
