export default {
  showFooter: false,
  isSidebarCompact: false,
  showBreadcrumb: false,
  mode: 'light',
  layout: 'mix',
  splitMenu: true,
  sideMode: 'light',
  isFooterAside: false,
  isSidebarFixed: true,
  isHeaderFixed: true,
  isUseTabsRouter: true,
  showHeader: true,
  brandTheme: '#3F5DED',
};
