import { DomainParamVO } from '@/api/main';

export default {
  creator: 'administrator',
  datasourceCategory: 'TABLE',
  datasourceName: 'E_MAINTENANCE_BILL_DTL_SPARE_PART',
  defaultPageCount: null,
  domainCategory: 'EQUIPMENT',
  domainParamCode: 'E_MAINTENANCE_BILL_DTL_SPARE_PART',
  domainParamDesc: null,
  domainParamGroupId: '1813403525457461249',
  domainParamName: '保养单据替换备件',
  domainParamTemplateId: '2',
  domainParmSetting: {
    buttonSetting: [
      {
        actionType: 'form-add',
        apiAction: null,
        buttonCode: 'add',
        buttonName: '新增',
        buttonPosition: 'tableHeader',
        buttonTheme: 'primary',
        customApi: null,
        deleteType: 'logical',
        formColumnSetting: [
          {
            columnType: 'NUMBER(20,0)',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            field: 'E_MAINTENANCE_BILL_DTL_ID',
            fieldType: null,
            id: '8957058909118613504',
            isDisabled: false,
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: true,
            label: null,
            parentField: null,
            placeholder: null,
            seq: 0,
            verifyExp: '',
          },
          {
            columnType: 'NUMBER(20,0)',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            field: 'M_SPARE_PART_ID',
            fieldType: null,
            id: '8619664021908389888',
            isDisabled: false,
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: true,
            label: null,
            parentField: null,
            placeholder: null,
            seq: 1,
            verifyExp: '',
          },
          {
            columnType: 'NUMBER(20,0)',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            field: 'CHANGE_COUNT',
            fieldType: null,
            id: '4262498038675378176',
            isDisabled: false,
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: true,
            label: null,
            parentField: null,
            placeholder: null,
            seq: 2,
            verifyExp: '',
          },
          {
            columnType: 'NUMBER(20,0)',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            field: 'ID',
            fieldType: null,
            id: '7350989963830953984',
            isDisabled: false,
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: false,
            label: null,
            parentField: null,
            placeholder: null,
            seq: 3,
            verifyExp: '',
          },
          {
            columnType: 'DATE',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            field: 'TIME_CREATE',
            fieldType: null,
            id: '950392490399178752',
            isDisabled: false,
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: false,
            label: null,
            parentField: null,
            placeholder: null,
            seq: 4,
            verifyExp: '',
          },
          {
            columnType: 'NVARCHAR2',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            field: 'CREATOR',
            fieldType: null,
            id: '4749370531104987136',
            isDisabled: false,
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: false,
            label: null,
            parentField: null,
            placeholder: null,
            seq: 5,
            verifyExp: '',
          },
          {
            columnType: 'DATE',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            field: 'TIME_MODIFIED',
            fieldType: null,
            id: '8224215575373770752',
            isDisabled: false,
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: false,
            label: null,
            parentField: null,
            placeholder: null,
            seq: 6,
            verifyExp: '',
          },
          {
            columnType: 'NVARCHAR2',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            field: 'MODIFIER',
            fieldType: null,
            id: '651340197885200384',
            isDisabled: false,
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: false,
            label: null,
            parentField: null,
            placeholder: null,
            seq: 7,
            verifyExp: '',
          },
          {
            columnType: 'NUMBER(11,0)',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            field: 'STATE',
            fieldType: null,
            id: '2095394063314100224',
            isDisabled: false,
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: false,
            label: null,
            parentField: null,
            placeholder: null,
            seq: 8,
            verifyExp: '',
          },
          {
            columnType: 'NUMBER(20,0)',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            field: 'EID',
            fieldType: null,
            id: '6430728613550641152',
            isDisabled: false,
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: false,
            label: null,
            parentField: null,
            placeholder: null,
            seq: 9,
            verifyExp: '',
          },
          {
            columnType: 'NUMBER(20,0)',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            field: 'OID',
            fieldType: null,
            id: '7706904012198776832',
            isDisabled: false,
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: false,
            label: null,
            parentField: null,
            placeholder: null,
            seq: 10,
            verifyExp: '',
          },
        ],
        id: null,
        importCode: null,
        isCustomButton: false,
        isEnabled: false,
        jumpLink: null,
        needCheckSelectRow: false,
        seq: 1,
      },
      {
        actionType: 'form-edit',
        apiAction: null,
        buttonCode: 'edit',
        buttonName: '编辑',
        buttonPosition: 'row',
        buttonTheme: 'primary',
        customApi: null,
        deleteType: '',
        formColumnSetting: [
          {
            columnType: 'NUMBER(20,0)',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            field: 'E_MAINTENANCE_BILL_DTL_ID',
            fieldType: null,
            id: '8957058909118613504',
            isDisabled: false,
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: true,
            label: null,
            parentField: null,
            placeholder: null,
            seq: 0,
            verifyExp: '',
          },
          {
            columnType: 'NUMBER(20,0)',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            field: 'M_SPARE_PART_ID',
            fieldType: null,
            id: '8619664021908389888',
            isDisabled: false,
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: true,
            label: null,
            parentField: null,
            placeholder: null,
            seq: 1,
            verifyExp: '',
          },
          {
            columnType: 'NUMBER(20,0)',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            field: 'CHANGE_COUNT',
            fieldType: null,
            id: '4262498038675378176',
            isDisabled: false,
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: true,
            label: null,
            parentField: null,
            placeholder: null,
            seq: 2,
            verifyExp: '',
          },
          {
            columnType: 'NUMBER(20,0)',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            field: 'ID',
            fieldType: null,
            id: '7350989963830953984',
            isDisabled: false,
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: false,
            label: null,
            parentField: null,
            placeholder: null,
            seq: 3,
            verifyExp: '',
          },
          {
            columnType: 'DATE',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            field: 'TIME_CREATE',
            fieldType: null,
            id: '950392490399178752',
            isDisabled: false,
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: false,
            label: null,
            parentField: null,
            placeholder: null,
            seq: 4,
            verifyExp: '',
          },
          {
            columnType: 'NVARCHAR2',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            field: 'CREATOR',
            fieldType: null,
            id: '4749370531104987136',
            isDisabled: false,
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: false,
            label: null,
            parentField: null,
            placeholder: null,
            seq: 5,
            verifyExp: '',
          },
          {
            columnType: 'DATE',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            field: 'TIME_MODIFIED',
            fieldType: null,
            id: '8224215575373770752',
            isDisabled: false,
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: false,
            label: null,
            parentField: null,
            placeholder: null,
            seq: 6,
            verifyExp: '',
          },
          {
            columnType: 'NVARCHAR2',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            field: 'MODIFIER',
            fieldType: null,
            id: '651340197885200384',
            isDisabled: false,
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: false,
            label: null,
            parentField: null,
            placeholder: null,
            seq: 7,
            verifyExp: '',
          },
          {
            columnType: 'NUMBER(11,0)',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            field: 'STATE',
            fieldType: null,
            id: '2095394063314100224',
            isDisabled: false,
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: false,
            label: null,
            parentField: null,
            placeholder: null,
            seq: 8,
            verifyExp: '',
          },
          {
            columnType: 'NUMBER(20,0)',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            field: 'EID',
            fieldType: null,
            id: '6430728613550641152',
            isDisabled: false,
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: false,
            label: null,
            parentField: null,
            placeholder: null,
            seq: 9,
            verifyExp: '',
          },
          {
            columnType: 'NUMBER(20,0)',
            component: 't-input',
            componentParam: '',
            componentSource: null,
            defaultValue: '',
            field: 'OID',
            fieldType: null,
            id: '7706904012198776832',
            isDisabled: false,
            isKeyField: false,
            isMultiple: false,
            isRequired: false,
            isVisible: false,
            label: null,
            parentField: null,
            placeholder: null,
            seq: 10,
            verifyExp: '',
          },
        ],
        id: null,
        importCode: null,
        isCustomButton: false,
        isEnabled: false,
        jumpLink: null,
        needCheckSelectRow: false,
        seq: 2,
      },
      {
        actionType: 'delete',
        apiAction: null,
        buttonCode: 'delete',
        buttonName: '删除',
        buttonPosition: 'row',
        buttonTheme: 'danger',
        customApi: null,
        deleteType: 'logical',
        formColumnSetting: [],
        id: null,
        importCode: null,
        isCustomButton: false,
        isEnabled: false,
        jumpLink: null,
        needCheckSelectRow: true,
        seq: 3,
      },
    ],
    datasourceSetting: [
      {
        aliasName: 'M_SPARE_PART_20240904141629',
        conditionData: [
          {
            aliasName: 'E_MAINTENANCE_BILL_DTL_SPARE_PART',
            fieldName: 'ID',
            operator: 'EQ',
            relateFieldName: 'M_SPARE_PART_ID',
            relateType: 'field',
            relateValue: '',
            seq: 0,
          },
        ],
        datasourceName: 'M_SPARE_PART',
        datasourceType: 'dataTable',
        relatedType: 'LEFT',
        seq: 1,
      },
    ],
    searchSetting: [],
    tableSetting: {
      columnSetting: [
        {
          align: 'center',
          canDelete: false,
          columnDefault: null,
          columnDesc: '备品备件编码',
          columnKey: null,
          columnName: 'SPARE_PART_CODE',
          columnType: 'NVARCHAR2',
          columnWidth: 100,
          componentSource: null,
          id: '6470403408334192640',
          isAutoWidth: true,
          isDataDefault: false,
          isDatabaseField: false,
          isHandAdd: true,
          isLeftFixed: false,
          isRightFixed: false,
          isVisible: true,
          nullable: null,
          seq: 1,
          tableName: 'M_SPARE_PART_20240904141629',
        },
        {
          align: 'center',
          canDelete: false,
          columnDefault: null,
          columnDesc: '备品备件名称',
          columnKey: null,
          columnName: 'SPARE_PART_NAME',
          columnType: 'NVARCHAR2',
          columnWidth: 100,
          componentSource: null,
          id: '433576897079629824',
          isAutoWidth: true,
          isDataDefault: false,
          isDatabaseField: false,
          isHandAdd: true,
          isLeftFixed: false,
          isRightFixed: false,
          isVisible: true,
          nullable: null,
          seq: 2,
          tableName: 'M_SPARE_PART_20240904141629',
        },
        {
          align: 'center',
          canDelete: false,
          columnDefault: null,
          columnDesc: null,
          columnKey: null,
          columnName: 'E_MAINTENANCE_BILL_DTL_ID',
          columnType: 'NUMBER(20,0)',
          columnWidth: 100,
          componentSource: null,
          id: '8957058909118613504',
          isAutoWidth: true,
          isDataDefault: false,
          isDatabaseField: true,
          isHandAdd: false,
          isLeftFixed: false,
          isRightFixed: false,
          isVisible: false,
          nullable: 'NO',
          seq: 3,
          tableName: 'E_MAINTENANCE_BILL_DTL_SPARE_PART',
        },
        {
          align: 'center',
          canDelete: false,
          columnDefault: null,
          columnDesc: null,
          columnKey: null,
          columnName: 'M_SPARE_PART_ID',
          columnType: 'NUMBER(20,0)',
          columnWidth: 100,
          componentSource: null,
          id: '8619664021908389888',
          isAutoWidth: true,
          isDataDefault: false,
          isDatabaseField: true,
          isHandAdd: false,
          isLeftFixed: false,
          isRightFixed: false,
          isVisible: false,
          nullable: 'NO',
          seq: 4,
          tableName: 'E_MAINTENANCE_BILL_DTL_SPARE_PART',
        },
        {
          align: 'center',
          canDelete: false,
          columnDefault: null,
          columnDesc: '更换数量',
          columnKey: null,
          columnName: 'CHANGE_COUNT',
          columnType: 'NUMBER(20,0)',
          columnWidth: 100,
          componentSource: null,
          id: '4262498038675378176',
          isAutoWidth: true,
          isDataDefault: false,
          isDatabaseField: true,
          isHandAdd: false,
          isLeftFixed: false,
          isRightFixed: false,
          isVisible: true,
          nullable: 'NO',
          seq: 5,
          tableName: 'E_MAINTENANCE_BILL_DTL_SPARE_PART',
        },
        {
          align: 'center',
          canDelete: false,
          columnDefault: null,
          columnDesc: '单位',
          columnKey: null,
          columnName: 'UOM',
          columnType: 'NVARCHAR2',
          columnWidth: 100,
          componentSource: null,
          id: '1219279910206046208',
          isAutoWidth: true,
          isDataDefault: false,
          isDatabaseField: false,
          isHandAdd: true,
          isLeftFixed: false,
          isRightFixed: false,
          isVisible: true,
          nullable: null,
          seq: 6,
          tableName: 'M_SPARE_PART_20240904141629',
        },
        {
          align: 'center',
          canDelete: false,
          columnDefault: null,
          columnDesc: null,
          columnKey: null,
          columnName: 'ID',
          columnType: 'NUMBER(20,0)',
          columnWidth: 100,
          componentSource: null,
          id: '7350989963830953984',
          isAutoWidth: true,
          isDataDefault: true,
          isDatabaseField: true,
          isHandAdd: false,
          isLeftFixed: false,
          isRightFixed: false,
          isVisible: false,
          nullable: 'NO',
          seq: 7,
          tableName: 'E_MAINTENANCE_BILL_DTL_SPARE_PART',
        },
        {
          align: 'center',
          canDelete: false,
          columnDefault: null,
          columnDesc: null,
          columnKey: null,
          columnName: 'TIME_CREATE',
          columnType: 'DATE',
          columnWidth: 100,
          componentSource: null,
          id: '950392490399178752',
          isAutoWidth: true,
          isDataDefault: true,
          isDatabaseField: true,
          isHandAdd: false,
          isLeftFixed: false,
          isRightFixed: false,
          isVisible: false,
          nullable: 'NO',
          seq: 8,
          tableName: 'E_MAINTENANCE_BILL_DTL_SPARE_PART',
        },
        {
          align: 'center',
          canDelete: false,
          columnDefault: null,
          columnDesc: null,
          columnKey: null,
          columnName: 'CREATOR',
          columnType: 'NVARCHAR2',
          columnWidth: 100,
          componentSource: null,
          id: '4749370531104987136',
          isAutoWidth: true,
          isDataDefault: true,
          isDatabaseField: true,
          isHandAdd: false,
          isLeftFixed: false,
          isRightFixed: false,
          isVisible: false,
          nullable: 'NO',
          seq: 9,
          tableName: 'E_MAINTENANCE_BILL_DTL_SPARE_PART',
        },
        {
          align: 'center',
          canDelete: false,
          columnDefault: null,
          columnDesc: null,
          columnKey: null,
          columnName: 'TIME_MODIFIED',
          columnType: 'DATE',
          columnWidth: 100,
          componentSource: null,
          id: '8224215575373770752',
          isAutoWidth: true,
          isDataDefault: true,
          isDatabaseField: true,
          isHandAdd: false,
          isLeftFixed: false,
          isRightFixed: false,
          isVisible: false,
          nullable: 'YES',
          seq: 10,
          tableName: 'E_MAINTENANCE_BILL_DTL_SPARE_PART',
        },
        {
          align: 'center',
          canDelete: false,
          columnDefault: null,
          columnDesc: null,
          columnKey: null,
          columnName: 'MODIFIER',
          columnType: 'NVARCHAR2',
          columnWidth: 100,
          componentSource: null,
          id: '651340197885200384',
          isAutoWidth: true,
          isDataDefault: true,
          isDatabaseField: true,
          isHandAdd: false,
          isLeftFixed: false,
          isRightFixed: false,
          isVisible: false,
          nullable: 'YES',
          seq: 11,
          tableName: 'E_MAINTENANCE_BILL_DTL_SPARE_PART',
        },
        {
          align: 'center',
          canDelete: false,
          columnDefault: null,
          columnDesc: null,
          columnKey: null,
          columnName: 'STATE',
          columnType: 'NUMBER(11,0)',
          columnWidth: 100,
          componentSource: null,
          id: '2095394063314100224',
          isAutoWidth: true,
          isDataDefault: true,
          isDatabaseField: true,
          isHandAdd: false,
          isLeftFixed: false,
          isRightFixed: false,
          isVisible: false,
          nullable: 'NO',
          seq: 12,
          tableName: 'E_MAINTENANCE_BILL_DTL_SPARE_PART',
        },
        {
          align: 'center',
          canDelete: false,
          columnDefault: null,
          columnDesc: null,
          columnKey: null,
          columnName: 'EID',
          columnType: 'NUMBER(20,0)',
          columnWidth: 100,
          componentSource: null,
          id: '6430728613550641152',
          isAutoWidth: true,
          isDataDefault: true,
          isDatabaseField: true,
          isHandAdd: false,
          isLeftFixed: false,
          isRightFixed: false,
          isVisible: false,
          nullable: 'NO',
          seq: 13,
          tableName: 'E_MAINTENANCE_BILL_DTL_SPARE_PART',
        },
        {
          align: 'center',
          canDelete: false,
          columnDefault: null,
          columnDesc: null,
          columnKey: null,
          columnName: 'OID',
          columnType: 'NUMBER(20,0)',
          columnWidth: 100,
          componentSource: null,
          id: '7706904012198776832',
          isAutoWidth: true,
          isDataDefault: true,
          isDatabaseField: true,
          isHandAdd: false,
          isLeftFixed: false,
          isRightFixed: false,
          isVisible: false,
          nullable: 'NO',
          seq: 14,
          tableName: 'E_MAINTENANCE_BILL_DTL_SPARE_PART',
        },
      ],
      isAutoLoad: true,
      pageSize: null,
      sortField: 'time_create',
      sortType: 'desc',
      tableTitle: '备品备件更换列表',
      usePage: false,
    },
  },
  eid: '1',
  exportFileName: null,
  exportLimitCount: null,
  groupCode: 'EQUIPMENT',
  groupName: '设备模块',
  id: '1831215223807512578',
  importFileName: null,
  isCustomerSql: null,
  isDebug: null,
  jsonContent:
    '{"buttonSetting":[{"actionType":"form-add","buttonCode":"add","buttonName":"新增","buttonPosition":"tableHeader","buttonTheme":"primary","deleteType":"logical","formColumnSetting":[{"columnType":"NUMBER(20,0)","component":"t-input","componentParam":"","defaultValue":"","field":"E_MAINTENANCE_BILL_DTL_ID","id":"8957058909118613504","isDisabled":false,"isKeyField":false,"isMultiple":false,"isRequired":false,"isVisible":true,"seq":0,"verifyExp":""},{"columnType":"NUMBER(20,0)","component":"t-input","componentParam":"","defaultValue":"","field":"M_SPARE_PART_ID","id":"8619664021908389888","isDisabled":false,"isKeyField":false,"isMultiple":false,"isRequired":false,"isVisible":true,"seq":1,"verifyExp":""},{"columnType":"NUMBER(20,0)","component":"t-input","componentParam":"","defaultValue":"","field":"CHANGE_COUNT","id":"4262498038675378176","isDisabled":false,"isKeyField":false,"isMultiple":false,"isRequired":false,"isVisible":true,"seq":2,"verifyExp":""},{"columnType":"NUMBER(20,0)","component":"t-input","componentParam":"","defaultValue":"","field":"ID","id":"7350989963830953984","isDisabled":false,"isKeyField":false,"isMultiple":false,"isRequired":false,"isVisible":false,"seq":3,"verifyExp":""},{"columnType":"DATE","component":"t-input","componentParam":"","defaultValue":"","field":"TIME_CREATE","id":"950392490399178752","isDisabled":false,"isKeyField":false,"isMultiple":false,"isRequired":false,"isVisible":false,"seq":4,"verifyExp":""},{"columnType":"NVARCHAR2","component":"t-input","componentParam":"","defaultValue":"","field":"CREATOR","id":"4749370531104987136","isDisabled":false,"isKeyField":false,"isMultiple":false,"isRequired":false,"isVisible":false,"seq":5,"verifyExp":""},{"columnType":"DATE","component":"t-input","componentParam":"","defaultValue":"","field":"TIME_MODIFIED","id":"8224215575373770752","isDisabled":false,"isKeyField":false,"isMultiple":false,"isRequired":false,"isVisible":false,"seq":6,"verifyExp":""},{"columnType":"NVARCHAR2","component":"t-input","componentParam":"","defaultValue":"","field":"MODIFIER","id":"651340197885200384","isDisabled":false,"isKeyField":false,"isMultiple":false,"isRequired":false,"isVisible":false,"seq":7,"verifyExp":""},{"columnType":"NUMBER(11,0)","component":"t-input","componentParam":"","defaultValue":"","field":"STATE","id":"2095394063314100224","isDisabled":false,"isKeyField":false,"isMultiple":false,"isRequired":false,"isVisible":false,"seq":8,"verifyExp":""},{"columnType":"NUMBER(20,0)","component":"t-input","componentParam":"","defaultValue":"","field":"EID","id":"6430728613550641152","isDisabled":false,"isKeyField":false,"isMultiple":false,"isRequired":false,"isVisible":false,"seq":9,"verifyExp":""},{"columnType":"NUMBER(20,0)","component":"t-input","componentParam":"","defaultValue":"","field":"OID","id":"7706904012198776832","isDisabled":false,"isKeyField":false,"isMultiple":false,"isRequired":false,"isVisible":false,"seq":10,"verifyExp":""}],"isCustomButton":false,"isEnabled":false,"needCheckSelectRow":false,"seq":1},{"actionType":"form-edit","buttonCode":"edit","buttonName":"编辑","buttonPosition":"row","buttonTheme":"primary","deleteType":"","formColumnSetting":[{"columnType":"NUMBER(20,0)","component":"t-input","componentParam":"","defaultValue":"","field":"E_MAINTENANCE_BILL_DTL_ID","id":"8957058909118613504","isDisabled":false,"isKeyField":false,"isMultiple":false,"isRequired":false,"isVisible":true,"seq":0,"verifyExp":""},{"columnType":"NUMBER(20,0)","component":"t-input","componentParam":"","defaultValue":"","field":"M_SPARE_PART_ID","id":"8619664021908389888","isDisabled":false,"isKeyField":false,"isMultiple":false,"isRequired":false,"isVisible":true,"seq":1,"verifyExp":""},{"columnType":"NUMBER(20,0)","component":"t-input","componentParam":"","defaultValue":"","field":"CHANGE_COUNT","id":"4262498038675378176","isDisabled":false,"isKeyField":false,"isMultiple":false,"isRequired":false,"isVisible":true,"seq":2,"verifyExp":""},{"columnType":"NUMBER(20,0)","component":"t-input","componentParam":"","defaultValue":"","field":"ID","id":"7350989963830953984","isDisabled":false,"isKeyField":false,"isMultiple":false,"isRequired":false,"isVisible":false,"seq":3,"verifyExp":""},{"columnType":"DATE","component":"t-input","componentParam":"","defaultValue":"","field":"TIME_CREATE","id":"950392490399178752","isDisabled":false,"isKeyField":false,"isMultiple":false,"isRequired":false,"isVisible":false,"seq":4,"verifyExp":""},{"columnType":"NVARCHAR2","component":"t-input","componentParam":"","defaultValue":"","field":"CREATOR","id":"4749370531104987136","isDisabled":false,"isKeyField":false,"isMultiple":false,"isRequired":false,"isVisible":false,"seq":5,"verifyExp":""},{"columnType":"DATE","component":"t-input","componentParam":"","defaultValue":"","field":"TIME_MODIFIED","id":"8224215575373770752","isDisabled":false,"isKeyField":false,"isMultiple":false,"isRequired":false,"isVisible":false,"seq":6,"verifyExp":""},{"columnType":"NVARCHAR2","component":"t-input","componentParam":"","defaultValue":"","field":"MODIFIER","id":"651340197885200384","isDisabled":false,"isKeyField":false,"isMultiple":false,"isRequired":false,"isVisible":false,"seq":7,"verifyExp":""},{"columnType":"NUMBER(11,0)","component":"t-input","componentParam":"","defaultValue":"","field":"STATE","id":"2095394063314100224","isDisabled":false,"isKeyField":false,"isMultiple":false,"isRequired":false,"isVisible":false,"seq":8,"verifyExp":""},{"columnType":"NUMBER(20,0)","component":"t-input","componentParam":"","defaultValue":"","field":"EID","id":"6430728613550641152","isDisabled":false,"isKeyField":false,"isMultiple":false,"isRequired":false,"isVisible":false,"seq":9,"verifyExp":""},{"columnType":"NUMBER(20,0)","component":"t-input","componentParam":"","defaultValue":"","field":"OID","id":"7706904012198776832","isDisabled":false,"isKeyField":false,"isMultiple":false,"isRequired":false,"isVisible":false,"seq":10,"verifyExp":""}],"isCustomButton":false,"isEnabled":false,"needCheckSelectRow":false,"seq":2},{"actionType":"delete","buttonCode":"delete","buttonName":"删除","buttonPosition":"row","buttonTheme":"danger","deleteType":"logical","formColumnSetting":[],"isCustomButton":false,"isEnabled":false,"needCheckSelectRow":true,"seq":3}],"datasourceSetting":[{"aliasName":"M_SPARE_PART_20240904141629","conditionData":[{"aliasName":"E_MAINTENANCE_BILL_DTL_SPARE_PART","fieldName":"ID","operator":"EQ","relateFieldName":"M_SPARE_PART_ID","relateType":"field","relateValue":"","seq":0}],"datasourceName":"M_SPARE_PART","datasourceType":"dataTable","relatedType":"LEFT","seq":1}],"searchSetting":[],"tableSetting":{"columnSetting":[{"align":"center","columnDesc":"备品备件编码","columnName":"SPARE_PART_CODE","columnType":"NVARCHAR2","columnWidth":100,"id":"6470403408334192640","isAutoWidth":true,"isHandAdd":true,"isLeftFixed":false,"isRightFixed":false,"isVisible":true,"seq":1,"tableName":"M_SPARE_PART_20240904141629"},{"align":"center","columnDesc":"备品备件名称","columnName":"SPARE_PART_NAME","columnType":"NVARCHAR2","columnWidth":100,"id":"433576897079629824","isAutoWidth":true,"isHandAdd":true,"isLeftFixed":false,"isRightFixed":false,"isVisible":true,"seq":2,"tableName":"M_SPARE_PART_20240904141629"},{"align":"center","canDelete":false,"columnName":"E_MAINTENANCE_BILL_DTL_ID","columnType":"NUMBER(20,0)","columnWidth":100,"id":"8957058909118613504","isAutoWidth":true,"isDataDefault":false,"isDatabaseField":true,"isHandAdd":false,"isLeftFixed":false,"isRightFixed":false,"isVisible":false,"nullable":"NO","seq":3,"tableName":"E_MAINTENANCE_BILL_DTL_SPARE_PART"},{"align":"center","canDelete":false,"columnName":"M_SPARE_PART_ID","columnType":"NUMBER(20,0)","columnWidth":100,"id":"8619664021908389888","isAutoWidth":true,"isDataDefault":false,"isDatabaseField":true,"isHandAdd":false,"isLeftFixed":false,"isRightFixed":false,"isVisible":false,"nullable":"NO","seq":4,"tableName":"E_MAINTENANCE_BILL_DTL_SPARE_PART"},{"align":"center","canDelete":false,"columnDesc":"更换数量","columnName":"CHANGE_COUNT","columnType":"NUMBER(20,0)","columnWidth":100,"id":"4262498038675378176","isAutoWidth":true,"isDataDefault":false,"isDatabaseField":true,"isHandAdd":false,"isLeftFixed":false,"isRightFixed":false,"isVisible":true,"nullable":"NO","seq":5,"tableName":"E_MAINTENANCE_BILL_DTL_SPARE_PART"},{"align":"center","columnDesc":"单位","columnName":"UOM","columnType":"NVARCHAR2","columnWidth":100,"id":"1219279910206046208","isAutoWidth":true,"isHandAdd":true,"isLeftFixed":false,"isRightFixed":false,"isVisible":true,"seq":6,"tableName":"M_SPARE_PART_20240904141629"},{"align":"center","canDelete":false,"columnName":"ID","columnType":"NUMBER(20,0)","columnWidth":100,"id":"7350989963830953984","isAutoWidth":true,"isDataDefault":true,"isDatabaseField":true,"isHandAdd":false,"isLeftFixed":false,"isRightFixed":false,"isVisible":false,"nullable":"NO","seq":7,"tableName":"E_MAINTENANCE_BILL_DTL_SPARE_PART"},{"align":"center","canDelete":false,"columnName":"TIME_CREATE","columnType":"DATE","columnWidth":100,"id":"950392490399178752","isAutoWidth":true,"isDataDefault":true,"isDatabaseField":true,"isHandAdd":false,"isLeftFixed":false,"isRightFixed":false,"isVisible":false,"nullable":"NO","seq":8,"tableName":"E_MAINTENANCE_BILL_DTL_SPARE_PART"},{"align":"center","canDelete":false,"columnName":"CREATOR","columnType":"NVARCHAR2","columnWidth":100,"id":"4749370531104987136","isAutoWidth":true,"isDataDefault":true,"isDatabaseField":true,"isHandAdd":false,"isLeftFixed":false,"isRightFixed":false,"isVisible":false,"nullable":"NO","seq":9,"tableName":"E_MAINTENANCE_BILL_DTL_SPARE_PART"},{"align":"center","canDelete":false,"columnName":"TIME_MODIFIED","columnType":"DATE","columnWidth":100,"id":"8224215575373770752","isAutoWidth":true,"isDataDefault":true,"isDatabaseField":true,"isHandAdd":false,"isLeftFixed":false,"isRightFixed":false,"isVisible":false,"nullable":"YES","seq":10,"tableName":"E_MAINTENANCE_BILL_DTL_SPARE_PART"},{"align":"center","canDelete":false,"columnName":"MODIFIER","columnType":"NVARCHAR2","columnWidth":100,"id":"651340197885200384","isAutoWidth":true,"isDataDefault":true,"isDatabaseField":true,"isHandAdd":false,"isLeftFixed":false,"isRightFixed":false,"isVisible":false,"nullable":"YES","seq":11,"tableName":"E_MAINTENANCE_BILL_DTL_SPARE_PART"},{"align":"center","canDelete":false,"columnName":"STATE","columnType":"NUMBER(11,0)","columnWidth":100,"id":"2095394063314100224","isAutoWidth":true,"isDataDefault":true,"isDatabaseField":true,"isHandAdd":false,"isLeftFixed":false,"isRightFixed":false,"isVisible":false,"nullable":"NO","seq":12,"tableName":"E_MAINTENANCE_BILL_DTL_SPARE_PART"},{"align":"center","canDelete":false,"columnName":"EID","columnType":"NUMBER(20,0)","columnWidth":100,"id":"6430728613550641152","isAutoWidth":true,"isDataDefault":true,"isDatabaseField":true,"isHandAdd":false,"isLeftFixed":false,"isRightFixed":false,"isVisible":false,"nullable":"NO","seq":13,"tableName":"E_MAINTENANCE_BILL_DTL_SPARE_PART"},{"align":"center","canDelete":false,"columnName":"OID","columnType":"NUMBER(20,0)","columnWidth":100,"id":"7706904012198776832","isAutoWidth":true,"isDataDefault":true,"isDatabaseField":true,"isHandAdd":false,"isLeftFixed":false,"isRightFixed":false,"isVisible":false,"nullable":"NO","seq":14,"tableName":"E_MAINTENANCE_BILL_DTL_SPARE_PART"}],"isAutoLoad":true,"sortField":"time_create","sortType":"desc","tableTitle":"备品备件更换列表","usePage":true}}',
  modifier: 'administrator',
  operateColumnWidth: null,
  queryApi: null,
  seqColumnWidth: null,
  sqlContent: null,
  state: 1,
  templateCode: 'singleTableManage',
  templateName: '数据维护模板',
  templateUrl: '/main#/singleTableManage',
  timeCreate: '2024-09-04 14:18:26',
  timeModified: '2024-09-04 14:18:26',
  validateApi: null,
} as DomainParamVO;
