import { DomainParamButtonSetting } from '@/api/main';

export default {
  formColumnSetting: [
    {
      columnType: 'varchar(80)',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      isDisabled: true,
      field: 'maintenance_item_code',
      fieldType: null,
      id: '8417007597286948864',
      isKeyField: true,
      isMultiple: false,
      isRequired: true,
      isVisible: true,
      label: '保养项目代码',
      placeholder: null,
      seq: 0,
      verifyExp: '',
    },
    {
      columnType: 'varchar(240)',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      isDisabled: false,
      field: 'maintenance_item_name',
      fieldType: null,
      id: '8079140693322721280',
      isKeyField: false,
      isMultiple: false,
      isRequired: true,
      isVisible: true,
      label: '保养项目名称',
      placeholder: null,
      seq: 1,
      verifyExp: '',
    },
    {
      columnType: 'varchar(2000)',
      component: 't-textarea',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      isDisabled: false,
      field: 'maintenance_item_require',
      fieldType: null,
      id: '3663260946553165824',
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: true,
      label: '保养项目要求',
      placeholder: null,
      seq: 2,
      verifyExp: '',
    },
    {
      columnType: 'varchar(80)',
      component: 'bcmp-select-param',
      componentParam: 'E_MAINTENANCE_PERIOD',
      componentSource: null,
      defaultValue: '',
      isDisabled: false,
      field: 'maintenance_period',
      fieldType: null,
      id: '5811999930571229184',
      isKeyField: false,
      isMultiple: false,
      isRequired: true,
      isVisible: true,
      label: '保养周期',
      placeholder: null,
      seq: 3,
      verifyExp: '',
    },
    {
      columnType: 'int',
      component: 't-switch',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      isDisabled: false,
      field: 'is_photo',
      fieldType: null,
      id: '2869657777317466112',
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: true,
      label: '是否拍照',
      placeholder: null,
      seq: 4,
      verifyExp: '',
    },
    {
      columnType: 'bigint',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      isDisabled: false,
      field: 'id',
      fieldType: null,
      id: '5563683092518062080',
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,
      label: '',
      placeholder: null,
      seq: 5,
      verifyExp: '',
    },
    {
      columnType: 'datetime(4)',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      isDisabled: false,
      field: 'time_create',
      fieldType: null,
      id: '2743210957659762688',
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,
      label: '创建时间',
      placeholder: null,
      seq: 6,
      verifyExp: '',
    },
    {
      columnType: 'varchar(80)',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      isDisabled: false,
      field: 'creator',
      fieldType: null,
      id: '4122982392095916032',
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,
      label: '创建人',
      placeholder: null,
      seq: 7,
      verifyExp: '',
    },
    {
      columnType: 'datetime(4)',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      isDisabled: false,
      field: 'time_modified',
      fieldType: null,
      id: '6656486853401825280',
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,
      label: '修改时间',
      placeholder: null,
      seq: 8,
      verifyExp: '',
    },
    {
      columnType: 'varchar(80)',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      isDisabled: false,
      field: 'modifier',
      fieldType: null,
      id: '8625720559212785664',
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,
      label: '修改人',
      placeholder: null,
      seq: 9,
      verifyExp: '',
    },
    {
      columnType: 'int',
      component: 't-switch',
      componentParam: '',
      componentSource: null,
      defaultValue: '1',
      isDisabled: false,
      field: 'state',
      fieldType: null,
      id: '873288551683076096',
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: true,
      label: '状态',
      placeholder: null,
      seq: 10,
      verifyExp: '',
    },
    {
      columnType: 'bigint',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      isDisabled: false,
      field: 'eid',
      fieldType: null,
      id: '5456451110613661696',
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,
      label: '企业ID',
      placeholder: null,
      seq: 11,
      verifyExp: '',
    },
    {
      columnType: 'bigint',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      isDisabled: false,
      field: 'oid',
      fieldType: null,
      id: '6283658517596313600',
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,
      label: '组织ID',
      placeholder: null,
      seq: 12,
      verifyExp: '',
    },
  ],
} as DomainParamButtonSetting;
