import { DomainParamSetting } from '@/api/main';

export default {
  tableSetting: {
    columnSetting: [
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '资产类型编码',
        columnKey: null,
        columnName: 'ASSET_TYPE_CODE',
        columnType: 'NVARCHAR2',
        columnWidth: 100,
        componentSource: null,
        id: '7037998728618158080',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: false,
        isHandAdd: true,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: true,
        nullable: null,
        seq: 1,
        tableName: 'M_ASSET_TYPE_20240828145508',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '资产类型名称',
        columnKey: null,
        columnName: 'ASSET_TYPE_NAME',
        columnType: 'NVARCHAR2',
        columnWidth: 100,
        componentSource: null,
        id: '2983723205979693056',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: false,
        isHandAdd: true,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: true,
        nullable: null,
        seq: 2,
        tableName: 'M_ASSET_TYPE_20240828145508',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '资产品牌编码',
        columnKey: null,
        columnName: 'ASSET_BRAND_CODE',
        columnType: 'NVARCHAR2',
        columnWidth: 100,
        componentSource: null,
        id: '1538810208039622656',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: false,
        isHandAdd: true,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: true,
        nullable: null,
        seq: 3,
        tableName: 'M_ASSET_BRAND_20240828145402',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '资产品牌名称',
        columnKey: null,
        columnName: 'ASSET_BRAND_NAME',
        columnType: 'NVARCHAR2',
        columnWidth: 100,
        componentSource: null,
        id: '6176421713554049024',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: false,
        isHandAdd: true,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: true,
        nullable: null,
        seq: 4,
        tableName: 'M_ASSET_BRAND_20240828145402',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '资产型号编码',
        columnKey: null,
        columnName: 'ASSET_MODEL_CODE',
        columnType: 'NVARCHAR2',
        columnWidth: 100,
        componentSource: null,
        id: '5338476492874725376',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: false,
        isHandAdd: true,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: true,
        nullable: null,
        seq: 5,
        tableName: 'M_ASSET_MODEL_20240828145439',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '资产型号名称',
        columnKey: null,
        columnName: 'ASSET_MODEL_NAME',
        columnType: 'NVARCHAR2',
        columnWidth: 100,
        componentSource: null,
        id: '5657625738609903616',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: false,
        isHandAdd: true,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: true,
        nullable: null,
        seq: 6,
        tableName: 'M_ASSET_MODEL_20240828145439',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '设备保养项目表ID',
        columnKey: null,
        columnName: 'E_MAINTENANCE_ITEM_ID',
        columnType: 'NUMBER(20,0)',
        columnWidth: 100,
        componentSource: null,
        id: '6795321485102522368',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'NO',
        seq: 7,
        tableName: 'E_MAINTENANCE_ITEM_IN_EQUIPMENT',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '资产类型表ID',
        columnKey: null,
        columnName: 'M_ASSET_TYPE_ID',
        columnType: 'NUMBER(20,0)',
        columnWidth: 100,
        componentSource: null,
        id: '5916775084813522944',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'YES',
        seq: 8,
        tableName: 'E_MAINTENANCE_ITEM_IN_EQUIPMENT',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '资产品牌表ID',
        columnKey: null,
        columnName: 'M_ASSET_BRAND_ID',
        columnType: 'NUMBER(20,0)',
        columnWidth: 100,
        componentSource: null,
        id: '8825791702691502080',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'YES',
        seq: 9,
        tableName: 'E_MAINTENANCE_ITEM_IN_EQUIPMENT',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '资产型号表ID',
        columnKey: null,
        columnName: 'M_ASSET_MODEL_ID',
        columnType: 'NUMBER(20,0)',
        columnWidth: 100,
        componentSource: null,
        id: '8751052224931405824',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'YES',
        seq: 10,
        tableName: 'E_MAINTENANCE_ITEM_IN_EQUIPMENT',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '模具类型',
        columnKey: null,
        columnName: 'MOULD_TYPE',
        columnType: 'NVARCHAR2',
        columnWidth: 100,
        componentSource: null,
        id: '5374676252176072704',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'YES',
        seq: 11,
        tableName: 'E_MAINTENANCE_ITEM_IN_EQUIPMENT',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '模具表ID',
        columnKey: null,
        columnName: 'M_MOULD_ID',
        columnType: 'NUMBER(20,0)',
        columnWidth: 100,
        componentSource: null,
        id: '8733233485768067072',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'YES',
        seq: 12,
        tableName: 'E_MAINTENANCE_ITEM_IN_EQUIPMENT',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: null,
        columnKey: null,
        columnName: 'ID',
        columnType: 'NUMBER(20,0)',
        columnWidth: 100,
        componentSource: null,
        id: '4749953190586585088',
        isAutoWidth: true,
        isDataDefault: true,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'NO',
        seq: 13,
        tableName: 'E_MAINTENANCE_ITEM_IN_EQUIPMENT',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '创建时间',
        columnKey: null,
        columnName: 'TIME_CREATE',
        columnType: 'DATE',
        columnWidth: 100,
        componentSource: null,
        id: '2065963187329300480',
        isAutoWidth: true,
        isDataDefault: true,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'NO',
        seq: 14,
        tableName: 'E_MAINTENANCE_ITEM_IN_EQUIPMENT',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '创建人',
        columnKey: null,
        columnName: 'CREATOR',
        columnType: 'NVARCHAR2',
        columnWidth: 100,
        componentSource: null,
        id: '9194313343352201216',
        isAutoWidth: true,
        isDataDefault: true,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'NO',
        seq: 15,
        tableName: 'E_MAINTENANCE_ITEM_IN_EQUIPMENT',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '修改时间',
        columnKey: null,
        columnName: 'TIME_MODIFIED',
        columnType: 'DATE',
        columnWidth: 100,
        componentSource: null,
        id: '3829484290303326208',
        isAutoWidth: true,
        isDataDefault: true,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'YES',
        seq: 16,
        tableName: 'E_MAINTENANCE_ITEM_IN_EQUIPMENT',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '修改人',
        columnKey: null,
        columnName: 'MODIFIER',
        columnType: 'NVARCHAR2',
        columnWidth: 100,
        componentSource: null,
        id: '5658543170192760832',
        isAutoWidth: true,
        isDataDefault: true,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'YES',
        seq: 17,
        tableName: 'E_MAINTENANCE_ITEM_IN_EQUIPMENT',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '1可用；0禁用',
        columnKey: null,
        columnName: 'STATE',
        columnType: 'NUMBER(11,0)',
        columnWidth: 100,
        componentSource: null,
        id: '4684232299334737920',
        isAutoWidth: true,
        isDataDefault: true,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'NO',
        seq: 18,
        tableName: 'E_MAINTENANCE_ITEM_IN_EQUIPMENT',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '企业ID',
        columnKey: null,
        columnName: 'EID',
        columnType: 'NUMBER(20,0)',
        columnWidth: 100,
        componentSource: null,
        id: '586223381686730752',
        isAutoWidth: true,
        isDataDefault: true,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'NO',
        seq: 19,
        tableName: 'E_MAINTENANCE_ITEM_IN_EQUIPMENT',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '组织ID',
        columnKey: null,
        columnName: 'OID',
        columnType: 'NUMBER(20,0)',
        columnWidth: 100,
        componentSource: null,
        id: '2879034766054287360',
        isAutoWidth: true,
        isDataDefault: true,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'NO',
        seq: 20,
        tableName: 'E_MAINTENANCE_ITEM_IN_EQUIPMENT',
      },
    ],
    pageSize: null,
    sortField: 'time_create',
    sortType: 'desc',
    tableTitle: '设备与保养项目关系表',
    usePage: true,
  },
} as DomainParamSetting;
