import { DomainParamButtonSetting } from '@/api/main';

export default {
  formColumnSetting: [
    {
      columnType: 'NUMBER(20,0)',
      component: 'bcmp-select-business',
      componentParam: 'maintenanceItem',
      componentSource: null,
      defaultValue: '',
      field: 'E_MAINTENANCE_ITEM_ID',
      fieldType: null,
      id: '6795321485102522368',
      isDisabled: false,
      isKeyField: false,
      isMultiple: false,
      isRequired: true,
      isVisible: true,
      label: '保养项目',
      parentField: null,
      placeholder: null,
      seq: 0,
      verifyExp: '',
    },
    {
      columnType: 'NUMBER(20,0)',
      component: 'bcmp-select-business',
      componentParam: 'assetType',
      componentSource: null,
      defaultValue: '',
      field: 'M_ASSET_TYPE_ID',
      fieldType: null,
      id: '5916775084813522944',
      isDisabled: false,
      isKeyField: false,
      isMultiple: false,
      isRequired: true,
      isVisible: true,
      label: '资产类型',
      parentField: null,
      placeholder: null,
      seq: 1,
      verifyExp: '',
    },
    {
      columnType: 'NUMBER(20,0)',
      component: 'bcmp-select-business',
      componentParam: 'assetBrand',
      componentSource: null,
      defaultValue: '',
      field: 'M_ASSET_BRAND_ID',
      fieldType: null,
      id: '8825791702691502080',
      isDisabled: false,
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,
      label: '资产品牌',
      parentField: 'M_ASSET_TYPE_ID',
      placeholder: null,
      seq: 2,
      verifyExp: '',
    },
    {
      columnType: 'NUMBER(20,0)',
      component: 'bcmp-select-business',
      componentParam: 'assetModel',
      componentSource: null,
      defaultValue: '',
      field: 'M_ASSET_MODEL_ID',
      fieldType: null,
      id: '8751052224931405824',
      isDisabled: false,
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,
      label: '资产型号',
      parentField: 'M_ASSET_BRAND_ID',
      placeholder: null,
      seq: 3,
      verifyExp: '',
    },
    {
      columnType: 'NVARCHAR2',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      field: 'MOULD_TYPE',
      fieldType: null,
      id: '5374676252176072704',
      isDisabled: false,
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,
      label: '模具类型',
      parentField: null,
      placeholder: null,
      seq: 4,
      verifyExp: '',
    },
    {
      columnType: 'NUMBER(20,0)',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      field: 'M_MOULD_ID',
      fieldType: null,
      id: '8733233485768067072',
      isDisabled: false,
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,
      label: '模具表ID',
      parentField: null,
      placeholder: null,
      seq: 5,
      verifyExp: '',
    },
    {
      columnType: 'NUMBER(20,0)',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      field: 'ID',
      fieldType: null,
      id: '4749953190586585088',
      isDisabled: false,
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,
      label: null,
      parentField: null,
      placeholder: null,
      seq: 6,
      verifyExp: '',
    },
    {
      columnType: 'DATE',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      field: 'TIME_CREATE',
      fieldType: null,
      id: '2065963187329300480',
      isDisabled: false,
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,
      label: '创建时间',
      parentField: null,
      placeholder: null,
      seq: 7,
      verifyExp: '',
    },
    {
      columnType: 'NVARCHAR2',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      field: 'CREATOR',
      fieldType: null,
      id: '9194313343352201216',
      isDisabled: false,
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,
      label: '创建人',
      parentField: null,
      placeholder: null,
      seq: 8,
      verifyExp: '',
    },
    {
      columnType: 'DATE',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      field: 'TIME_MODIFIED',
      fieldType: null,
      id: '3829484290303326208',
      isDisabled: false,
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,
      label: '修改时间',
      parentField: null,
      placeholder: null,
      seq: 9,
      verifyExp: '',
    },
    {
      columnType: 'NVARCHAR2',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      field: 'MODIFIER',
      fieldType: null,
      id: '5658543170192760832',
      isDisabled: false,
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,
      label: '修改人',
      parentField: null,
      placeholder: null,
      seq: 10,
      verifyExp: '',
    },
    {
      columnType: 'NUMBER(11,0)',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      field: 'STATE',
      fieldType: null,
      id: '4684232299334737920',
      isDisabled: false,
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,
      label: '1可用；0禁用',
      parentField: null,
      placeholder: null,
      seq: 11,
      verifyExp: '',
    },
    {
      columnType: 'NUMBER(20,0)',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      field: 'EID',
      fieldType: null,
      id: '586223381686730752',
      isDisabled: false,
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,
      label: '企业ID',
      parentField: null,
      placeholder: null,
      seq: 12,
      verifyExp: '',
    },
    {
      columnType: 'NUMBER(20,0)',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      field: 'OID',
      fieldType: null,
      id: '2879034766054287360',
      isDisabled: false,
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,
      label: '组织ID',
      parentField: null,
      placeholder: null,
      seq: 13,
      verifyExp: '',
    },
  ],
} as DomainParamButtonSetting;
