import { DomainParamSetting } from '@/api/main';

export default {
  tableSetting: {
    columnSetting: [
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '单据编号',
        columnKey: null,
        columnName: 'BILL_NO',
        columnType: 'NVARCHAR2',
        columnWidth: 100,
        componentSource: null,
        id: '3817610567148699648',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: true,
        nullable: 'NO',
        seq: 1,
        tableName: 'E_REPAIR_BILL_HEAD',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '单据状态',
        columnKey: null,
        columnName: 'STATUS',
        columnType: 'NVARCHAR2',
        columnWidth: 100,
        componentSource: {
          customDict: {
            dicData: [
              {
                label: '待维修',
                value: 'UNREPAIR',
              },
              {
                label: '维修中',
                value: 'REPAIRING',
              },
              {
                label: '已关闭',
                value: 'CLOSED',
              },
              {
                label: '待验收',
                value: 'UNACCEPT',
              },
            ],
          },
          dataTable: null,
          sourceType: null,
        },
        id: '8850436575350861824',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: true,
        nullable: 'NO',
        seq: 2,
        tableName: 'E_REPAIR_BILL_HEAD',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '位置',
        columnKey: null,
        columnName: 'POSITION_PATH',
        columnType: 'NVARCHAR2',
        columnWidth: 100,
        componentSource: null,
        id: '2435293340360278016',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: false,
        isHandAdd: true,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: true,
        nullable: null,
        seq: 3,
        tableName: 'P_WORKCENTER_20240906091746',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '报障人',
        columnKey: null,
        columnName: 'CREATOR',
        columnType: 'NVARCHAR2',
        columnWidth: 100,
        componentSource: null,
        id: '8020943246535555072',
        isAutoWidth: true,
        isDataDefault: true,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: true,
        nullable: 'NO',
        seq: 4,
        tableName: 'E_REPAIR_BILL_HEAD',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '模具名称',
        columnKey: null,
        columnName: 'MOULD_NAME',
        columnType: 'NVARCHAR2',
        columnWidth: 100,
        componentSource: null,
        id: '7768711525279301632',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: false,
        isHandAdd: true,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: true,
        nullable: null,
        seq: 5,
        tableName: 'M_EQUIPMENT_INFO',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '模具编码',
        columnKey: null,
        columnName: 'MOULD_CODE',
        columnType: 'NVARCHAR2',
        columnWidth: 100,
        componentSource: null,
        id: '4829886563371386880',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: false,
        isHandAdd: true,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: true,
        nullable: null,
        seq: 6,
        tableName: 'M_EQUIPMENT_INFO',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '模具类型',
        columnKey: null,
        columnName: 'mould_Type_Name',
        columnType: 'NVARCHAR2',
        columnWidth: 100,
        componentSource: null,
        id: '2188065888283648000',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: false,
        isHandAdd: true,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: true,
        nullable: null,
        seq: 7,
        tableName: 'M_ASSET_TYPE_20240906094910',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '故障编码',
        columnKey: null,
        columnName: 'REPAIR_ITEM_CODE',
        columnType: 'NVARCHAR2',
        columnWidth: 100,
        componentSource: null,
        id: '8864933043503343616',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: false,
        isHandAdd: true,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: true,
        nullable: null,
        seq: 8,
        tableName: 'E_REPAIR_BILL_DTL_20240906101005',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '故障描述',
        columnKey: null,
        columnName: 'REPAIR_ITEM_DESC',
        columnType: 'NVARCHAR2',
        columnWidth: 100,
        componentSource: null,
        id: '4256521252783656960',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: false,
        isHandAdd: true,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: true,
        nullable: null,
        seq: 9,
        tableName: 'E_REPAIR_BILL_DTL_20240906101005',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '维修人',
        columnKey: null,
        columnName: 'user_repair_name',
        columnType: 'NVARCHAR2',
        columnWidth: 100,
        componentSource: null,
        id: '2216900692105072640',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: false,
        isHandAdd: true,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: true,
        nullable: null,
        seq: 10,
        tableName: 'S_USER_DEAL',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '维修方法',
        columnKey: null,
        columnName: 'REPAIR_ITEM_METHOD',
        columnType: 'NVARCHAR2',
        columnWidth: 100,
        componentSource: null,
        id: '8610061764884682752',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: false,
        isHandAdd: true,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: true,
        nullable: null,
        seq: 11,
        tableName: 'E_REPAIR_BILL_DTL_20240906101005',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '维修内容',
        columnKey: null,
        columnName: 'SOLVE_ITEM_METHOD',
        columnType: 'NVARCHAR2',
        columnWidth: 100,
        componentSource: null,
        id: '8920705448081975296',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: false,
        isHandAdd: true,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: true,
        nullable: null,
        seq: 12,
        tableName: 'E_REPAIR_BILL_DTL_20240906101005',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '验收人',
        columnKey: null,
        columnName: 'user_accept_name',
        columnType: 'NVARCHAR2',
        columnWidth: 100,
        componentSource: null,
        id: '5098980410914086912',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: false,
        isHandAdd: true,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: true,
        nullable: null,
        seq: 13,
        tableName: 'S_USER_ACCEPT',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '报障位置ID',
        columnKey: null,
        columnName: 'P_WORKCENTER_ID',
        columnType: 'NUMBER(20,0)',
        columnWidth: 100,
        componentSource: null,
        id: '2786381968799238144',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'YES',
        seq: 14,
        tableName: 'E_REPAIR_BILL_HEAD',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '备注',
        columnKey: null,
        columnName: 'MEMO',
        columnType: 'NVARCHAR2',
        columnWidth: 100,
        componentSource: null,
        id: '5025250635246051328',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'YES',
        seq: 15,
        tableName: 'E_REPAIR_BILL_HEAD',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '维修处理组ID',
        columnKey: null,
        columnName: 'REPAIR_DEAL_ID',
        columnType: 'NUMBER(20,0)',
        columnWidth: 100,
        componentSource: null,
        id: '1303969115961960448',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'YES',
        seq: 16,
        tableName: 'E_REPAIR_BILL_HEAD',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '维修验收组ID',
        columnKey: null,
        columnName: 'REPAIR_ACCEPT_ID',
        columnType: 'NUMBER(20,0)',
        columnWidth: 100,
        componentSource: null,
        id: '4722783879264217088',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'YES',
        seq: 17,
        tableName: 'E_REPAIR_BILL_HEAD',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '设备ID',
        columnKey: null,
        columnName: 'M_EQUIPMENT_ID',
        columnType: 'NUMBER(20,0)',
        columnWidth: 100,
        componentSource: null,
        id: '1652611653440073728',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'YES',
        seq: 18,
        tableName: 'E_REPAIR_BILL_HEAD',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '维修人员ID',
        columnKey: null,
        columnName: 'USER_REPAIR_ID',
        columnType: 'NUMBER(20,0)',
        columnWidth: 100,
        componentSource: null,
        id: '648519157212565504',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'YES',
        seq: 19,
        tableName: 'E_REPAIR_BILL_HEAD',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '维修开始时间',
        columnKey: null,
        columnName: 'DATETIME_REPAIR_START',
        columnType: 'DATE',
        columnWidth: 100,
        componentSource: null,
        id: '7364684960741351424',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'YES',
        seq: 20,
        tableName: 'E_REPAIR_BILL_HEAD',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '维修完成时间',
        columnKey: null,
        columnName: 'DATETIME_REPAIR_END',
        columnType: 'DATE',
        columnWidth: 100,
        componentSource: null,
        id: '8029215550663530496',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'YES',
        seq: 21,
        tableName: 'E_REPAIR_BILL_HEAD',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '验收人员ID',
        columnKey: null,
        columnName: 'USER_ACCEPT_ID',
        columnType: 'NUMBER(20,0)',
        columnWidth: 100,
        componentSource: null,
        id: '5698955188202868736',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'YES',
        seq: 22,
        tableName: 'E_REPAIR_BILL_HEAD',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '验收时间',
        columnKey: null,
        columnName: 'DATETIME_ACCEPT',
        columnType: 'DATE',
        columnWidth: 100,
        componentSource: null,
        id: '2593952469310851072',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'YES',
        seq: 23,
        tableName: 'E_REPAIR_BILL_HEAD',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '模具ID',
        columnKey: null,
        columnName: 'M_MOULD_ID',
        columnType: 'NUMBER(20,0)',
        columnWidth: 100,
        componentSource: null,
        id: '6239969415580448768',
        isAutoWidth: true,
        isDataDefault: false,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'NO',
        seq: 24,
        tableName: 'E_REPAIR_BILL_HEAD',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: null,
        columnKey: null,
        columnName: 'ID',
        columnType: 'NUMBER(20,0)',
        columnWidth: 100,
        componentSource: null,
        id: '4314106228146837504',
        isAutoWidth: true,
        isDataDefault: true,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'NO',
        seq: 25,
        tableName: 'E_REPAIR_BILL_HEAD',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '创建时间',
        columnKey: null,
        columnName: 'TIME_CREATE',
        columnType: 'DATE',
        columnWidth: 100,
        componentSource: null,
        id: '7343209758527444992',
        isAutoWidth: true,
        isDataDefault: true,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'NO',
        seq: 26,
        tableName: 'E_REPAIR_BILL_HEAD',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '修改时间',
        columnKey: null,
        columnName: 'TIME_MODIFIED',
        columnType: 'DATE',
        columnWidth: 100,
        componentSource: null,
        id: '2112088375566444544',
        isAutoWidth: true,
        isDataDefault: true,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'YES',
        seq: 27,
        tableName: 'E_REPAIR_BILL_HEAD',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '修改人',
        columnKey: null,
        columnName: 'MODIFIER',
        columnType: 'NVARCHAR2',
        columnWidth: 100,
        componentSource: null,
        id: '7057108901527076864',
        isAutoWidth: true,
        isDataDefault: true,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'YES',
        seq: 28,
        tableName: 'E_REPAIR_BILL_HEAD',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '1可用；0禁用',
        columnKey: null,
        columnName: 'STATE',
        columnType: 'NUMBER(11,0)',
        columnWidth: 100,
        componentSource: null,
        id: '7108386235242416128',
        isAutoWidth: true,
        isDataDefault: true,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'NO',
        seq: 29,
        tableName: 'E_REPAIR_BILL_HEAD',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '企业ID',
        columnKey: null,
        columnName: 'EID',
        columnType: 'NUMBER(20,0)',
        columnWidth: 100,
        componentSource: null,
        id: '4450276768562325504',
        isAutoWidth: true,
        isDataDefault: true,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'NO',
        seq: 30,
        tableName: 'E_REPAIR_BILL_HEAD',
      },
      {
        align: 'center',
        canDelete: false,
        columnDefault: null,
        columnDesc: '组织ID',
        columnKey: null,
        columnName: 'OID',
        columnType: 'NUMBER(20,0)',
        columnWidth: 100,
        componentSource: null,
        id: '4895560374999480320',
        isAutoWidth: true,
        isDataDefault: true,
        isDatabaseField: true,
        isHandAdd: false,
        isLeftFixed: false,
        isRightFixed: false,
        isVisible: false,
        nullable: 'NO',
        seq: 31,
        tableName: 'E_REPAIR_BILL_HEAD',
      },
    ],
    isAutoLoad: true,
    pageSize: null,
    sortField: 'time_create',
    sortType: 'desc',
    tableTitle: '设备维修单据头表',
    usePage: true,
  },
} as DomainParamSetting;
