import { DomainParamButtonSetting } from '@/api/main';

export default {
  formColumnSetting: [
    {
      columnType: 'varchar(80)',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      isDisabled: false,
      field: 'repair_item_code',
      fieldType: null,
      id: '5560537921682362368',
      isDisabled: false,
      isKeyField: true,
      isMultiple: false,
      isRequired: true,
      isVisible: true,
      isKeyField: true,
      label: '故障代码',
      isMultiple: false,
      placeholder: null,
      isRequired: true,
      seq: 1,
      verifyExp: '',
    },
    {
      columnType: 'varchar(2000)',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      isDisabled: false,
      field: 'repair_item_method',
      fieldType: null,
      id: '7137773478589517824',
      isDisabled: false,
      isKeyField: false,
      isMultiple: false,
      isRequired: true,
      isVisible: true,
      isKeyField: false,
      label: '维修方法',
      isMultiple: false,
      placeholder: null,
      isRequired: true,
      seq: 2,
      verifyExp: '',
    },
    {
      columnType: 'varchar(2000)',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      isDisabled: false,
      field: 'repair_item_name',
      fieldType: null,
      id: '8964722529001308160',
      isDisabled: false,
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: true,
      isKeyField: false,
      label: '故障描述',
      isMultiple: false,
      placeholder: null,
      isRequired: false,
      seq: 3,
      verifyExp: '',
    },
    {
      columnType: 'int',
      component: 't-switch',
      componentParam: '',
      componentSource: null,
      defaultValue: '1',
      isDisabled: false,
      field: 'state',
      fieldType: null,
      id: '8025390211176169472',
      isDisabled: false,
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: true,
      isKeyField: false,
      label: '启用',
      isMultiple: false,
      placeholder: null,
      isRequired: false,
      seq: 4,
      verifyExp: '',
    },
    {
      columnType: 'varchar(80)',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      isDisabled: false,
      field: 'creator',
      fieldType: null,
      id: '6593358722933473280',
      isDisabled: false,
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,
      isKeyField: false,
      label: '创建人',
      isMultiple: false,
      placeholder: null,
      isRequired: false,
      seq: 5,
      verifyExp: '',
    },
    {
      columnType: 'bigint',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      isDisabled: false,
      field: 'eid',
      fieldType: null,
      id: '3156519966244200448',
      isDisabled: false,
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,
      isKeyField: false,
      label: '企业ID',
      isMultiple: false,
      placeholder: null,
      isRequired: false,
      seq: 6,
      verifyExp: '',
    },
    {
      columnType: 'bigint',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      isDisabled: false,
      field: 'id',
      fieldType: null,
      id: '3433588720423458816',
      isDisabled: false,
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,
      isKeyField: false,
      label: '',
      isMultiple: false,
      placeholder: null,
      isRequired: false,
      seq: 7,
      verifyExp: '',
    },
    {
      columnType: 'varchar(80)',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      isDisabled: false,
      field: 'modifier',
      fieldType: null,
      id: '1442247135381493760',
      isDisabled: false,
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,
      isKeyField: false,
      label: '修改人',
      isMultiple: false,
      placeholder: null,
      isRequired: false,
      seq: 8,
      verifyExp: '',
    },
    {
      columnType: 'bigint',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      isDisabled: false,
      field: 'oid',
      fieldType: null,
      id: '4217611165175418880',
      isDisabled: false,
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,
      isKeyField: false,
      label: '组织ID',
      isMultiple: false,
      placeholder: null,
      isRequired: false,
      seq: 9,
      verifyExp: '',
    },
    {
      columnType: 'datetime(4)',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      isDisabled: false,
      field: 'time_create',
      fieldType: null,
      id: '2834159895836973056',
      isDisabled: false,
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,
      isKeyField: false,
      label: '创建时间',
      isMultiple: false,
      placeholder: null,
      isRequired: false,
      seq: 10,
      verifyExp: '',
    },
    {
      columnType: 'datetime(4)',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      isDisabled: false,
      field: 'time_modified',
      fieldType: null,
      id: '8481970777069451264',
      isDisabled: false,
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,
      isKeyField: false,
      label: '修改时间',
      isMultiple: false,
      placeholder: null,
      isRequired: false,
      seq: 11,
      verifyExp: '',
    },
  ],
} as DomainParamButtonSetting;
