import { DomainParamTableColumn } from '@/api/main';

export default {
  formColumnSetting: [
    {
      columnType: 'bigint',
      component: 'bcmp-select-business',
      componentParam: 'repairItem',
      componentSource: null,
      defaultValue: '',
      isDisabled: false,
      field: 'e_repair_item_id',
      fieldType: null,
      id: '7074169511581835264',
      isKeyField: false,
      isMultiple: false,
      isRequired: true,
      isVisible: true,
      label: '维修项目',
      placeholder: null,
      seq: 1,
      verifyExp: '',
    },
    {
      columnType: 'String',
      component: 't-radio-group',
      componentSource: {
        sourceType: 'customDict',
        customDict: {
          dicData: [
            {
              label: '关联模具类型',
              value: 'mouldType',
            },
            {
              label: '关联模具',
              value: 'mould',
            },
          ],
        },
        dataTable: {
          mapBusinessDomain: '',
          mapTable: '',
          conditionData: [],
          valueField: '',
          showField: '',
        },
      },
      defaultValue: 'mouldType',
      isDisabled: false,
      field: 'relateType',
      fieldType: null,
      id: 'relateType',
      isKeyField: false,
      isMultiple: false,
      isRequired: true,
      isVisible: true,
      label: '关联类型',
      placeholder: null,
      seq: 2,
      verifyExp: '',
    },
    {
      columnType: 'varchar(80)',
      component: 'bcmp-select-param',
      componentParam: 'E_MOULD_TYPE',
      componentSource: null,
      defaultValue: '',
      isDisabled: false,
      field: 'mouldType',
      fieldType: null,
      id: '6576171639978893312',
      isKeyField: false,
      isMultiple: false,
      isRequired: true,
      isVisible: true,
      label: '模具类型',
      placeholder: null,
      seq: 3,
      verifyExp: '',
    },
    {
      columnType: 'bigint',
      component: 'bcmp-select-business',
      componentParam: 'mould',
      componentSource: null,
      defaultValue: '',
      isDisabled: false,
      field: 'mouldId',
      fieldType: null,
      id: '8794653969524314112',
      isKeyField: false,
      isMultiple: false,
      isRequired: true,
      isVisible: false,
      label: '模具',
      placeholder: null,
      seq: 2,
      verifyExp: '',
    },
    {
      columnType: 'bigint',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      isDisabled: false,
      field: 'm_asset_brand_id',
      fieldType: null,
      id: '5071067676293683200',
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,
      label: '资产品牌表ID',
      placeholder: null,
      seq: 4,
      verifyExp: '',
    },
    {
      columnType: 'bigint',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      isDisabled: false,
      field: 'm_asset_model_id',
      fieldType: null,
      id: '3360122505327278080',
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,
      label: '资产型号表ID',
      placeholder: null,
      seq: 5,
      verifyExp: '',
    },
    {
      columnType: 'bigint',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      isDisabled: false,
      field: 'm_asset_type_id',
      fieldType: null,
      id: '5519903825985478656',
      isKeyField: false,
      isMultiple: false,
      isRequired: true,
      isVisible: false,
      label: '资产类型表ID',
      placeholder: null,
      seq: 6,
      verifyExp: '',
    },
    {
      columnType: 'varchar(80)',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      isDisabled: false,
      field: 'creator',
      fieldType: null,
      id: '1751860826946289664',
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,
      label: '创建人',
      placeholder: null,
      seq: 7,
      verifyExp: '',
    },
    {
      columnType: 'bigint',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      isDisabled: false,
      field: 'eid',
      fieldType: null,
      id: '8646565055337807872',
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,
      label: '企业ID',
      placeholder: null,
      seq: 8,
      verifyExp: '',
    },
    {
      columnType: 'bigint',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      isDisabled: false,
      field: 'id',
      fieldType: null,
      id: '2743916374271356928',
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,
      label: '',
      placeholder: null,
      seq: 9,
      verifyExp: '',
    },
    {
      columnType: 'varchar(80)',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      isDisabled: false,
      field: 'modifier',
      fieldType: null,
      id: '41912747687444480',
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,
      label: '修改人',
      placeholder: null,
      seq: 10,
      verifyExp: '',
    },
    {
      columnType: 'bigint',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      isDisabled: false,
      field: 'oid',
      fieldType: null,
      id: '8872780942841815040',
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,
      label: '组织ID',
      placeholder: null,
      seq: 11,
      verifyExp: '',
    },
    {
      columnType: 'int',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      isDisabled: false,
      field: 'state',
      fieldType: null,
      id: '7113690172860616704',
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,
      label: '1可用；0禁用',
      placeholder: null,
      seq: 12,
      verifyExp: '',
    },
    {
      columnType: 'datetime(4)',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      isDisabled: false,
      field: 'time_create',
      fieldType: null,
      id: '4839361570755266560',
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,
      label: '创建时间',
      placeholder: null,
      seq: 13,
      verifyExp: '',
    },
    {
      columnType: 'datetime(4)',
      component: 't-input',
      componentParam: '',
      componentSource: null,
      defaultValue: '',
      isDisabled: false,
      field: 'time_modified',
      fieldType: null,
      id: '684207745880256512',
      isKeyField: false,
      isMultiple: false,
      isRequired: false,
      isVisible: false,
      label: '修改时间',
      placeholder: null,
      seq: 14,
      verifyExp: '',
    },
  ],
} as DomainParamTableColumn;
